packages:
  - apps/*
  - packages/*
overrides:
  '@payloadcms/db-sqlite@3.90.2>@libsql/client': 0.18.0
allowBuilds:
  esbuild: true
patchedDependencies:
  '@payloadcms/drizzle@3.90.2': patches/@payloadcms__drizzle@3.90.2.patch
minimumReleaseAgeExclude:
  - '@modelcontextprotocol/sdk@1.32.0'
