'use client'
import { useEffect, useMemo, useState } from 'react'
import styles from './email-workspace.module.css'

type Mailbox = { id: string; name: string; primaryAddress: string; aliases: string[]; host: string; port: number; security: 'starttls' | 'tls'; username: string; health: string; testedAt: string | null; credentialConfigured: boolean; credentialHint: string | null }
type Mapping = { id: string; area: 'leads' | 'careers' | 'notifications'; mailbox: string; senderAddress: string }
type Workspace = { providers: { microsoft: { status: string }; google: { status: string }; smtp: { status: string } }; mailboxes: Mailbox[]; mappings: Mapping[] }
const areas = [{ id: 'leads', name: 'Leads', description: 'Replies to inquiries and follow-up threads.' }, { id: 'careers', name: 'Careers', description: 'Replies to applicants for every role.' }, { id: 'notifications', name: 'Notifications', description: 'Alerts and review requests sent to staff.' }] as const
type SMTPForm = { id: string; name: string; primaryAddress: string; aliases: string; host: string; port: string; security: 'starttls' | 'tls'; username: string; password: string }
const emptyForm: SMTPForm = { id: '', name: '', primaryAddress: '', aliases: '', host: '', port: '587', security: 'starttls', username: '', password: '' }

export function EmailWorkspace() {
  const [workspace, setWorkspace] = useState<Workspace | null>(null); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [editing, setEditing] = useState(false); const [form, setForm] = useState<SMTPForm>(emptyForm); const [testing, setTesting] = useState<Mailbox | null>(null); const [testRecipient, setTestRecipient] = useState(''); const [confirmed, setConfirmed] = useState(false)
  const load = async () => { const response = await fetch('/api/email-workspace', { cache: 'no-store' }); const value = await response.json() as Workspace & { error?: string }; if (!response.ok) throw new Error(value.error || 'Email workspace could not be loaded.'); setWorkspace(value) }
  useEffect(() => { void load().catch((caught) => setError(caught instanceof Error ? caught.message : 'Email workspace could not be loaded.')) }, [])
  const request = async (value: Record<string, unknown>) => { setBusy(true); setError(''); setMessage(''); try { const response = await fetch('/api/email-workspace', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(value) }); const result = await response.json() as Workspace & { error?: string }; if (!response.ok) throw new Error(result.error || 'Email workspace request could not be completed.'); setWorkspace(result); return true } catch (caught) { setError(caught instanceof Error ? caught.message : 'Email workspace request could not be completed.'); return false } finally { setBusy(false) } }
  const addresses = useMemo(() => new Map((workspace?.mailboxes ?? []).map((mailbox) => [mailbox.id, [mailbox.primaryAddress, ...mailbox.aliases]])), [workspace])
  const edit = (mailbox?: Mailbox) => { setForm(mailbox ? { id: mailbox.id, name: mailbox.name, primaryAddress: mailbox.primaryAddress, aliases: mailbox.aliases.join(', '), host: mailbox.host, port: String(mailbox.port), security: mailbox.security, username: mailbox.username, password: '' } : emptyForm); setEditing(true); setError(''); setMessage('') }
  const save = async (event: React.FormEvent) => { event.preventDefault(); const ok = await request({ action: 'configure-smtp', ...(form.id ? { id: form.id } : {}), name: form.name, primaryAddress: form.primaryAddress, aliases: form.aliases.split(',').map((item) => item.trim()).filter(Boolean), host: form.host, port: Number(form.port), security: form.security, username: form.username, ...(form.password ? { password: form.password } : {}) }); if (ok) { setEditing(false); setMessage('SMTP mailbox saved. Test the connection before sending.') } }
  const connection = async (mailbox: Mailbox) => { if (await request({ action: 'test-connection', id: mailbox.id })) setMessage('SMTP connection test completed.') }
  const map = async (area: string, value: string) => { const [mailbox, ...sender] = value.split('|'); if (await request({ action: 'map-area', area, mailbox, senderAddress: sender.join('|') })) setMessage(`${areas.find((item) => item.id === area)?.name} sender updated.`) }
  const send = async (event: React.FormEvent) => { event.preventDefault(); if (!testing) return; const ok = await request({ action: 'send-test', requestKey: crypto.randomUUID(), mailbox: testing.id, senderAddress: testing.primaryAddress, recipientAddress: testRecipient, subject: 'Mailbox delivery test', body: 'This synthetic test confirms that the configured mailbox can deliver email.', confirmed }); if (ok) { setTesting(null); setConfirmed(false); setTestRecipient(''); setMessage('Test message accepted by the configured SMTP service.') } }
  return <div className={styles.workspace} data-email-workspace>
    {(error || message) && <p className={error ? styles.error : styles.status} role={error ? 'alert' : 'status'}>{error || message}</p>}
    <div className={styles.providers} data-email-providers>
      <article><header><strong>Microsoft 365</strong><span>Available</span></header><p>Replies and alerts through Microsoft Graph, with a copy in Sent Items.</p><small>Not connected · requires a tenant app, mailbox consent, and Mail.Send.</small></article>
      <article><header><strong>Google Workspace</strong><span>Available</span></header><p>Replies and alerts through the Gmail API.</p><small>Not connected · requires a Google Cloud app, mailbox consent, and gmail.send.</small></article>
      <article data-connected={String(workspace?.providers.smtp.status === 'connected')}><header><strong>SMTP</strong><span>{workspace?.providers.smtp.status === 'connected' ? 'Connected' : workspace?.providers.smtp.status === 'configured' ? 'Configured' : 'Available'}</span></header><p>Fallback for any mail provider using TLS and an encrypted password.</p><small>{workspace?.mailboxes.length ? `${workspace.mailboxes.length} mailbox${workspace.mailboxes.length === 1 ? '' : 'es'} configured` : 'No mailbox configured'}</small><button type="button" onClick={() => edit()}>{workspace?.mailboxes.length ? 'Connect another' : 'Configure'}</button></article>
    </div>
    {editing && <section className={styles.editor} aria-labelledby="smtp-editor-title" data-email-editor><header><div><h2 id="smtp-editor-title">{form.id ? 'Update SMTP mailbox' : 'Connect SMTP mailbox'}</h2><p>The password is encrypted and cannot be read back.</p></div><button type="button" aria-label="Close SMTP configuration" onClick={() => setEditing(false)}>×</button></header><form onSubmit={(event) => void save(event)}><div className={styles.formGrid}><label>Mailbox name<input required maxLength={120} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })}/></label><label>Primary address<input required type="email" value={form.primaryAddress} onChange={(event) => setForm({ ...form, primaryAddress: event.target.value })}/></label><label className={styles.wide}>Aliases <small>Comma-separated</small><input value={form.aliases} onChange={(event) => setForm({ ...form, aliases: event.target.value })}/></label><label>SMTP host<input required value={form.host} onChange={(event) => setForm({ ...form, host: event.target.value })}/></label><label>Port<input required type="number" min="1" max="65535" value={form.port} onChange={(event) => setForm({ ...form, port: event.target.value })}/></label><label>Security<select value={form.security} onChange={(event) => setForm({ ...form, security: event.target.value as 'starttls' | 'tls' })}><option value="starttls">STARTTLS</option><option value="tls">TLS</option></select></label><label>Username<input required value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })}/></label><label className={styles.wide}>Password<input required={!form.id} type="password" autoComplete="new-password" value={form.password} placeholder={form.id ? 'Leave blank to keep the saved password' : ''} onChange={(event) => setForm({ ...form, password: event.target.value })}/></label></div><footer><button type="button" onClick={() => setEditing(false)}>Cancel</button><button className={styles.primary} disabled={busy}>Save mailbox</button></footer></form></section>}
    <section className={styles.mailboxes} aria-labelledby="mailboxes-title"><header><div><h2 id="mailboxes-title">Mailboxes and addresses</h2><p>Connect one mailbox or several. Each area sends from its assigned primary address or alias.</p></div></header>
      {(workspace?.mailboxes ?? []).map((mailbox) => <article key={mailbox.id} data-mailbox-row><div><strong>{mailbox.name}</strong><code>{mailbox.primaryAddress}</code><span>{mailbox.aliases.length ? `Aliases: ${mailbox.aliases.join(', ')}` : 'No aliases'}</span></div><div><span data-health={mailbox.health}>{mailbox.health === 'connected' ? 'Connection verified' : mailbox.health === 'unknown' ? 'Not tested' : 'Connection unavailable'}</span><small>{mailbox.credentialHint}</small></div><div><button type="button" disabled={busy} onClick={() => void connection(mailbox)}>Test connection</button><button type="button" onClick={() => edit(mailbox)}>Edit</button><button type="button" disabled={mailbox.health !== 'connected'} onClick={() => setTesting(mailbox)}>Send test</button></div></article>)}
      {!workspace?.mailboxes.length && <p className={styles.empty}>No mailbox is connected. Configure SMTP above; Microsoft and Google remain unavailable until their tenant apps are registered.</p>}
      <div className={styles.mappingHeader}><strong>Area</strong><span>Sender address</span><span>Purpose</span></div>{areas.map((area) => { const current = workspace?.mappings.find((item) => item.area === area.id); return <div className={styles.mapping} key={area.id}><strong>{area.name}</strong><select aria-label={`${area.name} sender address`} value={current ? `${current.mailbox}|${current.senderAddress}` : ''} disabled={!workspace?.mailboxes.length || busy} onChange={(event) => void map(area.id, event.target.value)}><option value="">Not assigned</option>{workspace?.mailboxes.flatMap((mailbox) => (addresses.get(mailbox.id) ?? []).map((address) => <option key={`${mailbox.id}|${address}`} value={`${mailbox.id}|${address}`}>{address}{address !== mailbox.primaryAddress ? ' (alias)' : ''}</option>))}</select><span>{area.description}</span></div> })}
    </section>
    {testing && <section className={styles.test} aria-labelledby="test-send-title"><h2 id="test-send-title">Authorize a test send</h2><p>This sends one real message through <strong>{testing.name}</strong>. Review the exact recipient before confirming.</p><form onSubmit={(event) => void send(event)}><label>From<input readOnly value={testing.primaryAddress}/></label><label>Recipient<input required type="email" value={testRecipient} onChange={(event) => setTestRecipient(event.target.value)}/></label><label className={styles.confirm}><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)}/> I authorize this exact one-time test message.</label><footer><button type="button" onClick={() => setTesting(null)}>Cancel</button><button className={styles.primary} disabled={!confirmed || busy}>Authorize and send</button></footer></form></section>}
  </div>
}
