'use client'

import { useCallback, useEffect, useState } from 'react'
import styles from './notification-preferences.module.css'

type Kind = 'new-lead' | 'active-incident-lead' | 'new-job-application' | 'change-set-submitted' | 'follow-ups-due' | 'publish-or-integration-failed'
type Recipient = 'owner' | 'sales' | 'hiring' | 'approver' | 'lead-owner' | 'urgent-contact'
type Channel = 'email' | 'sms'
type Preference = { kind: Kind; enabled: boolean; recipients: Recipient[]; channels: Channel[]; cadence: 'immediate' | 'daily-0800' }
type Response = { events: Preference[]; capabilities: { emailDelivery: boolean; smsDelivery: boolean; producers: Record<Kind, boolean> } }
const labels: Record<Kind, string> = { 'new-lead': 'New lead', 'active-incident-lead': 'Active incident lead', 'new-job-application': 'New job application', 'change-set-submitted': 'Change set submitted for review', 'follow-ups-due': 'Follow-ups due', 'publish-or-integration-failed': 'Publish failed or integration down' }
const recipientLabels: Record<Recipient, string> = { owner: 'Owners', sales: 'Sales', hiring: 'Hiring', approver: 'Approvers', 'lead-owner': 'Lead owners', 'urgent-contact': 'Incident contacts' }
const recipients: Recipient[] = ['owner', 'sales', 'hiring', 'approver', 'lead-owner', 'urgent-contact']
const channels: Channel[] = ['email', 'sms']

export function NotificationPreferences() {
  const [events, setEvents] = useState<Preference[]>([]); const [capabilities, setCapabilities] = useState<Response['capabilities'] | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  const load = useCallback(async (signal?: AbortSignal) => { setLoading(true); setError(''); try { const response = await fetch('/api/notification-settings', { cache: 'no-store', signal }); const body = await response.json() as Response & { error?: string }; if (!response.ok) throw new Error(body.error ?? 'Notification preferences could not be loaded.'); if (!signal?.aborted) { setEvents(body.events); setCapabilities(body.capabilities) } } catch (caught) { if (!signal?.aborted) setError(caught instanceof Error ? caught.message : 'Notification preferences could not be loaded.') } finally { if (!signal?.aborted) setLoading(false) } }, [])
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort() }, [load])
  const update = (kind: Kind, patch: Partial<Preference>) => setEvents((current) => current.map((event) => event.kind === kind ? { ...event, ...patch } : event))
  const toggleRecipient = (event: Preference, recipient: Recipient) => { const selected = event.recipients.includes(recipient); const next = selected ? event.recipients.filter((value) => value !== recipient) : [...event.recipients, recipient]; if (next.length) update(event.kind, { recipients: next }) }
  const toggleChannel = (event: Preference, channel: Channel) => { const selected = event.channels.includes(channel); const next = selected ? event.channels.filter((value) => value !== channel) : [...event.channels, channel]; if (next.length) update(event.kind, { channels: next }) }
  const save = async () => { if (saving) return; setSaving(true); setMessage(''); setError(''); try { const response = await fetch('/api/notification-settings', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ events }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(response.status === 403 ? 'A fresh Owner sign-in is required before saving notification preferences.' : body.error ?? 'Notification preferences could not be saved.'); setMessage('Notification preferences saved.'); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Notification preferences could not be saved.') } finally { setSaving(false) } }
  return <div className={styles.layout} data-notification-preferences aria-busy={loading || saving}>
    <section className={styles.card} aria-labelledby="notification-routing-title">
      <header><div><h2 id="notification-routing-title">Who is told, and when</h2><p>Recipients are roles, so new staff are included automatically. Choose the Notifications sender in the <a href="/integrations?tab=email">Email tab</a>. Incident contacts are set in <a href="/site">Site › Business details</a>.</p></div><button type="button" onClick={() => void save()} disabled={loading || saving || !events.length}>{saving ? 'Saving…' : 'Save preferences'}</button></header>
      {(message || error) && <p className={error ? styles.error : styles.status} role={error ? 'alert' : 'status'}>{error || message}</p>}
      <div className={styles.tableHeader} aria-hidden="true"><span>Event</span><span>Recipients</span><span>How</span></div>
      {events.map((event) => <fieldset key={event.kind} className={styles.row} disabled={loading || saving}><legend className={styles.srOnly}>{labels[event.kind]}</legend><div className={styles.event}><strong>{labels[event.kind]}</strong>{!event.enabled && <small>Paused</small>}{!capabilities?.producers[event.kind] && <small>No event source is available yet.</small>}{event.kind === 'publish-or-integration-failed' && <small>Publish failures are recorded. Integration health alerts are not generated yet.</small>}</div><details className={styles.picker}><summary>{event.recipients.map((recipient) => recipientLabels[recipient]).join(', ')}</summary><div className={styles.menu}><label><input type="checkbox" checked={event.enabled} onChange={(input) => update(event.kind, { enabled: input.target.checked })}/>Create notification intent</label>{recipients.map((recipient) => <label key={recipient}><input type="checkbox" checked={event.recipients.includes(recipient)} onChange={() => toggleRecipient(event, recipient)}/>{recipientLabels[recipient]}</label>)}</div></details><details className={styles.picker}><summary>{event.channels.map((channel) => channel === 'email' ? 'Email' : 'Text').join(' + ')}{event.cadence === 'daily-0800' ? ', daily at 8:00' : ', immediately'}</summary><div className={styles.menu}>{channels.map((channel) => <label key={channel}><input type="checkbox" checked={event.channels.includes(channel)} onChange={() => toggleChannel(event, channel)}/>{channel === 'email' ? 'Email' : 'Text message'}</label>)}</div></details></fieldset>)}
    </section>
    <aside className={styles.aside}><section className={styles.card} data-notification-sidebar="sms"><header className={styles.cardTitle}><h2>Text messages</h2><span data-configured={String(Boolean(capabilities?.smsDelivery))}>{capabilities?.smsDelivery ? 'Available' : 'Not connected'}</span></header><p>Text messages are needed only for Active incident alerts. SMS delivery is not connected.</p></section><section className={styles.card} data-notification-sidebar="templates"><header className={styles.cardTitle}><h2>Email templates</h2><span>{capabilities?.emailDelivery ? 'Delivery available' : 'Delivery inactive'}</span></header><p>Email delivery is not connected. Notification messages are queued. Templates are not yet configurable.</p></section></aside>
  </div>
}
