import { createHash } from 'node:crypto'
import { lstat, readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { getPayload } from 'payload'
import config from '../../../../../../../payload.config'
import { serverSessionStrategy } from '../../../../../../../src/identity'
export const dynamic = 'force-dynamic'
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i, digest=/^[a-f0-9]{64}$/
const headers={'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}
const retention=()=>{const n=Number(process.env.PREVIEW_EVIDENCE_RETENTION_DAYS??30);return Number.isInteger(n)&&n>=1&&n<=365?n:30}
export async function GET(request:Request,context:{params:Promise<{jobID:string;variant:string}>}) { const {jobID,variant}=await context.params;if(!uuid.test(jobID)||!['live','proposed'].includes(variant))return new Response(null,{status:404,headers});const payload=await getPayload({config}),auth=await serverSessionStrategy.authenticate({headers:request.headers,payload}),user=auth.user as {roles?:string[]}|null;if(!user)return new Response(null,{status:401,headers});if(!user.roles?.some(r=>r==='owner'||r==='approver'))return new Response(null,{status:403,headers});try{const job=await payload.findByID({collection:'preview-render-jobs',id:jobID,depth:0,overrideAccess:true}) as unknown as Record<string,unknown>,shot=(job.evidenceManifest as {screenshots?:Record<string,{path?:unknown;bytes?:unknown;sha256?:unknown}>}|undefined)?.screenshots?.[variant];if(job.status!=='completed'||!job.completedAt||Date.parse(String(job.completedAt))+retention()*86400000<=Date.now()||!shot||shot.path!==`evidence/${variant}.png`||!Number.isInteger(shot.bytes)||typeof shot.sha256!=='string'||!digest.test(shot.sha256))return new Response(null,{status:404,headers});const root=process.env.PREVIEW_ARTIFACT_ROOT;if(!root?.startsWith('/'))throw Error();const base=resolve(root,jobID),file=resolve(base,String(shot.path));if(!file.startsWith(`${base}/`))throw Error();const stat=await lstat(file);if(!stat.isFile()||stat.isSymbolicLink()||stat.size!==shot.bytes||stat.size>5242880)throw Error();const body=await readFile(file);if(createHash('sha256').update(body).digest('hex')!==shot.sha256)throw Error();return new Response(body,{headers:{...headers,'Content-Type':'image/png','Content-Length':String(body.length)}})}catch{return new Response(null,{status:404,headers})} }
