import type { Dispatch, SetStateAction } from 'react'
import styles from './site-workspace.module.css'
import { emptyNavigation, type Reference, type References, type Settings } from './site-types'

type Props = { busy: boolean; canSave: boolean; references: References; settings: Settings; setSettings: Dispatch<SetStateAction<Settings | null>>; save: () => void }
const move = <T,>(items: T[], index: number, direction: -1 | 1) => { const next = [...items]; const target = index + direction; if (target < 0 || target >= next.length) return next; [next[index], next[target]] = [next[target], next[index]]; return next }

export function SiteNavigationEditor({ busy, canSave, references, settings, setSettings, save }: Props) {
  const navigation = settings.navigation ?? emptyNavigation
  const options = (kind: Reference['kind']) => kind === 'page' ? references.pages : references.sections
  const setNavigation = (next: typeof navigation) => setSettings({ ...settings, navigation: next })
  const updateHeader = (index: number, patch: Partial<Reference>) => { const next = structuredClone(navigation); next.header[index] = { ...next.header[index], ...patch }; setNavigation(next) }
  const updateColumn = (index: number, patch: Partial<(typeof navigation.footer.columns)[number]>) => { const next = structuredClone(navigation); next.footer.columns[index] = { ...next.footer.columns[index], ...patch }; setNavigation(next) }
  return <section className={styles.panel} data-site-panel="navigation"><header><h2>Navigation</h2><p>Choose explicit, ordered links for the public header and footer. References are checked when saved.</p></header>
    <form onSubmit={event => { event.preventDefault(); save() }}><fieldset disabled={busy}><legend>Header</legend>
      {navigation.header.map((item,index) => <div className={styles.navEditor} key={`${index}-${item.kind}-${item.id}`} data-site-navigation-item><label>Type<select value={item.kind} onChange={event => { const kind=event.target.value as Reference['kind']; updateHeader(index,{kind,id:options(kind)[0]?.id ?? ''}) }}><option value="page">Page</option><option value="section">Section</option></select></label><label>Destination<select required value={item.id} onChange={event=>updateHeader(index,{id:event.target.value})}>{options(item.kind).map(option=><option key={option.id} value={option.id}>{option.title}</option>)}</select></label><label>Label<input required maxLength={80} value={item.label} onChange={event=>updateHeader(index,{label:event.target.value})} /></label><label>Style<select value={item.style ?? 'link'} onChange={event=>updateHeader(index,{style:event.target.value as 'link'|'button'})}><option value="link">Link</option><option value="button">Button</option></select></label><div className={styles.rowActions}><button type="button" aria-label={`Move ${item.label || 'header link'} up`} disabled={index===0} onClick={()=>setNavigation({...navigation,header:move(navigation.header,index,-1)})}>↑</button><button type="button" aria-label={`Move ${item.label || 'header link'} down`} disabled={index===navigation.header.length-1} onClick={()=>setNavigation({...navigation,header:move(navigation.header,index,1)})}>↓</button><button type="button" onClick={()=>setNavigation({...navigation,header:navigation.header.filter((_,i)=>i!==index)})}>Remove</button></div></div>)}
      <button type="button" disabled={navigation.header.length>=6 || !references.pages.length} onClick={()=>setNavigation({...navigation,header:[...navigation.header,{kind:'page',id:references.pages[0]?.id ?? '',label:references.pages[0]?.title ?? '',style:'link'}]})}>Add header link</button>
    </fieldset><fieldset disabled={busy}><legend>Footer</legend>
      {navigation.footer.columns.map((column,columnIndex)=><section className={styles.footerColumn} key={columnIndex}><label>Column title<input required maxLength={80} value={column.heading} onChange={event=>updateColumn(columnIndex,{heading:event.target.value})} /></label>{column.links.map((item,index)=><div className={styles.navEditor} key={`${index}-${item.kind}-${item.id}`}><label>Type<select value={item.kind} onChange={event=>{const kind=event.target.value as Reference['kind']; const links=[...column.links]; links[index]={...item,kind,id:options(kind)[0]?.id ?? ''}; updateColumn(columnIndex,{links})}}><option value="page">Page</option><option value="section">Section</option></select></label><label>Destination<select required value={item.id} onChange={event=>{const links=[...column.links]; links[index]={...item,id:event.target.value}; updateColumn(columnIndex,{links})}}>{options(item.kind).map(option=><option key={option.id} value={option.id}>{option.title}</option>)}</select></label><label>Label<input required maxLength={80} value={item.label} onChange={event=>{const links=[...column.links]; links[index]={...item,label:event.target.value}; updateColumn(columnIndex,{links})}} /></label><div className={styles.rowActions}><button type="button" aria-label={`Move ${item.label || 'footer link'} up`} disabled={index===0} onClick={()=>updateColumn(columnIndex,{links:move(column.links,index,-1)})}>↑</button><button type="button" aria-label={`Move ${item.label || 'footer link'} down`} disabled={index===column.links.length-1} onClick={()=>updateColumn(columnIndex,{links:move(column.links,index,1)})}>↓</button><button type="button" onClick={()=>updateColumn(columnIndex,{links:column.links.filter((_,i)=>i!==index)})}>Remove</button></div></div>)}<div className={styles.rowActions}><button type="button" disabled={column.links.length>=8 || !references.pages.length} onClick={()=>updateColumn(columnIndex,{links:[...column.links,{kind:'page',id:references.pages[0]?.id ?? '',label:references.pages[0]?.title ?? ''}]})}>Add link</button><button type="button" onClick={()=>setNavigation({...navigation,footer:{...navigation.footer,columns:navigation.footer.columns.filter((_,i)=>i!==columnIndex)}})}>Remove column</button></div></section>)}
      <button type="button" disabled={navigation.footer.columns.length>=3} onClick={()=>setNavigation({...navigation,footer:{...navigation.footer,columns:[...navigation.footer.columns,{heading:'Explore',links:[]}]}})}>Add footer column</button><label>Copyright text<input maxLength={160} value={navigation.footer.copyright ?? ''} onChange={event=>{const footer={...navigation.footer}; if(event.target.value) footer.copyright=event.target.value; else delete footer.copyright; setNavigation({...navigation,footer})}} /></label>
    </fieldset><button type="submit" disabled={!canSave}>Save navigation</button></form>
  </section>
}
