import type { Dispatch, FormEvent, SetStateAction } from 'react'
import styles from './site-workspace.module.css'
import { emptyAddress, emptyLogos, type References, type Settings } from './site-types'

type Props = { busy: boolean; canSave: boolean; references: References; settings: Settings; setSettings: Dispatch<SetStateAction<Settings | null>>; onSubmit: (event: FormEvent) => void }

export function SiteDetailsForm({ busy, canSave, references, settings, setSettings, onSubmit }: Props) {
  const address = settings.address ?? emptyAddress
  const logos = settings.logos ?? emptyLogos
  const incident = settings.incident ?? { label: '', guidance: '' }
  const addressLabel = settings.address ? [address.streetAddress, address.addressLocality, address.addressRegion, address.postalCode].filter(Boolean).join(', ') : 'No address set'
  const logoPreview = (id: string | null) => references.assets.find(asset => asset.id === id)?.url
  return <form className={styles.detailsForm} onSubmit={onSubmit} data-site-panel="details" onInvalidCapture={event => { const details = (event.target as HTMLElement).closest('details'); if (details) details.open = true }}>
    <fieldset disabled={busy} className={styles.detailsGrid}><legend className={styles.srOnly}>Business details</legend>
      <section className={styles.card} data-site-details-card="business"><header><h2>Business details</h2></header>
        <label>Business name<input required maxLength={100} value={settings.siteName} onChange={event => setSettings({ ...settings, siteName: event.target.value })} /></label>
        <label>Legal name<input maxLength={160} value={settings.legalName ?? ''} onChange={event => setSettings({ ...settings, legalName: event.target.value || null })} /></label>
        <label>Phone <span>Used everywhere on the site</span><input maxLength={40} value={settings.contactPhone ?? ''} onChange={event => setSettings({ ...settings, contactPhone: event.target.value || null })} /></label><label>Email<input type="email" value={settings.contactEmail ?? ''} onChange={event => setSettings({ ...settings, contactEmail: event.target.value || null })} /></label>
        <details className={styles.addressDisclosure}><summary><strong>Address</strong><span>{addressLabel}</span><small>Edit address</small></summary><fieldset className={styles.address}><legend>Address</legend><label>Street address<input required={Boolean(settings.address)} maxLength={240} value={address.streetAddress} onChange={event => setSettings({ ...settings, address: { ...address, streetAddress: event.target.value } })} /></label><div className={styles.fieldGrid}><label>City<input required={Boolean(settings.address)} maxLength={100} value={address.addressLocality} onChange={event => setSettings({ ...settings, address: { ...address, addressLocality: event.target.value } })} /></label><label>Province or region<input required={Boolean(settings.address)} maxLength={100} value={address.addressRegion} onChange={event => setSettings({ ...settings, address: { ...address, addressRegion: event.target.value } })} /></label><label>Postal code<input required={Boolean(settings.address)} maxLength={24} value={address.postalCode} onChange={event => setSettings({ ...settings, address: { ...address, postalCode: event.target.value } })} /></label><label>Country code<input required={Boolean(settings.address)} pattern="[A-Z]{2}" maxLength={2} value={address.addressCountry} onChange={event => setSettings({ ...settings, address: { ...address, addressCountry: event.target.value.toUpperCase() } })} /></label></div>{settings.address ? <button type="button" onClick={() => setSettings({ ...settings, address: null })}>Clear address</button> : null}</fieldset></details>
        <label>LinkedIn URL<input type="url" placeholder="https://www.linkedin.com/company/example" value={settings.linkedIn ?? ''} onChange={event => setSettings({ ...settings, linkedIn: event.target.value || null })} /></label>
        <details className={styles.additionalSettings}><summary>Additional site settings</summary><label>Short site description<textarea maxLength={160} value={settings.seoDescription ?? ''} onChange={event => setSettings({ ...settings, seoDescription: event.target.value || null })} /></label><small>{(settings.seoDescription ?? '').length}/160 characters</small>
        <div className={styles.fieldGrid}><label>Homepage<select value={settings.homepageId ?? ''} onChange={event => setSettings({ ...settings, homepageId: event.target.value || null })}><option value="">Not selected</option>{references.pages.map(page => <option key={page.id} value={page.id}>{page.title}</option>)}</select></label><label>Default language<select value={settings.defaultLocale} onChange={event => setSettings({ ...settings, defaultLocale: event.target.value as Settings['defaultLocale'] })}><option value="en">English</option><option value="en-CA">English (Canada)</option></select></label><label>Organization type<select value={settings.organizationType ?? ''} onChange={event => setSettings({ ...settings, organizationType: event.target.value as Settings['organizationType'] || null })}><option value="">Not specified</option><option value="organization">Organization</option><option value="professional-service">Professional service</option></select></label></div></details>
      </section>
      <div className={styles.sideCards}><section className={styles.card} data-site-details-card="incident"><header><h2>Incident line</h2></header><label>Bar label<input required={Boolean(settings.incident)} maxLength={80} value={incident.label} onChange={event => setSettings({ ...settings, incident: { ...incident, label: event.target.value } })} /></label><label>Guidance<textarea required={Boolean(settings.incident)} maxLength={1000} value={incident.guidance} onChange={event => setSettings({ ...settings, incident: { ...incident, guidance: event.target.value } })} /></label>{settings.incident ? <button type="button" onClick={() => setSettings({ ...settings, incident: null })}>Clear incident line</button> : null}</section>
        <section className={styles.card} data-site-details-card="logos"><header><h2>Logos</h2></header><div className={styles.logoPreviews}>{([['primaryLight', 'On light backgrounds'], ['primaryDark', 'On dark backgrounds']] as const).map(([field, label]) => <figure key={field} data-site-logo-tone={field === 'primaryLight' ? 'light' : 'dark'}>{logoPreview(logos[field]) ? <img src={logoPreview(logos[field])!} alt={label} /> : <span>Theme default</span>}<figcaption>{label}</figcaption></figure>)}</div><p>Primary, full lockup and symbol, each light and dark. The theme picks the right one for each background.</p><details className={styles.additionalSettings}><summary>Choose logo variants</summary>{([['primaryLight','Primary · light'],['primaryDark','Primary · dark'],['fullLockupLight','Full lockup · light'],['fullLockupDark','Full lockup · dark'],['symbolLight','Symbol · light'],['symbolDark','Symbol · dark']] as const).map(([field,label]) => <label key={field}>{label}<select value={logos[field] ?? ''} onChange={event => setSettings({ ...settings, logos: { ...logos, [field]: event.target.value || null } })}><option value="">Not selected</option>{references.assets.map(asset => <option key={asset.id} value={asset.id}>{asset.label}</option>)}</select></label>)}</details></section></div>
      <div className={styles.formActions}><button type="submit" disabled={!canSave}>Save business details</button><span>Saved changes remain private until review and publication.</span></div>
    </fieldset>
  </form>
}
