'use client'

import { useCallback, useEffect, useState } from 'react'
import styles from './urgent-contacts-settings.module.css'

type Contact = { id?: string; name: string; email: string; mobile: string; enabled: boolean }
const empty = (): Contact => ({ name: '', email: '', mobile: '', enabled: true })

/** Private Owner-only settings panel intended for the Site incident card. */
export function UrgentContactsSettings({ title = 'Urgent alert contacts', formId }: { title?: string; formId?: string }) {
  const [contacts, setContacts] = useState<Contact[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  const load = useCallback(async (signal?: AbortSignal) => { setLoading(true); setError(''); try { const response = await fetch('/api/urgent-contacts', { cache: 'no-store', signal }); const body = await response.json() as { contacts?: Contact[]; error?: string }; if (!response.ok || !body.contacts) throw new Error(body.error ?? 'Urgent contacts could not be loaded.'); if (!signal?.aborted) setContacts(body.contacts) } catch (caught) { if (!signal?.aborted) setError(caught instanceof Error ? caught.message : 'Urgent contacts could not be loaded.') } finally { if (!signal?.aborted) setLoading(false) } }, [])
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort() }, [load])
  const update = (index: number, patch: Partial<Contact>) => setContacts((current) => current.map((contact, item) => item === index ? { ...contact, ...patch } : contact))
  const save = async () => { if (saving) return; setSaving(true); setMessage(''); setError(''); try { const response = await fetch('/api/urgent-contacts', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ contacts }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(response.status === 403 ? 'A fresh Owner sign-in is required before saving urgent contacts.' : body.error ?? 'Urgent contacts could not be saved.'); setMessage('Urgent contacts saved.'); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Urgent contacts could not be saved.') } finally { setSaving(false) } }
  return <section className={styles.settings} data-urgent-contacts aria-busy={loading || saving} aria-labelledby="urgent-contacts-title"><header><div><h3 id="urgent-contacts-title">{title}</h3><p>Choose who should receive urgent incident alerts.</p></div><button type="button" onClick={() => setContacts((current) => [...current, empty()])} disabled={loading || saving || contacts.length >= 20}>Add contact</button></header>
    {(message || error) && <p className={error ? styles.error : styles.status} role={error ? 'alert' : 'status'}>{error || message}</p>}
    {contacts.length ? <div className={styles.list}>{contacts.map((contact, index) => <fieldset key={contact.id ?? `new-${index}`} disabled={loading || saving}><legend className={styles.srOnly}>Urgent contact {index + 1}</legend><label>Name<input form={formId} required maxLength={120} autoComplete="name" value={contact.name} onChange={(event) => update(index, { name: event.target.value })}/></label><label>Email<input form={formId} required type="email" maxLength={254} autoComplete="email" value={contact.email} onChange={(event) => update(index, { email: event.target.value })}/></label><label>Mobile number<input form={formId} type="tel" maxLength={32} autoComplete="tel" placeholder="Optional" value={contact.mobile} onChange={(event) => update(index, { mobile: event.target.value })}/></label><label className={styles.enabled}><input form={formId} type="checkbox" checked={contact.enabled} onChange={(event) => update(index, { enabled: event.target.checked })}/>Active</label><button className={styles.remove} type="button" onClick={() => setContacts((current) => current.filter((_, item) => item !== index))}>Remove <span className={styles.srOnly}>{contact.name || `contact ${index + 1}`}</span></button></fieldset>)}</div> : !loading && <p className={styles.empty}>No urgent contacts are configured.</p>}
    <footer><button type="button" onClick={() => void save()} disabled={loading || saving}>{saving ? 'Saving…' : 'Save urgent contacts'}</button><small>These contacts are private and do not appear on your website.</small></footer>
  </section>
}
