import { getPayload } from 'payload'
import config from '../../../../payload.config'
import { hasRole } from '../../../../src/access'
import { serverSessionStrategy } from '../../../../src/identity'
import { mediaFocalContractVersion, mediaWorkspace } from '../../../../src/media-workspace'
import { canonicalFocalPoint } from '../../../../src/media'
import { loadInitialPreviewBaseline } from '../../../../src/review-preview'
export const dynamic = 'force-dynamic'
const maxBodyBytes = 8_192
const json = (body: unknown, status = 200) => Response.json(body, { status, headers: { 'Cache-Control': 'no-store' } })
const sameOrigin = (request: Request) => { const configured = process.env.PAYLOAD_PUBLIC_SERVER_URL; const origin = request.headers.get('origin'); return Boolean(configured && origin === new URL(configured).origin) }
async function actor(request: Request) { const payload = await getPayload({ config }); const user = (await serverSessionStrategy.authenticate({ headers: request.headers, payload })).user; if (!hasRole(user as never, ['owner', 'editor'])) return null; return { payload, user } }
async function body(request: Request): Promise<Record<string, unknown>> { const reader = request.body?.getReader(); if (!reader) throw new Error('INVALID'); const chunks: Uint8Array[] = []; let size = 0; while (true) { const chunk = await reader.read(); if (chunk.done) break; size += chunk.value.byteLength; if (size > maxBodyBytes) { await reader.cancel(); throw new Error('TOO_LARGE') }; chunks.push(chunk.value) }; const bytes = new Uint8Array(size); let offset = 0; for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength }; const parsed: unknown = JSON.parse(new TextDecoder().decode(bytes)); if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error('INVALID'); return parsed as Record<string, unknown> }
export async function GET(request: Request) { const access = await actor(request); if (!access) return json({ error: 'Media workspace access required.' }, 403); try { const url = new URL(request.url); const initialBaseline = await loadInitialPreviewBaseline(); return json({ ...await mediaWorkspace(access.payload, access.user as never, { q: url.searchParams.get('q') ?? undefined, filter: url.searchParams.get('filter') ?? undefined, page: Number(url.searchParams.get('page') ?? 1), pageSize: Number(url.searchParams.get('pageSize') ?? 24) }), focalEditingAvailable: Boolean(await mediaFocalContractVersion(access.payload, initialBaseline)) }) } catch { return json({ error: 'Media workspace is unavailable.' }, 400) } }
export async function PATCH(request: Request) { if (!sameOrigin(request)) return json({ error: 'CSRF origin check failed.' }, 403); const access = await actor(request); if (!access) return json({ error: 'Media workspace access required.' }, 403); try { const input = await body(request); if (Object.keys(input).some((key) => !['id', 'alt', 'decorative', 'caption', 'credit', 'tags', 'focalX', 'focalY'].includes(key))) return json({ error: 'Unexpected media metadata field.' }, 400); if (typeof input.id !== 'string' || typeof input.alt !== 'string' || typeof input.decorative !== 'boolean' || (input.caption !== undefined && typeof input.caption !== 'string') || (input.credit !== undefined && typeof input.credit !== 'string') || (input.tags !== undefined && (!Array.isArray(input.tags) || input.tags.some((tag) => typeof tag !== 'string'))) || typeof input.focalX !== 'number' || !Number.isFinite(input.focalX) || input.focalX < 0 || input.focalX > 100 || typeof input.focalY !== 'number' || !Number.isFinite(input.focalY) || input.focalY < 0 || input.focalY > 100) return json({ error: 'Invalid media metadata.' }, 400); const focalX = canonicalFocalPoint(input.focalX); const focalY = canonicalFocalPoint(input.focalY); const [current, focalContract] = await Promise.all([access.payload.findByID({ collection: 'assets', id: input.id, depth: 0, overrideAccess: false, user: access.user }), loadInitialPreviewBaseline().then((baseline) => mediaFocalContractVersion(access.payload, baseline))]); if (!focalContract && (focalX !== canonicalFocalPoint(current.focalX) || focalY !== canonicalFocalPoint(current.focalY))) return json({ error: 'Focal-point editing requires an active contract 1.4 theme.' }, 409); const asset = await access.payload.update({ collection: 'assets', id: input.id, data: { alt: input.alt, decorative: input.decorative, caption: input.caption as string | undefined, credit: input.credit as string | undefined, tags: input.tags as string[] | undefined, ...(focalContract ? { focalX, focalY } : {}) }, overrideAccess: false, user: access.user, context: { mediaFocalContract: focalContract } }); return json({ asset: { id: asset.id, alt: asset.alt ?? '', decorative: asset.decorative === true, caption: asset.caption ?? '', credit: asset.credit ?? '', tags: asset.tags ?? [], focalX: canonicalFocalPoint(asset.focalX), focalY: canonicalFocalPoint(asset.focalY) } }) } catch (error) { return json({ error: error instanceof Error && error.message === 'TOO_LARGE' ? 'Request is too large.' : 'Invalid media metadata.' }, error instanceof Error && error.message === 'TOO_LARGE' ? 413 : 400) } }
