import { getPayload } from 'payload'
import config from '../../../../payload.config'
import { hasRole } from '../../../../src/access'
import { serverSessionStrategy } from '../../../../src/identity'
import { mediaWorkspace } from '../../../../src/media-workspace'
export const dynamic = 'force-dynamic'
const sameOrigin = (request: Request) => { const configured = process.env.PAYLOAD_PUBLIC_SERVER_URL; const origin = request.headers.get('origin'); return Boolean(configured && origin === new URL(configured).origin) }
async function actor(request: Request) { const payload = await getPayload({ config }); const user = (await serverSessionStrategy.authenticate({ headers: request.headers, payload })).user; if (!hasRole(user as never, ['owner', 'editor'])) throw new Response(JSON.stringify({ error: 'Media workspace access required.' }), { status: 403 }); return { payload, user } }
export async function GET(request: Request) { try { const { payload, user } = await actor(request); const url = new URL(request.url); return Response.json(await mediaWorkspace(payload, user as never, { q: url.searchParams.get('q') ?? undefined, filter: url.searchParams.get('filter') ?? undefined }), { headers: { 'Cache-Control': 'no-store' } }) } catch (error) { return error instanceof Response ? error : Response.json({ error: error instanceof Error ? error.message : 'Unable to load media.' }, { status: 400 }) } }
export async function PATCH(request: Request) { if (!sameOrigin(request)) return Response.json({ error: 'CSRF origin check failed.' }, { status: 403 }); try { const raw = await request.text(); if (raw.length > 8_192) return Response.json({ error: 'Request is too large.' }, { status: 413 }); const body = JSON.parse(raw) as { id?: unknown; alt?: unknown; decorative?: unknown; caption?: unknown; credit?: unknown; tags?: unknown }; if (typeof body.id !== 'string' || typeof body.alt !== 'string' || typeof body.decorative !== 'boolean') return Response.json({ error: 'Asset id, alt text, and decorative state are required.' }, { status: 400 }); if ([body.alt, body.caption, body.credit].some((value) => value !== undefined && typeof value !== 'string') || (body.tags !== undefined && (!Array.isArray(body.tags) || body.tags.some((tag) => typeof tag !== 'string')))) return Response.json({ error: 'Invalid media metadata.' }, { status: 400 }); const { payload, user } = await actor(request); const asset = await payload.update({ collection: 'assets', id: body.id, data: { alt: body.alt, decorative: body.decorative, caption: body.caption as string | undefined, credit: body.credit as string | undefined, tags: body.tags as string[] | undefined }, overrideAccess: false, user }); const saved = asset as unknown as { id: string; alt?: string; decorative?: boolean; caption?: string; credit?: string; tags?: string[] }; return Response.json({ asset: saved }) } catch (error) { return error instanceof Response ? error : Response.json({ error: error instanceof Error ? error.message : 'Unable to save media metadata.' }, { status: 400 }) } }
