import { isIP } from 'node:net'
import type { IntegrationProvider } from './integrations'
import { normalizeProviderSettings, type ProviderSettings } from './provider-settings'
export type AdapterRequest = { url: string; headers: Record<string, string>; body: Record<string, unknown> }
const chat = (model: string, input: string, max: number, image?: string) => ({ model, max_tokens: max, messages: [{ role: 'user', content: image ? [{ type: 'text', text: input }, { type: 'image_url', image_url: { url: image } }] : input }] })
const responses = (model: string, input: string, max: number, image?: string) => ({ model, max_output_tokens: max, input: [{ role: 'user', content: [{ type: 'input_text', text: input }, ...(image ? [{ type: 'input_image', image_url: image }] : [])] }] })
function compatible(settings: ProviderSettings): string | undefined { const endpoint = settings.endpoint; if (!endpoint || !(process.env.AI_COMPATIBLE_ALLOWED_ORIGINS ?? '').split(',').map(x => x.trim()).includes(endpoint)) return; const url = new URL(endpoint); return isIP(url.hostname) || url.hostname.endsWith('.local') || url.hostname.endsWith('.internal') ? undefined : endpoint }
export function adapterRequest(provider: IntegrationProvider, credential: string, model: string, input: string, max: number, image: string | undefined, raw: ProviderSettings | undefined): AdapterRequest | undefined {
  let settings: ProviderSettings; try { settings = normalizeProviderSettings(provider, raw) } catch { return }
  if (provider === 'azure-openai') return { url: `${settings.endpoint}/responses`, headers: { 'api-key': credential, 'content-type': 'application/json' }, body: responses(model, input, max, image) }
  if (provider === 'amazon-bedrock') return { url: `https://bedrock-runtime.${settings.region}.amazonaws.com/model/${encodeURIComponent(model)}/converse`, headers: { authorization: `Bearer ${credential}`, 'content-type': 'application/json' }, body: { messages: [{ role: 'user', content: [{ text: input }] }], inferenceConfig: { maxTokens: max } } }
  if (provider === 'mistral') return { url: 'https://api.mistral.ai/v1/chat/completions', headers: { authorization: `Bearer ${credential}`, 'content-type': 'application/json' }, body: chat(model, input, max, image) }
  if (provider === 'openai-compatible') { const origin = compatible(settings); return origin ? { url: `${origin}/v1/chat/completions`, headers: { authorization: `Bearer ${credential}`, 'content-type': 'application/json' }, body: chat(model, input, max, image) } : undefined }
}
export function adapterMetadataURL(provider: IntegrationProvider, model: string, raw: ProviderSettings | undefined): string | undefined { let s: ProviderSettings; try { s = normalizeProviderSettings(provider, raw) } catch { return }; if (provider === 'azure-openai') return `${s.endpoint}/models/${encodeURIComponent(model)}`; if (provider === 'amazon-bedrock') return `https://bedrock.${s.region}.amazonaws.com/foundation-models/${encodeURIComponent(model)}`; if (provider === 'mistral') return `https://api.mistral.ai/v1/models/${encodeURIComponent(model)}`; if (provider === 'openai-compatible') { const origin = compatible(s); return origin && `${origin}/v1/models/${encodeURIComponent(model)}` } }
export function adapterOutput(provider: IntegrationProvider, body: Record<string, unknown>): { output: string; inputTokens?: unknown; outputTokens?: unknown } | undefined { if (provider === 'azure-openai') { const output = Array.isArray(body.output) ? body.output.flatMap(item => Array.isArray((item as Record<string, unknown>).content) ? (item as Record<string, unknown>).content as Array<Record<string, unknown>> : []).map(item => typeof item.text === 'string' && item.type === 'output_text' ? item.text : '').join('') : ''; const usage = body.usage as Record<string, unknown> | undefined; return output ? { output, inputTokens: usage?.input_tokens, outputTokens: usage?.output_tokens } : undefined }; if (provider === 'amazon-bedrock') { const output = ((body.output as Record<string, unknown> | undefined)?.message as Record<string, unknown> | undefined)?.content; const text = Array.isArray(output) ? output.map(x => typeof (x as Record<string, unknown>).text === 'string' ? (x as Record<string, unknown>).text : '').join('') : ''; const usage = body.usage as Record<string, unknown> | undefined; return text ? { output: text, inputTokens: usage?.inputTokens, outputTokens: usage?.outputTokens } : undefined }; if (provider === 'mistral' || provider === 'openai-compatible') { const choice = Array.isArray(body.choices) ? body.choices[0] as Record<string, unknown> | undefined : undefined; const text = (choice?.message as Record<string, unknown> | undefined)?.content; const usage = body.usage as Record<string, unknown> | undefined; return typeof text === 'string' && text ? { output: text, inputTokens: usage?.prompt_tokens, outputTokens: usage?.completion_tokens } : undefined } }
