/** Provider contracts: Graph sendMail returns 202 (accepted, not delivery); Gmail sends RFC822 base64url. Sources: https://learn.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0 and https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.messages/send */
export type Fetcher = (url: string, init: RequestInit) => Promise<Response>
export type Envelope = { sender: string; recipient: string; subject: string; body: string; threadID?: string }
const clean = (value: unknown) => String(value ?? '').replace(/<[^>]*>/g, ' ').replace(/[\u0000-\u001f]/g, ' ').replace(/\s+/g, ' ').trim().slice(0, 20_000)
const auth = (token: string) => ({ authorization: `Bearer ${token}`, 'content-type': 'application/json' })
const fail = (status: number) => { if (status === 401) throw new Error('provider_unauthorized'); if (status === 403) throw new Error('provider_forbidden'); throw new Error('provider_unavailable') }
function valid(e: Envelope) { for (const x of [e.sender,e.recipient,e.subject]) if (!x || /[\r\n\u0000]/.test(x)) throw new Error('invalid_envelope') }
async function json(r: Response) { const text = await r.text(); if (text.length > 262_144) throw new Error('provider_response_too_large'); try { return JSON.parse(text) as Record<string, unknown> } catch { throw new Error('provider_malformed_response') } }
function request(fetcher: Fetcher, url: string, init: RequestInit) { return fetcher(url, { ...init, redirect: 'error', signal: AbortSignal.timeout(10_000) }) }
export function microsoftAdapter(fetcher: Fetcher, verifiedSender?: string) { return { async send(token: string, envelope: Envelope) { valid(envelope); if (verifiedSender && envelope.sender.toLowerCase() !== verifiedSender.toLowerCase()) throw new Error('sender_not_verified'); const r = await request(fetcher, 'https://graph.microsoft.com/v1.0/me/sendMail', { method: 'POST', headers: auth(token), body: JSON.stringify({ message: { subject: envelope.subject, body: { contentType: 'Text', content: envelope.body }, toRecipients: [{ emailAddress: { address: envelope.recipient } }], ...(verifiedSender ? { from: { emailAddress: { address: verifiedSender } } } : {}) } }) }); if (r.status !== 202) fail(r.status); return { accepted: true as const } }, async thread(token: string, id: string) { const r = await request(fetcher, `https://graph.microsoft.com/v1.0/me/messages/${encodeURIComponent(id)}?$select=id,conversationId,body,subject`, { headers: auth(token) }); if (!r.ok) fail(r.status); const x = await json(r); return { id: String(x.id), threadID: String(x.conversationId), subject: clean(x.subject), body: clean((x.body as { content?: unknown })?.content) } }, async poll(token:string, cursor?:string) { if(cursor && !/^[A-Za-z0-9._~-]{1,500}$/.test(cursor)) throw new Error('invalid_cursor'); const r=await request(fetcher,`https://graph.microsoft.com/v1.0/me/messages?$select=id,conversationId,subject,body,from,toRecipients,receivedDateTime${cursor?`&$skiptoken=${encodeURIComponent(cursor)}`:''}`,{headers:auth(token)});if(!r.ok)fail(r.status);const x=await json(r);const values=Array.isArray(x.value)?x.value.slice(0,500):[];return {cursor:typeof x['@odata.nextLink']==='string'?new URL(String(x['@odata.nextLink'])).searchParams.get('$skiptoken')??null:null,messages:values.map((m:any)=>({messageId:String(m.id??''),threadId:String(m.conversationId??''),subject:clean(m.subject),body:clean(m.body?.content),date:String(m.receivedDateTime??''),sender:String(m.from?.emailAddress?.address??''),recipient:String(m.toRecipients?.[0]?.emailAddress?.address??'')})).filter(m=>m.messageId&&m.threadId)} } } }
export function microsoftIdentity(fetcher: Fetcher) { return async (token: string) => { const r = await request(fetcher, 'https://graph.microsoft.com/v1.0/me?$select=mail,userPrincipalName,proxyAddresses', { headers: auth(token) }); if (!r.ok) fail(r.status); const x = await json(r); const primary = String(x.mail || x.userPrincipalName || '').trim().toLowerCase(); if (!primary.includes('@')) throw new Error('provider_identity_missing'); const aliases = Array.isArray(x.proxyAddresses) ? x.proxyAddresses.filter((v): v is string => typeof v === 'string' && /^smtp:/i.test(v)).map(v => v.slice(5).toLowerCase()) : []; return { primaryAddress: primary, verifiedSenders: [...new Set([primary, ...aliases])].sort() } } }
export function gmailAdapter(fetcher: Fetcher) { return { async send(token: string, envelope: Envelope) { valid(envelope); const raw = Buffer.from(`To: ${envelope.recipient}\r\nFrom: ${envelope.sender}\r\nSubject: ${envelope.subject}\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=UTF-8\r\n\r\n${envelope.body}`).toString('base64url'); const r = await request(fetcher, 'https://gmail.googleapis.com/gmail/v1/users/me/messages/send', { method: 'POST', headers: auth(token), body: JSON.stringify({ raw, ...(envelope.threadID ? { threadId: envelope.threadID } : {}) }) }); if (!r.ok) fail(r.status); const x = await json(r); return { accepted: true as const, id: String(x.id ?? ''), threadID: String(x.threadId ?? '') } }, async poll(token: string, historyID: string) { const r = await request(fetcher, `https://gmail.googleapis.com/gmail/v1/users/me/history?startHistoryId=${encodeURIComponent(historyID)}`, { headers: auth(token) }); if (!r.ok) fail(r.status); const x = await json(r); const entries = Array.isArray(x.history) ? x.history.slice(0, 500) : []; return { historyID: String(x.historyId ?? historyID), entries } } } }
export function gmailIdentity(fetcher: Fetcher) { return async (token: string) => { const [profile, aliases] = await Promise.all(['https://gmail.googleapis.com/gmail/v1/users/me/profile','https://gmail.googleapis.com/gmail/v1/users/me/settings/sendAs'].map(async url => { const r = await request(fetcher,url,{headers:auth(token)}); if(!r.ok) fail(r.status); return json(r) })); const primary=String(profile.emailAddress??'').toLowerCase(); if(!primary.includes('@')) throw new Error('provider_identity_missing'); const verified=Array.isArray(aliases.sendAs)?aliases.sendAs.filter((x):x is Record<string,unknown>=>!!x&&typeof x==='object'&&x.verificationStatus==='accepted').map(x=>String(x.sendAsEmail).toLowerCase()).filter(x=>x.includes('@')):[]; return {primaryAddress:primary,verifiedSenders:[...new Set([primary,...verified])].sort()} } }
