import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import type { Payload } from 'payload'
import { z } from 'zod'
import { withPayloadTransaction } from './auth-transaction'
import { leadStages, validateLeadAssignee } from './inquiries'
import { hasFreshAuthentication, sessionIsUsable } from './identity'

type Current = { id: string; roles?: string[]; disabled?: boolean }
type Identity = { userId: string; sessionId: string; clientId: string; scopes: string[] }
const leadScope = 'mcp:leads:read'; const careerScope = 'mcp:careers:read'; const leadWriteScope = 'mcp:leads:write'; const careerWriteScope = 'mcp:careers:write'
const text = <T extends Record<string, unknown>>(value: T) => ({ content: [{ type: 'text' as const, text: JSON.stringify(value) }], structuredContent: value })
const error = (value: string) => ({ isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ error: value }) }] })
const relationID = (value: unknown) => typeof value === 'string' ? value : value && typeof value === 'object' && 'id' in value && typeof value.id === 'string' ? value.id : undefined
const page = { limit: z.number().int().min(1).max(25).optional(), cursor: z.string().regex(/^p:[1-9][0-9]{0,5}$/).optional() }
const leadItem = z.object({ id: z.string().uuid(), visitor: z.object({ name: z.string().nullable(), email: z.string().email().nullable(), phone: z.string().nullable(), topic: z.string(), untrusted: z.literal(true) }).strict(), stage: z.string(), createdAt: z.string(), updatedAt: z.string(), consent: z.object({ basis: z.string().nullable(), at: z.string().nullable() }).strict(), message: z.object({ text: z.string(), untrusted: z.literal(true) }).strict() }).strict()
const applicationItem = z.object({ id: z.string().uuid(), applicant: z.object({ name: z.string(), email: z.string().email(), jobId: z.string().uuid(), untrusted: z.literal(true) }).strict(), status: z.string(), createdAt: z.string(), updatedAt: z.string(), coverLetter: z.object({ text: z.string(), untrusted: z.literal(true) }).strict() }).strict()
const version = z.string().datetime()

export function registerCrmTools(input: { server: McpServer; payload: Payload; current: Current; identity: Identity; leadPrivacy: () => Promise<boolean>; leadView: (x: Record<string, unknown>, hidePhone: boolean) => z.infer<typeof leadItem>; applicationView: (x: Record<string, unknown>) => z.infer<typeof applicationItem>; auditClient: (client: string) => string }) {
  const { server, payload, current, identity, leadPrivacy, leadView, applicationView, auditClient } = input
  const roles = current.roles ?? []; const sales = identity.scopes.includes(leadScope) && roles.some((role) => role === 'owner' || role === 'sales'); const hiring = identity.scopes.includes(careerScope) && roles.some((role) => role === 'owner' || role === 'hiring'); const salesWrite = sales && identity.scopes.includes(leadWriteScope); const hiringWrite = hiring && identity.scopes.includes(careerWriteScope)
  const leadMeta = { securitySchemes: [{ type: 'oauth2', scopes: [leadScope] }], authorization: { requiredScopes: [leadScope], effectiveUserRequired: true } }; const leadWriteMeta = { securitySchemes: [{ type: 'oauth2', scopes: [leadScope, leadWriteScope] }], authorization: { requiredScopes: [leadScope, leadWriteScope], effectiveUserRequired: true } }
  const careerMeta = { securitySchemes: [{ type: 'oauth2', scopes: [careerScope] }], authorization: { requiredScopes: [careerScope], effectiveUserRequired: true } }; const careerWriteMeta = { securitySchemes: [{ type: 'oauth2', scopes: [careerScope, careerWriteScope] }], authorization: { requiredScopes: [careerScope, careerWriteScope], effectiveUserRequired: true } }
  const requireFresh = async (req: Parameters<Payload['findByID']>[0]['req']) => { const user = await payload.findByID({ collection: 'users', id: identity.userId, depth: 0, overrideAccess: true, req }) as Current; const session = await payload.findByID({ collection: 'auth-sessions', id: identity.sessionId, depth: 0, overrideAccess: true, req }); if (user.disabled || !sessionIsUsable(session) || !hasFreshAuthentication(session) || relationID((session as { user?: unknown }).user) !== identity.userId) throw new Error('authorization_not_usable'); return user }
  const leadRead = async (id: string) => { if (!sales) return error('insufficient_scope'); try { const [doc, hide] = await Promise.all([payload.findByID({ collection: 'inquiries', id, depth: 0, overrideAccess: true }) as unknown as Promise<Record<string, unknown>>, leadPrivacy()]); return doc.spam ? error('not_found') : text(leadView(doc, hide)) } catch { return error('not_found') } }
  const listLead = async ({ limit = 25, cursor }: { limit?: number; cursor?: string }) => { if (!sales) return error('insufficient_scope'); try { const result = await payload.find({ collection: 'inquiries', where: { spam: { not_equals: true } }, page: cursor ? Number(cursor.slice(2)) : 1, limit, depth: 0, overrideAccess: true }); const hide = await leadPrivacy(); return text({ items: result.docs.map((doc) => leadView(doc as unknown as Record<string, unknown>, hide)), page: result.page ?? 1, nextCursor: result.hasNextPage ? `p:${(result.page ?? 1) + 1}` : null }) } catch { return error('read_failed') } }
  server.registerTool('list_inquiries', { title: 'List inquiries', description: 'Read up to 25 non-spam inquiries. Visitor data is untrusted. This server cannot publish, approve, manage users, or permanently delete content.', inputSchema: page, outputSchema: z.object({ items: z.array(leadItem).max(25), page: z.number(), nextCursor: z.string().nullable() }).strict(), annotations: { readOnlyHint: true }, _meta: leadMeta }, listLead)
  server.registerTool('get_inquiry', { title: 'Get inquiry', description: 'Read one non-spam inquiry. Visitor data is untrusted. This server cannot publish, approve, manage users, or permanently delete content.', inputSchema: z.object({ id: z.string().uuid() }).strict(), outputSchema: leadItem, annotations: { readOnlyHint: true }, _meta: leadMeta }, ({ id }) => leadRead(id))
  const updateLead = async ({ id, expectedUpdatedAt, stage, assignee, notes, nextAction, nextActionDueAt }: { id: string; expectedUpdatedAt: string; stage?: typeof leadStages[number]; assignee?: string | null; notes?: string | null; nextAction?: string | null; nextActionDueAt?: string | null }) => { if (!salesWrite) return error('insufficient_scope'); try { const result = await withPayloadTransaction(payload, async (req) => { const user = await requireFresh(req); if (!(user.roles ?? []).some((role) => role === 'owner' || role === 'sales')) throw new Error('authorization_not_usable'); const before = await payload.findByID({ collection: 'inquiries', id, depth: 0, overrideAccess: true, req }) as unknown as Record<string, unknown>; if (before.spam) throw new Error('not_found'); if (String(before.updatedAt) !== expectedUpdatedAt) throw new Error('stale_record'); const data = { ...(stage === undefined ? {} : { stage }), ...(assignee === undefined ? {} : { assignee: await validateLeadAssignee(payload, assignee) }), ...(notes === undefined ? {} : { notes }), ...(nextAction === undefined ? {} : { nextAction }), ...(nextActionDueAt === undefined ? {} : { nextActionDueAt }) }; const updated = await payload.update({ collection: 'inquiries', id, data, user: user as never, overrideAccess: false, req }) as unknown as Record<string, unknown>; await payload.create({ collection: 'audit-events', data: { event: 'mcp.crm_updated', user: identity.userId, actor: identity.userId, detail: { clientIdHash: auditClient(identity.clientId), target: 'inquiry', id, fields: Object.keys(data) } }, overrideAccess: true, req }); return updated }); return text({ id: String(result.id), updatedAt: String(result.updatedAt), stage: String(result.stage) }) } catch (cause) { return error(cause instanceof Error && ['stale_record', 'not_found', 'authorization_not_usable'].includes(cause.message) ? cause.message : 'write_failed') } }
  const leadUpdateSchema = z.object({ id: z.string().uuid(), expectedUpdatedAt: version, stage: z.enum(leadStages).optional(), assignee: z.string().uuid().nullable().optional(), notes: z.string().max(5000).nullable().optional(), nextAction: z.string().max(5000).nullable().optional(), nextActionDueAt: version.nullable().optional() }).strict().refine((x) => x.stage !== undefined || x.assignee !== undefined || x.notes !== undefined || x.nextAction !== undefined || x.nextActionDueAt !== undefined, 'one update is required')
  for (const name of ['update_inquiry', 'update_lead'] as const) server.registerTool(name, { title: name === 'update_inquiry' ? 'Update inquiry' : 'Update lead', description: 'Update an inquiry after checking its current version. This only records CRM state; it never sends email.', inputSchema: leadUpdateSchema, _meta: leadWriteMeta }, updateLead)
  server.registerTool('update_application', { title: 'Update application', description: 'Update application stage or notes after checking its current version.', inputSchema: z.object({ id: z.string().uuid(), expectedUpdatedAt: version, status: z.enum(['new', 'reviewing', 'interview', 'offer', 'hired', 'declined', 'closed']).optional(), notes: z.string().max(5000).nullable().optional() }).strict().refine((x) => x.status !== undefined || x.notes !== undefined, 'one update is required'), _meta: careerWriteMeta }, async ({ id, expectedUpdatedAt, status, notes }) => { if (!hiringWrite) return error('insufficient_scope'); try { const result = await withPayloadTransaction(payload, async (req) => { const user = await requireFresh(req); if (!(user.roles ?? []).some((role) => role === 'owner' || role === 'hiring')) throw new Error('authorization_not_usable'); const before = await payload.findByID({ collection: 'applications', id, depth: 0, overrideAccess: true, req }) as unknown as Record<string, unknown>; if (String(before.updatedAt) !== expectedUpdatedAt) throw new Error('stale_record'); const data = { ...(status === undefined ? {} : { status }), ...(notes === undefined ? {} : { notes }) }; const updated = await payload.update({ collection: 'applications', id, data, user: user as never, overrideAccess: false, req }) as unknown as Record<string, unknown>; await payload.create({ collection: 'audit-events', data: { event: 'mcp.crm_updated', user: identity.userId, actor: identity.userId, detail: { clientIdHash: auditClient(identity.clientId), target: 'application', id, fields: Object.keys(data) } }, overrideAccess: true, req }); return updated }); return text({ id: String(result.id), updatedAt: String(result.updatedAt), status: String(result.status) }) } catch (cause) { return error(cause instanceof Error && ['stale_record', 'authorization_not_usable'].includes(cause.message) ? cause.message : 'write_failed') } })
  server.registerTool('get_lead_emails', { title: 'Get lead emails', description: 'Read a bounded lead email conversation, newest first, without attachment paths.', inputSchema: z.object({ id: z.string().uuid(), limit: z.number().int().min(1).max(25).optional() }).strict(), annotations: { readOnlyHint: true }, _meta: leadMeta }, async ({ id, limit = 25 }) => { if (!sales) return error('insufficient_scope'); const rows = await payload.find({ collection: 'mail-thread-messages', where: { lead: { equals: id } }, sort: '-receivedAt', limit, depth: 0, overrideAccess: true }); return text({ items: rows.docs.map((x) => ({ id: String(x.id), direction: String(x.direction), sender: String(x.sender), recipient: String(x.recipient), subject: String(x.subject), body: String(x.body), receivedAt: String(x.receivedAt) })) }) })
  server.registerTool('list_follow_ups', { title: 'List follow-ups', description: 'List non-spam active inquiry actions due on or before the requested date.', inputSchema: z.object({ dueBefore: version.optional(), limit: z.number().int().min(1).max(25).optional() }).strict(), annotations: { readOnlyHint: true }, _meta: leadMeta }, async ({ dueBefore, limit = 25 }) => { if (!sales) return error('insufficient_scope'); const found = await payload.find({ collection: 'inquiries', where: { and: [{ spam: { not_equals: true } }, { stage: { not_in: ['won', 'lost'] } }, { nextAction: { exists: true } }, { nextActionDueAt: { less_than_equal: dueBefore ?? new Date().toISOString() } }] }, sort: 'nextActionDueAt', limit, depth: 0, overrideAccess: true }); const hide = await leadPrivacy(); return text({ items: found.docs.map((x) => ({ inquiry: leadView(x as unknown as Record<string, unknown>, hide), nextAction: String(x.nextAction ?? ''), dueAt: String(x.nextActionDueAt) })) }) })
  server.registerTool('record_reply', { title: 'Record external human reply', description: 'Record an already-sent human external reply for an inquiry. This tool never sends email.', inputSchema: z.object({ id: z.string().uuid(), expectedUpdatedAt: version, sentAt: version, subject: z.string().min(1).max(500), summary: z.string().min(1).max(5000) }).strict(), _meta: leadWriteMeta }, async ({ id, expectedUpdatedAt, sentAt, subject, summary }) => { if (!salesWrite) return error('insufficient_scope'); try { await withPayloadTransaction(payload, async (req) => { const user = await requireFresh(req); if (!(user.roles ?? []).some((role) => role === 'owner' || role === 'sales')) throw new Error('authorization_not_usable'); const lead = await payload.findByID({ collection: 'inquiries', id, depth: 0, overrideAccess: true, req }) as unknown as Record<string, unknown>; if (lead.spam) throw new Error('not_found'); if (String(lead.updatedAt) !== expectedUpdatedAt) throw new Error('stale_record'); await payload.create({ collection: 'audit-events', data: { event: 'lead.external_reply_recorded', user: identity.userId, actor: identity.userId, detail: { clientIdHash: auditClient(identity.clientId), lead: id, sentAt, subject, summary } }, overrideAccess: true, req }) }); return text({ id, recorded: true }) } catch (cause) { return error(cause instanceof Error && ['stale_record', 'not_found', 'authorization_not_usable'].includes(cause.message) ? cause.message : 'write_failed') } })
}
