'use client'
import { useEffect, useState } from 'react'

type Data = { policy: { spamDays: number; mediaBinDays: number; retainedInquiries: string; applicationsAndResumes: string }; backupNotice: string; failedJobs: Array<{ id: string; resourceType: string; resourceID: string; attempts: number; lastError?: string }> }
export function RetentionWorkspace() {
  const [data, setData] = useState<Data>(); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const load = async () => { const response = await fetch('/api/retention', { cache: 'no-store' }); if (!response.ok) throw new Error('Owner access is required to view retention.'); setData(await response.json() as Data) }
  useEffect(() => { void load().catch(cause => setError(cause instanceof Error ? cause.message : 'Unable to load retention.')) }, [])
  const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); setError(''); try { const response = await fetch('/api/retention', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ spamDays: Number(form.get('spamDays')), mediaBinDays: Number(form.get('mediaBinDays')) }) }); const value = await response.json(); if (!response.ok) throw new Error(value.error); setData(current => current ? { ...current, policy: value.policy } : current) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save retention.') } finally { setSaving(false) } }
  return <main style={{ maxWidth: 860, padding: 28 }}><h1>Retention and deletion</h1>{error && <p role="alert">{error}</p>}{data && <><p>Spam is removed after {data.policy.spamDays} days. Unused media remains in the deletion bin for {data.policy.mediaBinDays} days. Retained inquiries and applications/resumes require an Owner’s manual permanent deletion.</p><p>{data.backupNotice}</p><form onSubmit={save}><label>Spam cleanup days <input name="spamDays" type="number" min="1" max="365" defaultValue={data.policy.spamDays} required /></label><br /><label>Media bin days <input name="mediaBinDays" type="number" min="1" max="365" defaultValue={data.policy.mediaBinDays} required /></label><br /><button disabled={saving}>{saving ? 'Saving…' : 'Save policy'}</button></form><h2>Failed purge jobs</h2>{data.failedJobs.length ? <ul>{data.failedJobs.map(job => <li key={job.id}>{job.resourceType} {job.resourceID}: {job.lastError ?? 'Retry pending'} (attempt {job.attempts})</li>)}</ul> : <p>No failed purge jobs.</p>}</>}</main>
}
