import { expect, test, type Browser } from '@playwright/test'
import { createRequire } from 'node:module'
const axeSource = createRequire(import.meta.url).resolve('axe-core/axe.min.js')
const origin = `https://127.0.0.1:${Number(process.env.CMS_E2E_PORT ?? 4300)}`
async function pageFor(browser: Browser, role: 'owner' | 'editor' | 'sales') { const context = await browser.newContext({ baseURL: origin, ignoreHTTPSErrors: true }); const token = role === 'owner' ? 'synthetic-operations-owner-session-token' : `synthetic-application-${role}-session-token`; await context.addCookies(['site_engine_session', '__Host-site_engine_session'].map(name => ({ name, value: token, url: origin, secure: true, httpOnly: true, sameSite: 'Lax' as const }))); return { context, page: await context.newPage() } }
async function openMenu(page: Awaited<ReturnType<typeof pageFor>>['page']) { const button = page.locator('button.nav-toggler:visible'); if (await button.getAttribute('aria-label') === 'Open Menu') { await button.click(); await expect(button).toHaveAttribute('aria-label', 'Close Menu') } }
test('ENG-006 exposes an accessible editor content tree through the native navigation', async ({ browser }) => {
  for (const role of ['owner', 'editor'] as const) { const session = await pageFor(browser, role); await session.page.goto('/admin'); await openMenu(session.page); const link = session.page.getByRole('link', { name: 'Content tree' }); await link.click(); await expect(session.page).toHaveURL(/\/content-tree$/); await expect(session.page.getByRole('heading', { name: 'Content tree' })).toBeVisible(); await session.page.locator('a[href="/admin"]').focus(); await expect(session.page.locator('a[href="/admin"]')).toBeFocused(); await session.page.addScriptTag({ path: axeSource }); expect(await session.page.evaluate(async () => (await (window as unknown as { axe: typeof import('axe-core') }).axe.run('main')).violations)).toEqual([]); await session.page.setViewportSize({ width: 390, height: 844 }); await session.page.goto('/admin'); await openMenu(session.page); await session.page.getByRole('link', { name: 'Content tree' }).click(); await expect(session.page.getByRole('heading', { name: 'Content tree' })).toBeVisible(); await session.context.close() }
  const sales = await pageFor(browser, 'sales'); await sales.page.goto('/content-tree'); await expect(sales.page).toHaveURL(/\/admin\/login/); await sales.context.close()
})
