import { expect, test, type Browser, type Page } from '@playwright/test'
import { createRequire } from 'node:module'

const axeSource = createRequire(import.meta.url).resolve('axe-core/axe.min.js')
const origin = `https://127.0.0.1:${Number(process.env.CMS_E2E_PORT ?? 4300)}`

async function session(browser: Browser, token: string) {
  const context = await browser.newContext({ baseURL: origin, ignoreHTTPSErrors: true })
  await context.addCookies(['site_engine_session', '__Host-site_engine_session'].map(name => ({ name, value: token, url: origin, secure: true, httpOnly: true, sameSite: 'Lax' as const })))
  return { context, page: await context.newPage() }
}
async function axe(page: Page) {
  await page.addScriptTag({ path: axeSource })
  expect(await page.evaluate(async () => (await (window as unknown as { axe: typeof import('axe-core') }).axe.run('main', { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag22aa'] } })).violations)).toEqual([])
}

test('Site workspace captures real settings, redirects, and navigation into an owned draft', async ({ browser }, testInfo) => {
  test.setTimeout(60_000)
  const owner = await session(browser, 'synthetic-site-owner-session-token')
  const themeDraft = await owner.page.request.post('/api/themes', { headers: { origin, 'content-type': 'application/json' }, data: { id: 'navigation-browser-theme', version: '1.6.0', changeSetName: 'Navigation 1.6 browser draft' } })
  expect(themeDraft.status(), await themeDraft.text()).toBe(201)
  const publicationBefore = await owner.page.request.get('/__e2e/publish-state').then(response => response.json())
  await owner.page.goto('/site')
  await expect(owner.page.locator('[data-site-workspace]')).toBeVisible()
  await expect(owner.page.getByRole('button', { name: 'Business details', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(owner.page.getByRole('link', { name: 'Site', exact: true })).toHaveAttribute('aria-current', 'page')
  await owner.page.getByLabel('Save changes to').selectOption({ label: 'Navigation 1.6 browser draft · open' })

  await owner.page.getByLabel('Business name').fill('Synthetic Site Workspace')
  await owner.page.getByLabel('Legal name').fill('Synthetic Site Workspace Incorporated')
  await owner.page.getByLabel(/Phone/).fill('+1 555 010 0260')
  await owner.page.getByText('Edit address', { exact: true }).click()
  await owner.page.getByLabel('Street address').fill('100 Example Road')
  await owner.page.getByLabel('City').fill('Toronto')
  await owner.page.getByLabel('Province or region').fill('ON')
  await owner.page.getByLabel('Postal code').fill('M5V 2T6')
  await owner.page.getByText('Additional site settings', { exact: true }).click()
  const homepage = owner.page.getByLabel('Homepage')
  await homepage.selectOption('cccccccc-cccc-4ccc-8ccc-cccccccccccc')
  await expect(homepage).toHaveValue('cccccccc-cccc-4ccc-8ccc-cccccccccccc')
  await owner.page.getByLabel('LinkedIn URL').fill('https://www.linkedin.com/company/synthetic-site-workspace')
  await owner.page.getByLabel('Bar label').fill('Incident in progress?')
  await owner.page.getByLabel('Guidance').fill('Call the incident line and preserve affected systems.')
  await owner.page.getByText('Edit address', { exact: true }).click()
  await owner.page.getByRole('button', { name: 'Save business details' }).click()
  await expect(owner.page.getByRole('status')).toContainText('Public content is unchanged')
  await owner.page.setViewportSize({ width: 1440, height: 1000 })
  await owner.page.evaluate(() => new Promise<void>(resolve => { scrollTo(0, 0); requestAnimationFrame(() => requestAnimationFrame(() => resolve())) }))
  const inputStyle = await owner.page.getByLabel('Business name').evaluate(element => ({ font: getComputedStyle(element).fontFamily, weight: getComputedStyle(element).fontWeight }))
  expect(inputStyle.font).not.toMatch(/Times New Roman/)
  expect(inputStyle.weight).toBe('400')
  const desktop = testInfo.outputPath('site-business-details-1440.png'); await owner.page.screenshot({ path: desktop, fullPage: true }); await testInfo.attach('Site Business details 1440', { path: desktop, contentType: 'image/png' })

  await owner.page.getByRole('button', { name: 'Redirects' }).click()
  await expect(owner.page).toHaveURL(/tab=redirects/)
  await expect(owner.page.locator('[data-redirects-table]')).toBeVisible()
  await expect(owner.page.locator('[data-redirect-form]')).toHaveCount(0)
  await owner.page.getByRole('button', { name: '+ Add redirect', exact: true }).click()
  await expect(owner.page.getByLabel('Old address')).toBeFocused()
  await owner.page.getByLabel('Old address').fill('/site-workspace-old')
  await owner.page.getByLabel('Goes to').fill('/contact')
  await owner.page.getByRole('button', { name: 'Add redirect', exact: true }).click()
  await expect(owner.page.getByRole('cell', { name: '/site-workspace-old' })).toBeVisible()
  await expect(owner.page.getByRole('cell', { name: 'Synthetic Site Owner' })).toBeVisible()
  await expect(owner.page.locator('[data-redirect-form]')).toHaveCount(0)
  await owner.page.locator('[data-redirect-row]').filter({ hasText: '/site-workspace-old' }).getByRole('button', { name: 'Edit' }).click()
  await expect(owner.page.locator('[data-redirect-form-mode="edit"]')).toBeVisible()
  await expect(owner.page.getByLabel('Old address')).toBeFocused()
  await owner.page.getByLabel('Goes to').fill('/contact-us')
  await owner.page.getByRole('button', { name: 'Save redirect' }).click()
  await expect(owner.page.getByRole('cell', { name: '/contact-us' })).toBeVisible()
  await expect(owner.page.getByRole('cell', { name: 'Synthetic Site Owner' })).toBeVisible()
  await axe(owner.page)
  await owner.page.screenshot({ path: testInfo.outputPath('site-redirects-1440.png'), fullPage: true })

  await owner.page.getByRole('button', { name: 'Search and AI' }).click()
  await expect(owner.page.getByLabel('Search engines')).toBeChecked()
  await expect(owner.page.getByLabel('AI search and answers')).toBeChecked()
  await expect(owner.page.getByLabel('AI model training')).toBeChecked()
  await expect(owner.page.getByRole('button', { name: 'Save Search and AI' })).toBeDisabled()
  await expect(owner.page.locator('[data-site-search-ai]')).toContainText('Select a contract 1.7 theme')

  const sets = await owner.page.request.get('/api/editorial/list').then(response => response.json()) as { sets: Array<{ id: string; name: string; state: string; changes: Array<{ collection: string }> }> }
  const captured = sets.sets.find(item => item.name === 'Navigation 1.6 browser draft')
  expect(captured).toMatchObject({ state: 'open' })
  expect(captured?.changes.map(change => change.collection)).toEqual(expect.arrayContaining(['site-settings', 'redirects']))
  expect(await owner.page.request.get('/__e2e/publish-state').then(response => response.json())).toMatchObject({ releaseCount: publicationBefore.releaseCount })

  await owner.page.getByRole('button', { name: 'Navigation' }).click()
  const navigationContext = await owner.page.request.get('/api/site-workspace').then(response => response.json()) as { changeSets: Array<{ name: string; contractVersion: string | null }> }
  expect(navigationContext.changeSets.find(set => set.name === 'Navigation 1.6 browser draft')?.contractVersion).toBe('1.6.0')
  await owner.page.getByRole('button', { name: 'Add header item' }).click()
  await owner.page.getByRole('button', { name: 'Add header item' }).click()
  const headerRows = owner.page.locator('[data-site-navigation-header] [data-site-navigation-item]')
  await headerRows.first().locator('summary').click()
  await headerRows.first().getByLabel('Label', { exact: true }).fill('First browser link')
  await headerRows.first().locator('summary').click()
  await headerRows.nth(1).locator('summary').click()
  await headerRows.nth(1).getByLabel('Label', { exact: true }).fill('Second browser link')
  await headerRows.nth(1).locator('summary').click()
  await owner.page.getByRole('button', { name: 'Move Second browser link up', exact: true }).click()
  await expect(headerRows.first()).toContainText('Second browser link')
  await owner.page.getByRole('button', { name: 'Add header item' }).click()
  await headerRows.nth(2).locator('summary').click()
  await headerRows.nth(2).getByLabel('Type').selectOption('unavailable')
  await headerRows.nth(2).getByLabel('Label', { exact: true }).fill('Insights')
  await headerRows.nth(2).getByLabel('Explanation').fill('Insights are not published yet.')
  await owner.page.getByRole('button', { name: 'Add links column' }).click()
  await owner.page.getByRole('button', { name: 'Add a link', exact: true }).click()
  await owner.page.getByRole('button', { name: 'Add generated Services' }).click()
  await owner.page.getByLabel('Services section').selectOption({ label: 'Metadata browser section' })
  await owner.page.getByRole('button', { name: 'Add contact details' }).click()
  await owner.page.getByRole('button', { name: 'Add bottom link' }).click()
  const bottom = owner.page.locator('[data-site-navigation-bottom]').locator('[data-site-navigation-item]').last()
  await bottom.locator('summary').click(); await bottom.getByLabel('Type').selectOption('unavailable'); await bottom.getByLabel('Label', { exact: true }).fill('Privacy'); await bottom.getByLabel('Explanation').fill('Privacy is not published yet.')
  await owner.page.getByLabel('Copyright').fill('© {year} Synthetic Site Workspace Incorporated')
  const navigationSaved = owner.page.waitForResponse(response => response.url().endsWith('/api/site-workspace') && response.request().method() === 'POST')
  await owner.page.getByRole('button', { name: 'Save navigation' }).click(); expect((await navigationSaved).status()).toBe(200)
  await expect(owner.page.getByRole('status')).toContainText('Public content is unchanged')
  await owner.page.getByText('Current content structure', { exact: true }).click()
  await expect(owner.page.getByRole('link', { name: 'Edit pages and structure in Content' })).toHaveAttribute('href', '/content-tree')
  await owner.page.getByText('Current content structure', { exact: true }).click()
  const navSettings = await owner.page.request.get('/api/site-workspace').then(response => response.json())
  expect(navSettings.changeSets.find((set: { name: string }) => set.name === 'Navigation 1.6 browser draft')?.contractVersion).toBe('1.6.0')
  expect(navSettings.settings.navigation.header.map((item: { label: string }) => item.label)).toEqual(['Second browser link', 'First browser link', 'Insights'])
  expect(navSettings.settings.navigation.footer.columns.map((column: { kind?: string }) => column.kind ?? 'links')).toEqual(['links', 'section-pillars', 'contact'])
  await expect(owner.page.locator('[data-navigation-column-kind="section-pillars"]').getByText('Metadata service pillar', { exact: true })).toBeVisible()
  for (const width of [1440, 390]) {
    await owner.page.setViewportSize({ width, height: 1000 })
    await owner.page.evaluate(() => scrollTo(0, 0))
    expect(await owner.page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    await axe(owner.page)
    await owner.page.screenshot({ path: testInfo.outputPath(`site-navigation-${width}.png`), fullPage: true })
  }

  await owner.page.getByRole('button', { name: 'Theme' }).click()
  await expect(owner.page.getByRole('heading', { name: 'Themes' })).toBeVisible()
  await axe(owner.page)

  await owner.page.setViewportSize({ width: 390, height: 844 })
  await owner.page.getByRole('button', { name: 'Redirects' }).click()
  expect(await owner.page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(392)
  const redirectTable = owner.page.locator('[data-redirects-table]')
  expect(await redirectTable.evaluate(element => element.scrollWidth > element.clientWidth)).toBe(true)
  await redirectTable.focus(); await expect(redirectTable).toBeFocused()
  const initialScroll = await redirectTable.evaluate(element => element.scrollLeft)
  await owner.page.keyboard.press('ArrowRight')
  await expect.poll(() => redirectTable.evaluate(element => element.scrollLeft)).toBeGreaterThan(initialScroll)
  await axe(owner.page)
  await owner.page.screenshot({ path: testInfo.outputPath('site-redirects-390.png'), fullPage: true })
  await owner.page.getByRole('button', { name: 'Business details', exact: true }).click()
  await owner.page.evaluate(() => new Promise<void>(resolve => { scrollTo(0, 0); requestAnimationFrame(() => requestAnimationFrame(() => resolve())) }))
  const mobile = testInfo.outputPath('site-business-details-390.png'); await owner.page.screenshot({ path: mobile, fullPage: true }); await testInfo.attach('Site Business details 390', { path: mobile, contentType: 'image/png' })
  await axe(owner.page)

  // The suite intentionally shares a real SQLite database. Complete this
  // fixture's open theme-settings lifecycle so the following Theme workspace
  // test starts from the published selection instead of a foreign Owner's
  // unresolved 1.6 selection. This uses the normal guarded discard path and
  // therefore also proves that the draft can be safely restored.
  const discarded = await owner.page.request.post('/api/editorial/discard', { headers: { origin, 'content-type': 'application/json' }, data: { id: captured!.id } })
  expect(discarded.status(), await discarded.text()).toBe(200)
  await owner.context.close()
})

test('Site workspace rejects non-owners and cross-origin writes', async ({ browser }) => {
  const editor = await session(browser, 'synthetic-application-editor-session-token')
  expect((await editor.page.request.get('/api/site-workspace')).status()).toBe(403)
  await editor.page.goto('/site')
  await expect(editor.page).toHaveURL(/\/admin\/login/)
  await editor.context.close()

  const owner = await session(browser, 'synthetic-site-owner-session-token')
  const response = await owner.page.request.post('/api/site-workspace', { headers: { origin: 'https://attacker.example', 'content-type': 'application/json' }, data: {} })
  expect(response.status()).toBe(403)
  const otherOwner = await session(browser, 'synthetic-theme-owner-session-token')
  const foreignSet = await otherOwner.page.request.post('/api/editorial/create', { headers: { origin, 'content-type': 'application/json' }, data: { name: 'Foreign Site draft' } }).then(result => result.json()) as { id: string; revision: number }
  const current = await owner.page.request.get('/api/site-workspace').then(result => result.json()) as { settings: Record<string, unknown>; settingsHash: string }
  const foreignWrite = await owner.page.request.post('/api/site-workspace', { headers: { origin, 'content-type': 'application/json' }, data: { action: 'settings', changeSetID: foreignSet.id, expectedRevision: foreignSet.revision, expectedHash: current.settingsHash, value: current.settings } })
  expect(foreignWrite.status()).toBe(400)
  expect(await foreignWrite.json()).toMatchObject({ error: expect.stringContaining('not owned') })
  await otherOwner.context.close()
  await owner.context.close()
})
