import { expect, test, type Browser, type Page, type TestInfo } from '@playwright/test'
import { createRequire } from 'node:module'

const axeSource = createRequire(import.meta.url).resolve('axe-core/axe.min.js')
const origin = `https://127.0.0.1:${Number(process.env.CMS_E2E_PORT ?? 4300)}`

async function session(browser: Browser, token: string) {
  const context = await browser.newContext({ baseURL: origin, ignoreHTTPSErrors: true })
  await context.addCookies(['site_engine_session', '__Host-site_engine_session'].map(name => ({ name, value: token, url: origin, secure: true, httpOnly: true, sameSite: 'Lax' as const })))
  return { context, page: await context.newPage() }
}
async function axe(page: Page) {
  await page.addScriptTag({ path: axeSource })
  expect(await page.evaluate(async () => (await (window as unknown as { axe: typeof import('axe-core') }).axe.run('main', { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag22aa'] } })).violations)).toEqual([])
}

async function attachThemeFontEvidence(page: Page, testInfo: TestInfo) {
  const cdp = await page.context().newCDPSession(page)
  try {
    await cdp.send('DOM.enable'); await cdp.send('CSS.enable')
    const { root } = await cdp.send('DOM.getDocument', { depth: -1, pierce: true })
    const evidence = []
    for (const [name, selector] of [['theme heading', '[data-theme-card] h3'], ['theme body', '[data-theme-card] p']] as const) {
      const { nodeId } = await cdp.send('DOM.querySelector', { nodeId: root.nodeId, selector })
      expect(nodeId, `${name} font target exists`).toBeTruthy()
      const { fonts } = await cdp.send('CSS.getPlatformFontsForNode', { nodeId })
      expect(fonts.length, `${name} has a rendered platform font`).toBeGreaterThan(0)
      evidence.push({ name, selector, fonts })
    }
    await testInfo.attach('Theme rendered platform fonts', { body: Buffer.from(JSON.stringify(evidence, null, 2)), contentType: 'application/json' })
    if (await page.locator('link[href="/admin-branding/admin-branding.css"]').count()) {
      expect(evidence.every(({ fonts }) => fonts.some(font => font.isCustomFont && font.familyName.startsWith('IBM Plex Sans'))), JSON.stringify(evidence)).toBe(true)
    }
  } finally { await cdp.detach() }
}

test('Site workspace captures real settings, redirects, and navigation into an owned draft', async ({ browser }, testInfo) => {
  test.setTimeout(60_000)
  const owner = await session(browser, 'synthetic-site-owner-session-token')
  const themeDraft = await owner.page.request.post('/api/themes', { headers: { origin, 'content-type': 'application/json' }, data: { id: 'navigation-browser-theme', version: '1.6.0', changeSetName: 'Navigation 1.6 browser draft' } })
  expect(themeDraft.status(), await themeDraft.text()).toBe(201)
  const publicationBefore = await owner.page.request.get('/__e2e/publish-state').then(response => response.json())
  await owner.page.goto('/site')
  await expect(owner.page.locator('[data-site-workspace]')).toBeVisible()
  await expect(owner.page.getByRole('button', { name: 'Business details', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(owner.page.getByRole('link', { name: 'Site', exact: true })).toHaveAttribute('aria-current', 'page')
  await owner.page.getByLabel('Save changes to').selectOption({ label: 'Navigation 1.6 browser draft · open' })

  await owner.page.getByLabel('Business name').fill('Synthetic Site Workspace')
  await owner.page.getByLabel('Legal name').fill('Synthetic Site Workspace Incorporated')
  await owner.page.getByLabel(/Phone/).fill('+1 555 010 0260')
  await owner.page.getByText('Edit address', { exact: true }).click()
  await owner.page.getByLabel('Street address').fill('100 Example Road')
  await owner.page.getByLabel('City').fill('Toronto')
  await owner.page.getByLabel('Province or region').fill('ON')
  await owner.page.getByLabel('Postal code').fill('M5V 2T6')
  await owner.page.getByText('Additional site settings', { exact: true }).click()
  const homepage = owner.page.getByLabel('Homepage')
  await homepage.selectOption('cccccccc-cccc-4ccc-8ccc-cccccccccccc')
  await expect(homepage).toHaveValue('cccccccc-cccc-4ccc-8ccc-cccccccccccc')
  await owner.page.getByLabel('LinkedIn URL').fill('https://www.linkedin.com/company/synthetic-site-workspace')
  await owner.page.getByLabel('Bar label').fill('Incident in progress?')
  await owner.page.getByLabel('Guidance').fill('Call the incident line and preserve affected systems.')
  await owner.page.getByText('Edit address', { exact: true }).click()
  await owner.page.getByRole('button', { name: 'Save business details' }).click()
  await expect(owner.page.getByRole('status')).toContainText('Public content is unchanged')
  await owner.page.setViewportSize({ width: 1440, height: 1000 })
  await owner.page.evaluate(() => new Promise<void>(resolve => { scrollTo(0, 0); requestAnimationFrame(() => requestAnimationFrame(() => resolve())) }))
  const inputStyle = await owner.page.getByLabel('Business name').evaluate(element => ({ font: getComputedStyle(element).fontFamily, weight: getComputedStyle(element).fontWeight }))
  expect(inputStyle.font).not.toMatch(/Times New Roman/)
  expect(inputStyle.weight).toBe('400')
  const desktop = testInfo.outputPath('site-business-details-1440.png'); await owner.page.screenshot({ path: desktop, fullPage: true }); await testInfo.attach('Site Business details 1440', { path: desktop, contentType: 'image/png' })

  await owner.page.getByRole('button', { name: 'Redirects' }).click()
  await expect(owner.page).toHaveURL(/tab=redirects/)
  await expect(owner.page.locator('[data-redirects-table]')).toBeVisible()
  await expect(owner.page.locator('[data-redirect-form]')).toHaveCount(0)
  await owner.page.getByRole('button', { name: '+ Add redirect', exact: true }).click()
  await expect(owner.page.getByLabel('Old address')).toBeFocused()
  await owner.page.getByLabel('Old address').fill('/site-workspace-old')
  await owner.page.getByLabel('Goes to').fill('/contact')
  await owner.page.getByRole('button', { name: 'Add redirect', exact: true }).click()
  await expect(owner.page.getByRole('cell', { name: '/site-workspace-old' })).toBeVisible()
  await expect(owner.page.getByRole('cell', { name: 'Synthetic Site Owner' })).toBeVisible()
  await expect(owner.page.locator('[data-redirect-form]')).toHaveCount(0)
  await owner.page.locator('[data-redirect-row]').filter({ hasText: '/site-workspace-old' }).getByRole('button', { name: 'Edit' }).click()
  await expect(owner.page.locator('[data-redirect-form-mode="edit"]')).toBeVisible()
  await expect(owner.page.getByLabel('Old address')).toBeFocused()
  await owner.page.getByLabel('Goes to').fill('/contact-us')
  await owner.page.getByRole('button', { name: 'Save redirect' }).click()
  await expect(owner.page.getByRole('cell', { name: '/contact-us' })).toBeVisible()
  await expect(owner.page.getByRole('cell', { name: 'Synthetic Site Owner' })).toBeVisible()
  await owner.page.reload()
  await owner.page.getByLabel('Save changes to').selectOption({ label: 'Navigation 1.6 browser draft · open' })
  await owner.page.getByRole('button', { name: 'Redirects' }).click()
  await expect(owner.page.getByRole('cell', { name: '/contact-us' })).toBeVisible()
  await expect(owner.page.locator('[aria-live="polite"]')).toBeEmpty()
  await axe(owner.page)
  await owner.page.screenshot({ path: testInfo.outputPath('site-redirects-1440.png'), fullPage: true })

  await owner.page.getByRole('button', { name: 'Search and AI' }).click()
  await expect(owner.page.getByLabel('Search engines')).toBeChecked()
  await expect(owner.page.getByLabel('AI search and answers')).toBeChecked()
  await expect(owner.page.getByLabel('AI model training')).toBeChecked()
  await expect(owner.page.getByRole('button', { name: 'Save Search and AI' })).toBeDisabled()
  await expect(owner.page.locator('[data-site-search-ai]')).toContainText('Select a contract 1.7 theme')

  const sets = await owner.page.request.get('/api/editorial/list').then(response => response.json()) as { sets: Array<{ id: string; name: string; state: string; changes: Array<{ collection: string }> }> }
  const captured = sets.sets.find(item => item.name === 'Navigation 1.6 browser draft')
  expect(captured).toMatchObject({ state: 'open' })
  expect(captured?.changes.map(change => change.collection)).toEqual(expect.arrayContaining(['site-settings', 'redirects']))
  expect(await owner.page.request.get('/__e2e/publish-state').then(response => response.json())).toMatchObject({ releaseCount: publicationBefore.releaseCount })

  await owner.page.getByRole('button', { name: 'Navigation' }).click()
  const navigationContext = await owner.page.request.get('/api/site-workspace').then(response => response.json()) as { changeSets: Array<{ name: string; contractVersion: string | null }> }
  expect(navigationContext.changeSets.find(set => set.name === 'Navigation 1.6 browser draft')?.contractVersion).toBe('1.6.0')
  await owner.page.getByRole('button', { name: 'Add header item' }).click()
  await owner.page.getByRole('button', { name: 'Add header item' }).click()
  const headerRows = owner.page.locator('[data-site-navigation-header] [data-site-navigation-item]')
  await expect(owner.page.locator('[data-navigation-editor][open]')).toHaveCount(0)
  await headerRows.first().locator('summary').click()
  await expect(headerRows.first().locator('[data-navigation-editor]')).toHaveAttribute('open', '')
  await expect(headerRows.first().locator('summary')).toHaveAttribute('aria-expanded', 'true')
  await headerRows.first().getByLabel('Label', { exact: true }).fill('First browser link')
  await headerRows.nth(1).locator('summary').click()
  await expect(headerRows.first().locator('[data-navigation-editor]')).not.toHaveAttribute('open', '')
  await expect(owner.page.locator('[data-navigation-editor][open]')).toHaveCount(1)
  await headerRows.nth(1).getByLabel('Label', { exact: true }).fill('Second browser link')
  await headerRows.first().locator('summary').click()
  await expect(headerRows.first().getByLabel('Label', { exact: true })).toHaveValue('First browser link')
  await headerRows.first().locator('summary').click()
  await owner.page.getByRole('button', { name: 'Move Second browser link up', exact: true }).click()
  await expect(headerRows.first()).toContainText('Second browser link')
  await owner.page.getByRole('button', { name: 'Add header item' }).click()
  await headerRows.nth(2).locator('summary').click()
  await headerRows.nth(2).getByLabel('Type').selectOption('unavailable')
  await headerRows.nth(2).getByLabel('Label', { exact: true }).fill('Insights')
  await headerRows.nth(2).getByLabel('Explanation').fill('')
  await headerRows.nth(2).locator('summary').click()
  await owner.page.getByRole('button', { name: 'Save navigation' }).click()
  await expect(headerRows.nth(2).locator('[data-navigation-editor]')).toHaveAttribute('open', '')
  await expect(headerRows.nth(2).getByLabel('Explanation')).toBeFocused()
  const navigationValidation = owner.page.locator('[data-site-navigation] p[role="alert"]')
  await expect(navigationValidation).toHaveText('Complete the required field in the opened navigation item.')
  await headerRows.nth(2).getByLabel('Explanation').fill('Insights are not published yet.')
  await expect(navigationValidation).toHaveCount(0)
  await owner.page.getByRole('button', { name: 'Add links column' }).click()
  await owner.page.getByRole('button', { name: 'Add a link', exact: true }).click()
  await owner.page.getByRole('button', { name: 'Add generated Services' }).click()
  await owner.page.getByLabel('Services section').selectOption({ label: 'Metadata browser section' })
  await owner.page.getByRole('button', { name: 'Add contact details' }).click()
  await owner.page.getByRole('button', { name: 'Add bottom link' }).click()
  const bottom = owner.page.locator('[data-site-navigation-bottom]').locator('[data-site-navigation-item]').last()
  await bottom.locator('summary').click(); await bottom.getByLabel('Type').selectOption('unavailable'); await bottom.getByLabel('Label', { exact: true }).fill('Privacy'); await bottom.getByLabel('Explanation').fill('Privacy is not published yet.')
  await expect(owner.page.locator('[data-navigation-editor][open]')).toHaveCount(1)
  await expect(headerRows.nth(2).locator('[data-navigation-editor]')).not.toHaveAttribute('open', '')
  await headerRows.nth(2).locator('summary').click()
  await expect(headerRows.nth(2).getByLabel('Explanation')).toHaveValue('Insights are not published yet.')
  await expect(bottom.locator('[data-navigation-editor]')).not.toHaveAttribute('open', '')
  await headerRows.nth(2).locator('summary').click()
  await expect(owner.page.locator('[data-navigation-editor][open]')).toHaveCount(0)
  await owner.page.getByLabel('Copyright').fill('© {year} Synthetic Site Workspace Incorporated')
  const navigationSaved = owner.page.waitForResponse(response => response.url().endsWith('/api/site-workspace') && response.request().method() === 'POST')
  await owner.page.getByRole('button', { name: 'Save navigation' }).click(); expect((await navigationSaved).status()).toBe(200)
  await expect(owner.page.getByRole('status')).toContainText('Public content is unchanged')
  await owner.page.getByText('Current content structure', { exact: true }).click()
  await expect(owner.page.getByRole('link', { name: 'Edit pages and structure in Content' })).toHaveAttribute('href', '/content-tree')
  await owner.page.getByText('Current content structure', { exact: true }).click()
  const navSettings = await owner.page.request.get('/api/site-workspace').then(response => response.json())
  expect(navSettings.changeSets.find((set: { name: string }) => set.name === 'Navigation 1.6 browser draft')?.contractVersion).toBe('1.6.0')
  expect(navSettings.settings.navigation.header.map((item: { label: string }) => item.label)).toEqual(['Second browser link', 'First browser link', 'Insights'])
  expect(navSettings.settings.navigation.header[2]).toMatchObject({ kind: 'unavailable', reason: 'Insights are not published yet.' })
  expect(navSettings.settings.navigation.footer.bottomLinks.at(-1)).toMatchObject({ kind: 'unavailable', label: 'Privacy', reason: 'Privacy is not published yet.' })
  expect(navSettings.settings.navigation.footer.columns.map((column: { kind?: string }) => column.kind ?? 'links')).toEqual(['links', 'section-pillars', 'contact'])
  await expect(owner.page.locator('[data-navigation-column-kind="section-pillars"]').getByText('Metadata service pillar', { exact: true })).toBeVisible()
  for (const width of [1440, 390]) {
    await owner.page.setViewportSize({ width, height: 1000 })
    await owner.page.evaluate(() => scrollTo(0, 0))
    await expect(owner.page.locator('[data-site-navigation] fieldset').first()).toBeEnabled()
    await owner.page.evaluate(() => document.fonts.ready.then(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve())))))
    await expect(owner.page.locator('[data-navigation-editor][open]')).toHaveCount(0)
    if (width === 390) {
      const summary = headerRows.first().locator('summary')
      await summary.focus(); await owner.page.keyboard.press('Enter')
      await expect(summary).toHaveAttribute('aria-expanded', 'true')
      await expect(headerRows.first().getByLabel('Type')).toBeFocused()
      await owner.page.keyboard.press('Escape')
      await expect(summary).toHaveAttribute('aria-expanded', 'false')
      await expect(summary).toBeFocused()
    }
    const bottomAction = owner.page.getByRole('button', { name: 'Add bottom link', exact: true })
    await expect(bottomAction).toBeEnabled()
    await expect(bottomAction).toBeVisible()
    expect(await bottomAction.evaluate(element => { const style = getComputedStyle(element); return { background: style.backgroundColor, color: style.color, visibility: style.visibility } })).toEqual({ background: 'rgba(0, 0, 0, 0)', color: 'rgb(22, 76, 120)', visibility: 'visible' })
    const disabledColumnActions = owner.page.locator('[data-site-navigation-add]:disabled').filter({ hasText: /Add (links column|generated Services|contact details)/ })
    await expect(disabledColumnActions).toHaveCount(3)
    expect(await disabledColumnActions.evaluateAll(elements => elements.every(element => { const style = getComputedStyle(element); return style.color === 'rgb(22, 76, 120)' && style.backgroundColor === 'rgba(0, 0, 0, 0)' && style.visibility === 'visible' }))).toBe(true)
    const contactLabel = owner.page.locator('[data-navigation-column-kind="contact"] label').filter({ hasText: /^Phone$/ }).first()
    const contactControlStyle = await contactLabel.evaluate(label => { const input = label.querySelector('input')!; const labelStyle = getComputedStyle(label), inputStyle = getComputedStyle(input), labelBox = label.getBoundingClientRect(), inputBox = input.getBoundingClientRect(); return { accent: inputStyle.accentColor, display: labelStyle.display, fontWeight: labelStyle.fontWeight, height: inputBox.height, width: inputBox.width, aligned: Math.abs((inputBox.top + inputBox.height / 2) - (labelBox.top + labelBox.height / 2)) <= 1 } })
    expect(contactControlStyle).toEqual({ accent: 'rgb(10, 58, 94)', display: 'flex', fontWeight: '400', height: 16, width: 16, aligned: true })
    expect(await owner.page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    await axe(owner.page)
    const navigationShot = testInfo.outputPath(`site-navigation-${width}.png`)
    await owner.page.screenshot({ path: navigationShot, fullPage: true })
    await testInfo.attach(`Site Navigation ${width}`, { path: navigationShot, contentType: 'image/png' })
  }

  await owner.page.getByRole('button', { name: 'Theme' }).click()
  await expect(owner.page.getByRole('heading', { name: 'Themes' })).toBeVisible()
  await owner.page.setViewportSize({ width: 1440, height: 1000 })
  const themePanel = owner.page.locator('[data-site-panel="theme"]')
  const embeddedTheme = owner.page.locator('[data-theme-embedded="true"]')
  for (const target of [themePanel, embeddedTheme, owner.page.locator('[data-theme-grid]')]) {
    await expect(target).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
    await expect(target).toHaveCSS('border-top-width', '0px')
    await expect(target).toHaveCSS('border-radius', '0px')
  }
  await expect(themePanel).toHaveCSS('padding-left', '0px')
  await expect(embeddedTheme).toHaveCSS('padding-left', '0px')
  await attachThemeFontEvidence(owner.page, testInfo)
  await owner.page.evaluate(() => new Promise<void>(resolve => { scrollTo(0, 0); requestAnimationFrame(() => requestAnimationFrame(() => resolve())) }))
  const themeDesktop = testInfo.outputPath('site-theme-1440.png'); await owner.page.screenshot({ path: themeDesktop, fullPage: true }); await testInfo.attach('Site Theme 1440', { path: themeDesktop, contentType: 'image/png' })
  await axe(owner.page)

  await owner.page.setViewportSize({ width: 390, height: 844 })
  expect(await owner.page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(392)
  const themeMobile = testInfo.outputPath('site-theme-390.png'); await owner.page.screenshot({ path: themeMobile, fullPage: true }); await testInfo.attach('Site Theme 390', { path: themeMobile, contentType: 'image/png' })

  // Clear the transient navigation save notice before the source-comparison
  // capture while retaining the populated redirect through the draft API.
  await owner.page.reload()
  await owner.page.setViewportSize({ width: 390, height: 844 })
  await owner.page.getByRole('button', { name: 'Redirects' }).click()
  await owner.page.getByLabel('Save changes to').selectOption({ label: 'Navigation 1.6 browser draft · open' })
  await expect(owner.page.locator('[aria-live="polite"]')).toBeEmpty()
  expect(await owner.page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(392)
  const redirectTable = owner.page.locator('[data-redirects-table]')
  expect(await redirectTable.evaluate(element => element.scrollWidth > element.clientWidth)).toBe(true)
  await redirectTable.focus(); await expect(redirectTable).toBeFocused()
  const initialScroll = await redirectTable.evaluate(element => element.scrollLeft)
  await owner.page.keyboard.press('ArrowRight')
  await expect.poll(() => redirectTable.evaluate(element => element.scrollLeft)).toBeGreaterThan(initialScroll)
  await axe(owner.page)
  await owner.page.screenshot({ path: testInfo.outputPath('site-redirects-390.png'), fullPage: true })
  await owner.page.getByRole('button', { name: 'Business details', exact: true }).click()
  await owner.page.evaluate(() => new Promise<void>(resolve => { scrollTo(0, 0); requestAnimationFrame(() => requestAnimationFrame(() => resolve())) }))
  const mobile = testInfo.outputPath('site-business-details-390.png'); await owner.page.screenshot({ path: mobile, fullPage: true }); await testInfo.attach('Site Business details 390', { path: mobile, contentType: 'image/png' })
  await axe(owner.page)

  // The suite intentionally shares a real SQLite database. Complete this
  // fixture's open theme-settings lifecycle so the following Theme workspace
  // test starts from the published selection instead of a foreign Owner's
  // unresolved 1.6 selection. This uses the normal guarded discard path and
  // therefore also proves that the draft can be safely restored.
  const discarded = await owner.page.request.post('/api/editorial/discard', { headers: { origin, 'content-type': 'application/json' }, data: { id: captured!.id } })
  expect(discarded.status(), await discarded.text()).toBe(200)
  await owner.context.close()
})

test('Site workspace saves navigation for the installed 1.8 theme', async ({ browser }) => {
  const owner = await session(browser, 'synthetic-site-owner-session-token')
  const draft = await owner.page.request.post('/api/themes', {
    headers: { origin, 'content-type': 'application/json' },
    data: { id: 'search-browser-theme', version: '1.8.0', changeSetName: 'Navigation 1.8 browser draft' },
  })
  expect(draft.status(), await draft.text()).toBe(201)

  await owner.page.goto('/site')
  await owner.page.getByLabel('Save changes to').selectOption({ label: 'Navigation 1.8 browser draft · open' })
  await owner.page.getByLabel('Business name').fill('Synthetic navigation compatibility site')
  await owner.page.getByRole('button', { name: 'Navigation' }).click()
  const workspace = owner.page.locator('[data-site-navigation]')
  await expect(workspace).toBeVisible()
  await owner.page.getByRole('button', { name: 'Add header item' }).click()
  const item = workspace.locator('[data-site-navigation-header] [data-site-navigation-item]').last()
  await item.locator('summary').click()
  await item.getByLabel('Type').selectOption('unavailable')
  await item.getByLabel('Label', { exact: true }).fill('1.8 browser navigation')
  await item.getByLabel('Explanation').fill('This synthetic destination is intentionally unavailable.')
  const saved = owner.page.waitForResponse(response => response.url().endsWith('/api/site-workspace') && response.request().method() === 'POST')
  await owner.page.getByRole('button', { name: 'Save navigation' }).click()
  const savedResponse = await saved
  expect(savedResponse.status(), await savedResponse.text()).toBe(200)
  const context = await owner.page.request.get('/api/site-workspace').then(response => response.json()) as { changeSets: Array<{ id: string; name: string; contractVersion: string | null }>; settings: { navigation: { header: Array<{ label: string; kind: string; reason?: string }> } } }
  expect(context.changeSets.find(set => set.name === 'Navigation 1.8 browser draft')?.contractVersion).toBe('1.8.0')
  expect(context.settings.navigation.header).toEqual(expect.arrayContaining([expect.objectContaining({ label: '1.8 browser navigation', kind: 'unavailable', reason: 'This synthetic destination is intentionally unavailable.' })]))

  const changeSet = context.changeSets.find(set => set.name === 'Navigation 1.8 browser draft')
  const discarded = await owner.page.request.post('/api/editorial/discard', { headers: { origin, 'content-type': 'application/json' }, data: { id: changeSet!.id } })
  expect(discarded.status(), await discarded.text()).toBe(200)
  await owner.context.close()
})

test('Site workspace rejects non-owners and cross-origin writes', async ({ browser }) => {
  const editor = await session(browser, 'synthetic-application-editor-session-token')
  expect((await editor.page.request.get('/api/site-workspace')).status()).toBe(403)
  await editor.page.goto('/site')
  await expect(editor.page).toHaveURL(/\/admin\/login/)
  await editor.context.close()

  const owner = await session(browser, 'synthetic-site-owner-session-token')
  const response = await owner.page.request.post('/api/site-workspace', { headers: { origin: 'https://attacker.example', 'content-type': 'application/json' }, data: {} })
  expect(response.status()).toBe(403)
  const otherOwner = await session(browser, 'synthetic-theme-owner-session-token')
  const foreignSet = await otherOwner.page.request.post('/api/editorial/create', { headers: { origin, 'content-type': 'application/json' }, data: { name: 'Foreign Site draft' } }).then(result => result.json()) as { id: string; revision: number }
  const current = await owner.page.request.get('/api/site-workspace').then(result => result.json()) as { settings: Record<string, unknown>; settingsHash: string }
  const foreignWrite = await owner.page.request.post('/api/site-workspace', { headers: { origin, 'content-type': 'application/json' }, data: { action: 'settings', changeSetID: foreignSet.id, expectedRevision: foreignSet.revision, expectedHash: current.settingsHash, value: current.settings } })
  expect(foreignWrite.status()).toBe(400)
  expect(await foreignWrite.json()).toMatchObject({ error: expect.stringContaining('not owned') })
  await otherOwner.context.close()
  await owner.context.close()
})
