/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    invitations: Invitation;
    'auth-sessions': AuthSession;
    'auth-transactions': AuthTransaction;
    'audit-events': AuditEvent;
    pages: Page;
    sections: Section;
    assets: Asset;
    'asset-file-versions': AssetFileVersion;
    redirects: Redirect;
    'theme-settings': ThemeSetting;
    'site-settings': SiteSetting;
    'style-guides': StyleGuide;
    'integration-configurations': IntegrationConfiguration;
    'mcp-privacy-settings': McpPrivacySetting;
    'provider-usage-reservations': ProviderUsageReservation;
    'mailbox-configurations': MailboxConfiguration;
    'mailbox-oauth-transactions': MailboxOauthTransaction;
    'mailbox-area-mappings': MailboxAreaMapping;
    'mailbox-test-sends': MailboxTestSend;
    inquiries: Inquiry;
    'notification-outbox': NotificationOutbox;
    'notification-deliveries': NotificationDelivery;
    'notification-preferences': NotificationPreference;
    'notification-user-preferences': NotificationUserPreference;
    'urgent-contacts': UrgentContact;
    'mail-conversation-suggestions': MailConversationSuggestion;
    'mail-drafts': MailDraft;
    'mail-threads': MailThread;
    'mail-thread-messages': MailThreadMessage;
    'external-replies': ExternalReply;
    'mail-authorizations': MailAuthorization;
    applications: Application;
    'retention-settings': RetentionSetting;
    'deletion-tombstones': DeletionTombstone;
    'retention-purge-jobs': RetentionPurgeJob;
    'change-sets': ChangeSet;
    'configured-ai-jobs': ConfiguredAiJob;
    'publish-snapshots': PublishSnapshot;
    'publish-outbox': PublishOutbox;
    'scheduled-publications': ScheduledPublication;
    'preview-render-jobs': PreviewRenderJob;
    'published-releases': PublishedRelease;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    invitations: InvitationsSelect<false> | InvitationsSelect<true>;
    'auth-sessions': AuthSessionsSelect<false> | AuthSessionsSelect<true>;
    'auth-transactions': AuthTransactionsSelect<false> | AuthTransactionsSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    sections: SectionsSelect<false> | SectionsSelect<true>;
    assets: AssetsSelect<false> | AssetsSelect<true>;
    'asset-file-versions': AssetFileVersionsSelect<false> | AssetFileVersionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'theme-settings': ThemeSettingsSelect<false> | ThemeSettingsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'style-guides': StyleGuidesSelect<false> | StyleGuidesSelect<true>;
    'integration-configurations': IntegrationConfigurationsSelect<false> | IntegrationConfigurationsSelect<true>;
    'mcp-privacy-settings': McpPrivacySettingsSelect<false> | McpPrivacySettingsSelect<true>;
    'provider-usage-reservations': ProviderUsageReservationsSelect<false> | ProviderUsageReservationsSelect<true>;
    'mailbox-configurations': MailboxConfigurationsSelect<false> | MailboxConfigurationsSelect<true>;
    'mailbox-oauth-transactions': MailboxOauthTransactionsSelect<false> | MailboxOauthTransactionsSelect<true>;
    'mailbox-area-mappings': MailboxAreaMappingsSelect<false> | MailboxAreaMappingsSelect<true>;
    'mailbox-test-sends': MailboxTestSendsSelect<false> | MailboxTestSendsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'notification-outbox': NotificationOutboxSelect<false> | NotificationOutboxSelect<true>;
    'notification-deliveries': NotificationDeliveriesSelect<false> | NotificationDeliveriesSelect<true>;
    'notification-preferences': NotificationPreferencesSelect<false> | NotificationPreferencesSelect<true>;
    'notification-user-preferences': NotificationUserPreferencesSelect<false> | NotificationUserPreferencesSelect<true>;
    'urgent-contacts': UrgentContactsSelect<false> | UrgentContactsSelect<true>;
    'mail-conversation-suggestions': MailConversationSuggestionsSelect<false> | MailConversationSuggestionsSelect<true>;
    'mail-drafts': MailDraftsSelect<false> | MailDraftsSelect<true>;
    'mail-threads': MailThreadsSelect<false> | MailThreadsSelect<true>;
    'mail-thread-messages': MailThreadMessagesSelect<false> | MailThreadMessagesSelect<true>;
    'external-replies': ExternalRepliesSelect<false> | ExternalRepliesSelect<true>;
    'mail-authorizations': MailAuthorizationsSelect<false> | MailAuthorizationsSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'retention-settings': RetentionSettingsSelect<false> | RetentionSettingsSelect<true>;
    'deletion-tombstones': DeletionTombstonesSelect<false> | DeletionTombstonesSelect<true>;
    'retention-purge-jobs': RetentionPurgeJobsSelect<false> | RetentionPurgeJobsSelect<true>;
    'change-sets': ChangeSetsSelect<false> | ChangeSetsSelect<true>;
    'configured-ai-jobs': ConfiguredAiJobsSelect<false> | ConfiguredAiJobsSelect<true>;
    'publish-snapshots': PublishSnapshotsSelect<false> | PublishSnapshotsSelect<true>;
    'publish-outbox': PublishOutboxSelect<false> | PublishOutboxSelect<true>;
    'scheduled-publications': ScheduledPublicationsSelect<false> | ScheduledPublicationsSelect<true>;
    'preview-render-jobs': PreviewRenderJobsSelect<false> | PreviewRenderJobsSelect<true>;
    'published-releases': PublishedReleasesSelect<false> | PublishedReleasesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  email: string;
  name: string;
  roles: ('owner' | 'approver' | 'editor' | 'sales' | 'hiring')[];
  disabled?: boolean | null;
  invitedAt?: string | null;
  provider?: ('google' | 'microsoft') | null;
  providerIssuer?: string | null;
  providerSubject?: string | null;
  emergencyTotpSecret?: string | null;
  emergencyRecoveryHashes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  emergencyLastCounter?: number | null;
  emergencyFailedAt?: string | null;
  emergencyFailedCount?: number | null;
  updatedAt: string;
  createdAt: string;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations".
 */
export interface Invitation {
  id: string;
  email: string;
  provider: 'google' | 'microsoft';
  /**
   * Trusted configured issuer for this invite.
   */
  providerIssuer: string;
  providerSubject: string;
  /**
   * Optional prebound verified OIDC subject. Enrollment always requires the one-time invitation.
   */
  requiredSubject?: string | null;
  /**
   * Opaque invite credential hash; its original value is never shown in admin.
   */
  tokenHash: string;
  roles: ('owner' | 'approver' | 'editor' | 'sales' | 'hiring')[];
  expiresAt: string;
  acceptedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-sessions".
 */
export interface AuthSession {
  id: string;
  tokenHash: string;
  user: string | User;
  authenticatedAt: string;
  lastSeenAt: string;
  expiresAt: string;
  revokedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-transactions".
 */
export interface AuthTransaction {
  id: string;
  stateHash: string;
  nonce: string;
  verifier: string;
  provider: 'google' | 'microsoft';
  invitation?: (string | null) | Invitation;
  expiresAt: string;
  consumedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: string;
  event: string;
  user?: (string | null) | User;
  actor?: (string | null) | User;
  detail?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  /**
   * Required content section.
   */
  sectionId: string | Section;
  /**
   * Parent page for tree-oriented navigation.
   */
  parentId?: (string | null) | Page;
  /**
   * Write one or two sentences for listings and editorial context.
   */
  summary: string;
  template: 'landing' | 'standard' | 'listing' | 'pillar' | 'service' | 'article' | 'job';
  status?: ('draft' | 'published' | 'archived') | null;
  blocks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Short service-page context shown above the page title.
   */
  kicker?: string | null;
  /**
   * Service-page introduction shown with the page title.
   */
  lede?: string | null;
  seoDescription?: string | null;
  /**
   * Keep this published page out of search engines and the public site search index.
   */
  noindex?: boolean | null;
  /**
   * Article publication date.
   */
  publishedAt?: string | null;
  /**
   * Date this service or article was last reviewed.
   */
  lastReviewed?: string | null;
  /**
   * Job posting date, employment type, location, and optional closing date.
   */
  jobPosting?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Article-only client or anonymized client, industry, challenge, approach, outcome, services, and publication date.
   */
  businessCase?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections".
 */
export interface Section {
  id: string;
  name: string;
  summary?: string | null;
  slug: string;
  landingPageId?: (string | null) | Page;
  allowedTemplates: ('landing' | 'standard' | 'listing' | 'pillar' | 'service' | 'article' | 'job')[];
  pageIds?: (string | Page)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets".
 */
export interface Asset {
  id: string;
  alt?: string | null;
  decorative?: boolean | null;
  caption?: string | null;
  credit?: string | null;
  tags?: string[] | null;
  currentFileVersion?: (string | null) | AssetFileVersion;
  currentFile?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  deletedAt?: string | null;
  deleteAfter?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    heroAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    heroWebp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    cardAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    cardWebp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnailAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnailWebp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-file-versions".
 */
export interface AssetFileVersion {
  id: string;
  parentAsset: string | Asset;
  digest: string;
  versionKey: string;
  idempotencyKey: string;
  originalFilename: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    heroAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    heroWebp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    cardAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    cardWebp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnailAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnailWebp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  from: string;
  to: string;
  status?: number | null;
  createdBy?: (string | null) | User;
  createdByLabel?: string | null;
  /**
   * Updated by the edge log ingestion adapter.
   */
  hitCount?: number | null;
  lastHitAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings".
 */
export interface ThemeSetting {
  id: string;
  key: string;
  selection:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  settings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  key: string;
  /**
   * Public site name.
   */
  siteName: string;
  legalName?: string | null;
  /**
   * Published landing page to use as the homepage.
   */
  homepageId?: (string | null) | Page;
  defaultLocale: 'en' | 'en-CA';
  organizationType?: ('organization' | 'professional-service') | null;
  logo?: (string | null) | Asset;
  logos?: {
    primaryLight?: (string | null) | Asset;
    primaryDark?: (string | null) | Asset;
    fullLockupLight?: (string | null) | Asset;
    fullLockupDark?: (string | null) | Asset;
    symbolLight?: (string | null) | Asset;
    symbolDark?: (string | null) | Asset;
  };
  contactEmail?: string | null;
  contactPhone?: string | null;
  seoDescription?: string | null;
  address?: {
    streetAddress?: string | null;
    addressLocality?: string | null;
    addressRegion?: string | null;
    postalCode?: string | null;
    addressCountry?: string | null;
  };
  linkedIn?: string | null;
  incident?: {
    label?: string | null;
    guidance?: string | null;
  };
  /**
   * Validated ordered header and footer references.
   */
  navigation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Expose the static public search page and include it in the primary navigation after this change is reviewed and published.
   */
  searchEnabled?: boolean | null;
  /**
   * Reviewed robots.txt requests. These preferences do not enforce access.
   */
  crawlerPolicy?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contractVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "style-guides".
 */
export interface StyleGuide {
  id: string;
  key: string;
  bannedPhrases?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  preferredTerms?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  canadianSpelling: 'off' | 'warn';
  maximumSentenceWords: number;
  minimumReadingEase: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integration-configurations".
 */
export interface IntegrationConfiguration {
  id: string;
  provider: 'openai' | 'anthropic' | 'google-gemini' | 'openrouter' | 'mistral';
  model: string;
  fallbackProvider?: ('openai' | 'anthropic' | 'google-gemini' | 'openrouter' | 'mistral') | null;
  monthlyCapMicroUsd?: number | null;
  monthlyUsageMicroUsd?: number | null;
  usageMonth?: string | null;
  inputMicroUsdPerMillionTokens?: number | null;
  outputMicroUsdPerMillionTokens?: number | null;
  pricingSource?: string | null;
  pricingAsOf?: string | null;
  encryptedCredential?: string | null;
  credentialFingerprint?: string | null;
  health: 'unknown' | 'connected' | 'unavailable' | 'rejected' | 'revoked';
  testedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mcp-privacy-settings".
 */
export interface McpPrivacySetting {
  id: string;
  key: string;
  hidePhone: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provider-usage-reservations".
 */
export interface ProviderUsageReservation {
  id: string;
  configuration: string | IntegrationConfiguration;
  executionKey: string;
  usageMonth: string;
  reservedMicroUsd: number;
  settledMicroUsd?: number | null;
  state: 'reserved' | 'settled' | 'released';
  configModel: string;
  credentialFingerprint?: string | null;
  inputMicroUsdPerMillionTokens: number;
  outputMicroUsdPerMillionTokens: number;
  pricingSource: string;
  pricingAsOf: string;
  requestInputTokens: number;
  maxOutputTokens: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailbox-configurations".
 */
export interface MailboxConfiguration {
  id: string;
  name: string;
  provider: 'smtp' | 'microsoft' | 'google';
  primaryAddress: string;
  aliases:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  verifiedAliases:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  host: string;
  port: number;
  security: 'starttls' | 'tls';
  username: string;
  encryptedCredential?: string | null;
  credentialRevision: string;
  health: 'unknown' | 'connected' | 'rejected' | 'unavailable' | 'revoked';
  testedAt?: string | null;
  inboundCursor?: string | null;
  inboundCursorRevision?: string | null;
  inboundNextAttemptAt?: string | null;
  inboundFailureCount?: number | null;
  inboundLastError?: string | null;
  inboundLastSyncedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailbox-oauth-transactions".
 */
export interface MailboxOauthTransaction {
  id: string;
  provider: 'microsoft' | 'google';
  stateHash: string;
  sessionHash: string;
  verifier: string;
  owner: string | User;
  expiresAt: string;
  consumedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailbox-area-mappings".
 */
export interface MailboxAreaMapping {
  id: string;
  area: 'leads' | 'careers' | 'notifications';
  mailbox: string | MailboxConfiguration;
  senderAddress: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailbox-test-sends".
 */
export interface MailboxTestSend {
  id: string;
  requestKey: string;
  requestHash: string;
  mailbox: string | MailboxConfiguration;
  senderAddress: string;
  recipientAddress: string;
  authorizedBy: string | User;
  state: 'sending' | 'sent' | 'failed';
  providerMessageID?: string | null;
  failureCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: string;
  email: string;
  name?: string | null;
  telephone?: string | null;
  company?: string | null;
  message: string;
  topic:
    'general' | 'project' | 'partnership' | 'active-incident' | 'consultation' | 'service' | 'retainer' | 'careers';
  sourcePage: string;
  consentedAt: string;
  consentBasis: 'visitor-confirmed' | 'staff-recorded' | 'unknown';
  idempotencyKey: string;
  stage: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost';
  spam?: boolean | null;
  spamMarkedAt?: string | null;
  spamPreviousStage?: ('new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost') | null;
  urgent?: boolean | null;
  notes?: string | null;
  assignee?: (string | null) | User;
  nextAction?: string | null;
  /**
   * Optional follow-up due date.
   */
  nextActionDueAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-outbox".
 */
export interface NotificationOutbox {
  id: string;
  inquiry?: (string | null) | Inquiry;
  kind:
    | 'new-lead'
    | 'active-incident-lead'
    | 'new-job-application'
    | 'change-set-submitted'
    | 'follow-ups-due'
    | 'publish-or-integration-failed';
  idempotencyKey: string;
  state: 'queued' | 'delivered' | 'failed';
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  recipientRules:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  recipients:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  channels:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sourceType?: string | null;
  sourceID?: string | null;
  availableAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-deliveries".
 */
export interface NotificationDelivery {
  id: string;
  outbox: string | NotificationOutbox;
  idempotencyKey: string;
  recipient:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  state: 'queued' | 'processing' | 'delivered' | 'retryable' | 'failed' | 'unknown' | 'unsupported';
  attempts: number;
  nextAttemptAt: string;
  leaseToken?: string | null;
  leaseExpiresAt?: string | null;
  providerMessageID?: string | null;
  failureCode?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-preferences".
 */
export interface NotificationPreference {
  id: string;
  key: string;
  events:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedBy: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-user-preferences".
 */
export interface NotificationUserPreference {
  id: string;
  user: string | User;
  mutedKinds:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "urgent-contacts".
 */
export interface UrgentContact {
  id: string;
  name: string;
  email: string;
  mobile?: string | null;
  enabled: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail-conversation-suggestions".
 */
export interface MailConversationSuggestion {
  id: string;
  mailbox: string | MailboxConfiguration;
  provider: 'smtp' | 'microsoft' | 'google';
  providerConversationID: string;
  addressHash: string;
  target: 'lead' | 'application';
  adoptedAt?: string | null;
  adoptedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail-drafts".
 */
export interface MailDraft {
  id: string;
  lead?: (string | null) | Inquiry;
  application?: (string | null) | Application;
  threadID: string;
  recipient: string;
  sender: string;
  subject: string;
  body: string;
  attachments?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  attachmentHashes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  assistantClientIDHash?: string | null;
  assistantActor?: (string | null) | User;
  assistantOAuthSessionID?: string | null;
  revision: number;
  state:
    | 'prepared'
    | 'authorized'
    | 'canceled'
    | 'revoked'
    | 'expired'
    | 'consumed'
    | 'sent'
    | 'failed'
    | 'delivery-unknown';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: string;
  name: string;
  email: string;
  telephone?: string | null;
  linkedIn?: string | null;
  coverLetter: string;
  consent: boolean;
  jobId: string;
  resumeKey: string;
  idempotencyKey: string;
  status?: ('new' | 'reviewing' | 'interview' | 'offer' | 'hired' | 'declined' | 'closed') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail-threads".
 */
export interface MailThread {
  id: string;
  lead?: (string | null) | Inquiry;
  application?: (string | null) | Application;
  mailbox: string | MailboxConfiguration;
  provider: 'smtp' | 'microsoft' | 'google';
  providerConversationID: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail-thread-messages".
 */
export interface MailThreadMessage {
  id: string;
  thread: string | MailThread;
  mailbox: string | MailboxConfiguration;
  lead?: (string | null) | Inquiry;
  application?: (string | null) | Application;
  providerMessageID: string;
  rfcMessageID?: string | null;
  rfcReferences?: string | null;
  direction: 'inbound' | 'outbound';
  sender: string;
  recipient: string;
  subject: string;
  body: string;
  receivedAt: string;
  attachmentMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-replies".
 */
export interface ExternalReply {
  id: string;
  lead: string | Inquiry;
  sentAt: string;
  subject: string;
  summary: string;
  recordedBy: string | User;
  idempotencyKey: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail-authorizations".
 */
export interface MailAuthorization {
  id: string;
  draft: string | MailDraft;
  digest: string;
  draftRevision: number;
  authorizedBy: string | User;
  humanConfirmationSessionID?: string | null;
  assistantClientIDHash?: string | null;
  assistantActor?: (string | null) | User;
  assistantOAuthSessionID?: string | null;
  expiresAt: string;
  revokedAt?: string | null;
  consumedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "retention-settings".
 */
export interface RetentionSetting {
  id: string;
  key: string;
  spamDays: number;
  mediaBinDays: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deletion-tombstones".
 */
export interface DeletionTombstone {
  id: string;
  resourceType: 'application' | 'inquiry' | 'media';
  resourceID: string;
  deletedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "retention-purge-jobs".
 */
export interface RetentionPurgeJob {
  id: string;
  resourceType: 'spam-inquiry' | 'application' | 'media';
  resourceID: string;
  state: 'queued' | 'failed' | 'completed';
  attempts: number;
  lastError?: string | null;
  resumeKey?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "change-sets".
 */
export interface ChangeSet {
  id: string;
  name: string;
  actor?: (string | null) | User;
  state?:
    ('open' | 'submitted' | 'changes-requested' | 'approved' | 'rejected' | 'published' | 'discarded' | 'stale') | null;
  revision?: number | null;
  /**
   * Field-level before and after images captured from draft saves.
   */
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  quality?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  preview?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reviewComments?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  submittedAt?: string | null;
  reviewedAt?: string | null;
  staleAt?: string | null;
  creationRequestKey?: string | null;
  creationRequestHash?: string | null;
  summary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configured-ai-jobs".
 */
export interface ConfiguredAiJob {
  id: string;
  actor: string | User;
  idempotencyKey: string;
  requestDigest: string;
  input: string;
  provider: 'openai' | 'anthropic' | 'google-gemini' | 'openrouter' | 'mistral';
  fallbackProvider?: ('openai' | 'anthropic' | 'google-gemini' | 'openrouter' | 'mistral') | null;
  maxOutputTokens: number;
  configurationSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  state: 'queued' | 'running' | 'completed' | 'manual-review' | 'failed';
  leaseToken?: string | null;
  leaseExpiresAt?: string | null;
  dispatchStartedAt?: string | null;
  result?: string | null;
  resultDigest?: string | null;
  costStatus?: ('actual' | 'reserved') | null;
  usedProvider?: ('openai' | 'anthropic' | 'google-gemini' | 'openrouter' | 'mistral') | null;
  fallbackUsed?: boolean | null;
  failureCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publish-snapshots".
 */
export interface PublishSnapshot {
  id: string;
  contentHash: string;
  changeSet: string | ChangeSet;
  reviewRevision: number;
  changeHash: string;
  manifest:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  themeVersion: string;
  engineVersion: string;
  contractVersion: string;
  approvedBy: string | User;
  baselineSnapshot?: (string | null) | PublishSnapshot;
  baselineSequence: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publish-outbox".
 */
export interface PublishOutbox {
  id: string;
  idempotencyKey: string;
  sequence: number;
  snapshot: string | PublishSnapshot;
  changeSet: string | ChangeSet;
  reviewRevision: number;
  changeHash: string;
  includedChangeKeys:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'pending' | 'processing' | 'failed' | 'completed';
  attempts: number;
  nextAttemptAt?: string | null;
  claimedAt?: string | null;
  leaseToken?: string | null;
  leaseExpiresAt?: string | null;
  completedAt?: string | null;
  completionEvidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errorCode?: string | null;
  correlationID: string;
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scheduled-publications".
 */
export interface ScheduledPublication {
  id: string;
  idempotencyKey: string;
  snapshot: string | PublishSnapshot;
  changeSet: string | ChangeSet;
  scheduledFor: string;
  state: 'scheduled' | 'cancelled' | 'stale' | 'enqueued';
  outbox?: (string | null) | PublishOutbox;
  enqueuedAt?: string | null;
  dispatchReason?: string | null;
  proof:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preview-render-jobs".
 */
export interface PreviewRenderJob {
  id: string;
  changeSet: string | ChangeSet;
  reviewRevision: number;
  changeHash: string;
  includedChangeKeys:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  baselineSnapshot?: (string | null) | PublishSnapshot;
  baselineSequence: number;
  liveSnapshot?: (string | null) | PublishSnapshot;
  liveSequence: number;
  liveManifest:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  proposedManifest:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  liveManifestHash: string;
  proposedManifestHash: string;
  versionPins:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'pending' | 'processing' | 'failed' | 'completed';
  attempts: number;
  nextAttemptAt?: string | null;
  leaseToken?: string | null;
  leaseExpiresAt?: string | null;
  completedAt?: string | null;
  artifactDigest?: string | null;
  errorCode?: string | null;
  renderDiagnostics?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "published-releases".
 */
export interface PublishedRelease {
  id: string;
  outbox: string | PublishOutbox;
  sequence: number;
  snapshot: string | PublishSnapshot;
  activatedAt: string;
  healthEvidence:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  artifact:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'invitations';
        value: string | Invitation;
      } | null)
    | ({
        relationTo: 'auth-sessions';
        value: string | AuthSession;
      } | null)
    | ({
        relationTo: 'auth-transactions';
        value: string | AuthTransaction;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: string | AuditEvent;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'sections';
        value: string | Section;
      } | null)
    | ({
        relationTo: 'assets';
        value: string | Asset;
      } | null)
    | ({
        relationTo: 'asset-file-versions';
        value: string | AssetFileVersion;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'theme-settings';
        value: string | ThemeSetting;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: string | SiteSetting;
      } | null)
    | ({
        relationTo: 'style-guides';
        value: string | StyleGuide;
      } | null)
    | ({
        relationTo: 'integration-configurations';
        value: string | IntegrationConfiguration;
      } | null)
    | ({
        relationTo: 'mcp-privacy-settings';
        value: string | McpPrivacySetting;
      } | null)
    | ({
        relationTo: 'provider-usage-reservations';
        value: string | ProviderUsageReservation;
      } | null)
    | ({
        relationTo: 'mailbox-configurations';
        value: string | MailboxConfiguration;
      } | null)
    | ({
        relationTo: 'mailbox-oauth-transactions';
        value: string | MailboxOauthTransaction;
      } | null)
    | ({
        relationTo: 'mailbox-area-mappings';
        value: string | MailboxAreaMapping;
      } | null)
    | ({
        relationTo: 'mailbox-test-sends';
        value: string | MailboxTestSend;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: string | Inquiry;
      } | null)
    | ({
        relationTo: 'notification-outbox';
        value: string | NotificationOutbox;
      } | null)
    | ({
        relationTo: 'notification-deliveries';
        value: string | NotificationDelivery;
      } | null)
    | ({
        relationTo: 'notification-preferences';
        value: string | NotificationPreference;
      } | null)
    | ({
        relationTo: 'notification-user-preferences';
        value: string | NotificationUserPreference;
      } | null)
    | ({
        relationTo: 'urgent-contacts';
        value: string | UrgentContact;
      } | null)
    | ({
        relationTo: 'mail-conversation-suggestions';
        value: string | MailConversationSuggestion;
      } | null)
    | ({
        relationTo: 'mail-drafts';
        value: string | MailDraft;
      } | null)
    | ({
        relationTo: 'mail-threads';
        value: string | MailThread;
      } | null)
    | ({
        relationTo: 'mail-thread-messages';
        value: string | MailThreadMessage;
      } | null)
    | ({
        relationTo: 'external-replies';
        value: string | ExternalReply;
      } | null)
    | ({
        relationTo: 'mail-authorizations';
        value: string | MailAuthorization;
      } | null)
    | ({
        relationTo: 'applications';
        value: string | Application;
      } | null)
    | ({
        relationTo: 'retention-settings';
        value: string | RetentionSetting;
      } | null)
    | ({
        relationTo: 'deletion-tombstones';
        value: string | DeletionTombstone;
      } | null)
    | ({
        relationTo: 'retention-purge-jobs';
        value: string | RetentionPurgeJob;
      } | null)
    | ({
        relationTo: 'change-sets';
        value: string | ChangeSet;
      } | null)
    | ({
        relationTo: 'configured-ai-jobs';
        value: string | ConfiguredAiJob;
      } | null)
    | ({
        relationTo: 'publish-snapshots';
        value: string | PublishSnapshot;
      } | null)
    | ({
        relationTo: 'publish-outbox';
        value: string | PublishOutbox;
      } | null)
    | ({
        relationTo: 'scheduled-publications';
        value: string | ScheduledPublication;
      } | null)
    | ({
        relationTo: 'preview-render-jobs';
        value: string | PreviewRenderJob;
      } | null)
    | ({
        relationTo: 'published-releases';
        value: string | PublishedRelease;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  roles?: T;
  disabled?: T;
  invitedAt?: T;
  provider?: T;
  providerIssuer?: T;
  providerSubject?: T;
  emergencyTotpSecret?: T;
  emergencyRecoveryHashes?: T;
  emergencyLastCounter?: T;
  emergencyFailedAt?: T;
  emergencyFailedCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations_select".
 */
export interface InvitationsSelect<T extends boolean = true> {
  email?: T;
  provider?: T;
  providerIssuer?: T;
  providerSubject?: T;
  requiredSubject?: T;
  tokenHash?: T;
  roles?: T;
  expiresAt?: T;
  acceptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-sessions_select".
 */
export interface AuthSessionsSelect<T extends boolean = true> {
  tokenHash?: T;
  user?: T;
  authenticatedAt?: T;
  lastSeenAt?: T;
  expiresAt?: T;
  revokedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-transactions_select".
 */
export interface AuthTransactionsSelect<T extends boolean = true> {
  stateHash?: T;
  nonce?: T;
  verifier?: T;
  provider?: T;
  invitation?: T;
  expiresAt?: T;
  consumedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  event?: T;
  user?: T;
  actor?: T;
  detail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sectionId?: T;
  parentId?: T;
  summary?: T;
  template?: T;
  status?: T;
  blocks?: T;
  kicker?: T;
  lede?: T;
  seoDescription?: T;
  noindex?: T;
  publishedAt?: T;
  lastReviewed?: T;
  jobPosting?: T;
  businessCase?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections_select".
 */
export interface SectionsSelect<T extends boolean = true> {
  name?: T;
  summary?: T;
  slug?: T;
  landingPageId?: T;
  allowedTemplates?: T;
  pageIds?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets_select".
 */
export interface AssetsSelect<T extends boolean = true> {
  alt?: T;
  decorative?: T;
  caption?: T;
  credit?: T;
  tags?: T;
  currentFileVersion?: T;
  currentFile?: T;
  deletedAt?: T;
  deleteAfter?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        heroAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        heroWebp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        cardAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        cardWebp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnailAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnailWebp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-file-versions_select".
 */
export interface AssetFileVersionsSelect<T extends boolean = true> {
  parentAsset?: T;
  digest?: T;
  versionKey?: T;
  idempotencyKey?: T;
  originalFilename?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        heroAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        heroWebp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        cardAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        cardWebp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnailAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnailWebp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  status?: T;
  createdBy?: T;
  createdByLabel?: T;
  hitCount?: T;
  lastHitAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings_select".
 */
export interface ThemeSettingsSelect<T extends boolean = true> {
  key?: T;
  selection?: T;
  settings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  key?: T;
  siteName?: T;
  legalName?: T;
  homepageId?: T;
  defaultLocale?: T;
  organizationType?: T;
  logo?: T;
  logos?:
    | T
    | {
        primaryLight?: T;
        primaryDark?: T;
        fullLockupLight?: T;
        fullLockupDark?: T;
        symbolLight?: T;
        symbolDark?: T;
      };
  contactEmail?: T;
  contactPhone?: T;
  seoDescription?: T;
  address?:
    | T
    | {
        streetAddress?: T;
        addressLocality?: T;
        addressRegion?: T;
        postalCode?: T;
        addressCountry?: T;
      };
  linkedIn?: T;
  incident?:
    | T
    | {
        label?: T;
        guidance?: T;
      };
  navigation?: T;
  searchEnabled?: T;
  crawlerPolicy?: T;
  contractVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "style-guides_select".
 */
export interface StyleGuidesSelect<T extends boolean = true> {
  key?: T;
  bannedPhrases?: T;
  preferredTerms?: T;
  canadianSpelling?: T;
  maximumSentenceWords?: T;
  minimumReadingEase?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integration-configurations_select".
 */
export interface IntegrationConfigurationsSelect<T extends boolean = true> {
  provider?: T;
  model?: T;
  fallbackProvider?: T;
  monthlyCapMicroUsd?: T;
  monthlyUsageMicroUsd?: T;
  usageMonth?: T;
  inputMicroUsdPerMillionTokens?: T;
  outputMicroUsdPerMillionTokens?: T;
  pricingSource?: T;
  pricingAsOf?: T;
  encryptedCredential?: T;
  credentialFingerprint?: T;
  health?: T;
  testedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mcp-privacy-settings_select".
 */
export interface McpPrivacySettingsSelect<T extends boolean = true> {
  key?: T;
  hidePhone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provider-usage-reservations_select".
 */
export interface ProviderUsageReservationsSelect<T extends boolean = true> {
  configuration?: T;
  executionKey?: T;
  usageMonth?: T;
  reservedMicroUsd?: T;
  settledMicroUsd?: T;
  state?: T;
  configModel?: T;
  credentialFingerprint?: T;
  inputMicroUsdPerMillionTokens?: T;
  outputMicroUsdPerMillionTokens?: T;
  pricingSource?: T;
  pricingAsOf?: T;
  requestInputTokens?: T;
  maxOutputTokens?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailbox-configurations_select".
 */
export interface MailboxConfigurationsSelect<T extends boolean = true> {
  name?: T;
  provider?: T;
  primaryAddress?: T;
  aliases?: T;
  verifiedAliases?: T;
  host?: T;
  port?: T;
  security?: T;
  username?: T;
  encryptedCredential?: T;
  credentialRevision?: T;
  health?: T;
  testedAt?: T;
  inboundCursor?: T;
  inboundCursorRevision?: T;
  inboundNextAttemptAt?: T;
  inboundFailureCount?: T;
  inboundLastError?: T;
  inboundLastSyncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailbox-oauth-transactions_select".
 */
export interface MailboxOauthTransactionsSelect<T extends boolean = true> {
  provider?: T;
  stateHash?: T;
  sessionHash?: T;
  verifier?: T;
  owner?: T;
  expiresAt?: T;
  consumedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailbox-area-mappings_select".
 */
export interface MailboxAreaMappingsSelect<T extends boolean = true> {
  area?: T;
  mailbox?: T;
  senderAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailbox-test-sends_select".
 */
export interface MailboxTestSendsSelect<T extends boolean = true> {
  requestKey?: T;
  requestHash?: T;
  mailbox?: T;
  senderAddress?: T;
  recipientAddress?: T;
  authorizedBy?: T;
  state?: T;
  providerMessageID?: T;
  failureCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  telephone?: T;
  company?: T;
  message?: T;
  topic?: T;
  sourcePage?: T;
  consentedAt?: T;
  consentBasis?: T;
  idempotencyKey?: T;
  stage?: T;
  spam?: T;
  spamMarkedAt?: T;
  spamPreviousStage?: T;
  urgent?: T;
  notes?: T;
  assignee?: T;
  nextAction?: T;
  nextActionDueAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-outbox_select".
 */
export interface NotificationOutboxSelect<T extends boolean = true> {
  inquiry?: T;
  kind?: T;
  idempotencyKey?: T;
  state?: T;
  payload?: T;
  recipientRules?: T;
  recipients?: T;
  channels?: T;
  sourceType?: T;
  sourceID?: T;
  availableAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-deliveries_select".
 */
export interface NotificationDeliveriesSelect<T extends boolean = true> {
  outbox?: T;
  idempotencyKey?: T;
  recipient?: T;
  state?: T;
  attempts?: T;
  nextAttemptAt?: T;
  leaseToken?: T;
  leaseExpiresAt?: T;
  providerMessageID?: T;
  failureCode?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-preferences_select".
 */
export interface NotificationPreferencesSelect<T extends boolean = true> {
  key?: T;
  events?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-user-preferences_select".
 */
export interface NotificationUserPreferencesSelect<T extends boolean = true> {
  user?: T;
  mutedKinds?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "urgent-contacts_select".
 */
export interface UrgentContactsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  mobile?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail-conversation-suggestions_select".
 */
export interface MailConversationSuggestionsSelect<T extends boolean = true> {
  mailbox?: T;
  provider?: T;
  providerConversationID?: T;
  addressHash?: T;
  target?: T;
  adoptedAt?: T;
  adoptedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail-drafts_select".
 */
export interface MailDraftsSelect<T extends boolean = true> {
  lead?: T;
  application?: T;
  threadID?: T;
  recipient?: T;
  sender?: T;
  subject?: T;
  body?: T;
  attachments?: T;
  attachmentHashes?: T;
  assistantClientIDHash?: T;
  assistantActor?: T;
  assistantOAuthSessionID?: T;
  revision?: T;
  state?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail-threads_select".
 */
export interface MailThreadsSelect<T extends boolean = true> {
  lead?: T;
  application?: T;
  mailbox?: T;
  provider?: T;
  providerConversationID?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail-thread-messages_select".
 */
export interface MailThreadMessagesSelect<T extends boolean = true> {
  thread?: T;
  mailbox?: T;
  lead?: T;
  application?: T;
  providerMessageID?: T;
  rfcMessageID?: T;
  rfcReferences?: T;
  direction?: T;
  sender?: T;
  recipient?: T;
  subject?: T;
  body?: T;
  receivedAt?: T;
  attachmentMetadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-replies_select".
 */
export interface ExternalRepliesSelect<T extends boolean = true> {
  lead?: T;
  sentAt?: T;
  subject?: T;
  summary?: T;
  recordedBy?: T;
  idempotencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail-authorizations_select".
 */
export interface MailAuthorizationsSelect<T extends boolean = true> {
  draft?: T;
  digest?: T;
  draftRevision?: T;
  authorizedBy?: T;
  humanConfirmationSessionID?: T;
  assistantClientIDHash?: T;
  assistantActor?: T;
  assistantOAuthSessionID?: T;
  expiresAt?: T;
  revokedAt?: T;
  consumedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  telephone?: T;
  linkedIn?: T;
  coverLetter?: T;
  consent?: T;
  jobId?: T;
  resumeKey?: T;
  idempotencyKey?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "retention-settings_select".
 */
export interface RetentionSettingsSelect<T extends boolean = true> {
  key?: T;
  spamDays?: T;
  mediaBinDays?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deletion-tombstones_select".
 */
export interface DeletionTombstonesSelect<T extends boolean = true> {
  resourceType?: T;
  resourceID?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "retention-purge-jobs_select".
 */
export interface RetentionPurgeJobsSelect<T extends boolean = true> {
  resourceType?: T;
  resourceID?: T;
  state?: T;
  attempts?: T;
  lastError?: T;
  resumeKey?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "change-sets_select".
 */
export interface ChangeSetsSelect<T extends boolean = true> {
  name?: T;
  actor?: T;
  state?: T;
  revision?: T;
  changes?: T;
  quality?: T;
  preview?: T;
  reviewComments?: T;
  submittedAt?: T;
  reviewedAt?: T;
  staleAt?: T;
  creationRequestKey?: T;
  creationRequestHash?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configured-ai-jobs_select".
 */
export interface ConfiguredAiJobsSelect<T extends boolean = true> {
  actor?: T;
  idempotencyKey?: T;
  requestDigest?: T;
  input?: T;
  provider?: T;
  fallbackProvider?: T;
  maxOutputTokens?: T;
  configurationSnapshot?: T;
  state?: T;
  leaseToken?: T;
  leaseExpiresAt?: T;
  dispatchStartedAt?: T;
  result?: T;
  resultDigest?: T;
  costStatus?: T;
  usedProvider?: T;
  fallbackUsed?: T;
  failureCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publish-snapshots_select".
 */
export interface PublishSnapshotsSelect<T extends boolean = true> {
  contentHash?: T;
  changeSet?: T;
  reviewRevision?: T;
  changeHash?: T;
  manifest?: T;
  themeVersion?: T;
  engineVersion?: T;
  contractVersion?: T;
  approvedBy?: T;
  baselineSnapshot?: T;
  baselineSequence?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publish-outbox_select".
 */
export interface PublishOutboxSelect<T extends boolean = true> {
  idempotencyKey?: T;
  sequence?: T;
  snapshot?: T;
  changeSet?: T;
  reviewRevision?: T;
  changeHash?: T;
  includedChangeKeys?: T;
  status?: T;
  attempts?: T;
  nextAttemptAt?: T;
  claimedAt?: T;
  leaseToken?: T;
  leaseExpiresAt?: T;
  completedAt?: T;
  completionEvidence?: T;
  errorCode?: T;
  correlationID?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scheduled-publications_select".
 */
export interface ScheduledPublicationsSelect<T extends boolean = true> {
  idempotencyKey?: T;
  snapshot?: T;
  changeSet?: T;
  scheduledFor?: T;
  state?: T;
  outbox?: T;
  enqueuedAt?: T;
  dispatchReason?: T;
  proof?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preview-render-jobs_select".
 */
export interface PreviewRenderJobsSelect<T extends boolean = true> {
  changeSet?: T;
  reviewRevision?: T;
  changeHash?: T;
  includedChangeKeys?: T;
  baselineSnapshot?: T;
  baselineSequence?: T;
  liveSnapshot?: T;
  liveSequence?: T;
  liveManifest?: T;
  proposedManifest?: T;
  liveManifestHash?: T;
  proposedManifestHash?: T;
  versionPins?: T;
  status?: T;
  attempts?: T;
  nextAttemptAt?: T;
  leaseToken?: T;
  leaseExpiresAt?: T;
  completedAt?: T;
  artifactDigest?: T;
  errorCode?: T;
  renderDiagnostics?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "published-releases_select".
 */
export interface PublishedReleasesSelect<T extends boolean = true> {
  outbox?: T;
  sequence?: T;
  snapshot?: T;
  activatedAt?: T;
  healthEvidence?: T;
  artifact?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}