/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    invitations: Invitation;
    'auth-sessions': AuthSession;
    'auth-transactions': AuthTransaction;
    'audit-events': AuditEvent;
    pages: Page;
    sections: Section;
    assets: Asset;
    redirects: Redirect;
    inquiries: Inquiry;
    'notification-outbox': NotificationOutbox;
    applications: Application;
    'change-sets': ChangeSet;
    'publish-snapshots': PublishSnapshot;
    'publish-outbox': PublishOutbox;
    'preview-render-jobs': PreviewRenderJob;
    'published-releases': PublishedRelease;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    invitations: InvitationsSelect<false> | InvitationsSelect<true>;
    'auth-sessions': AuthSessionsSelect<false> | AuthSessionsSelect<true>;
    'auth-transactions': AuthTransactionsSelect<false> | AuthTransactionsSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    sections: SectionsSelect<false> | SectionsSelect<true>;
    assets: AssetsSelect<false> | AssetsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'notification-outbox': NotificationOutboxSelect<false> | NotificationOutboxSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'change-sets': ChangeSetsSelect<false> | ChangeSetsSelect<true>;
    'publish-snapshots': PublishSnapshotsSelect<false> | PublishSnapshotsSelect<true>;
    'publish-outbox': PublishOutboxSelect<false> | PublishOutboxSelect<true>;
    'preview-render-jobs': PreviewRenderJobsSelect<false> | PreviewRenderJobsSelect<true>;
    'published-releases': PublishedReleasesSelect<false> | PublishedReleasesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  email: string;
  name: string;
  roles: ('owner' | 'approver' | 'editor' | 'sales' | 'hiring')[];
  disabled?: boolean | null;
  invitedAt?: string | null;
  provider?: ('google' | 'microsoft') | null;
  providerIssuer?: string | null;
  providerSubject?: string | null;
  emergencyTotpSecret?: string | null;
  emergencyRecoveryHashes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  emergencyLastCounter?: number | null;
  emergencyFailedAt?: string | null;
  emergencyFailedCount?: number | null;
  updatedAt: string;
  createdAt: string;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations".
 */
export interface Invitation {
  id: string;
  email: string;
  provider: 'google' | 'microsoft';
  /**
   * Trusted configured issuer for this invite.
   */
  providerIssuer: string;
  providerSubject: string;
  /**
   * Optional prebound verified OIDC subject. Enrollment always requires the one-time invitation.
   */
  requiredSubject?: string | null;
  /**
   * Opaque invite credential hash; its original value is never shown in admin.
   */
  tokenHash: string;
  roles: ('owner' | 'approver' | 'editor' | 'sales' | 'hiring')[];
  expiresAt: string;
  acceptedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-sessions".
 */
export interface AuthSession {
  id: string;
  tokenHash: string;
  user: string | User;
  authenticatedAt: string;
  lastSeenAt: string;
  expiresAt: string;
  revokedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-transactions".
 */
export interface AuthTransaction {
  id: string;
  stateHash: string;
  nonce: string;
  verifier: string;
  provider: 'google' | 'microsoft';
  invitation?: (string | null) | Invitation;
  expiresAt: string;
  consumedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: string;
  event: string;
  user?: (string | null) | User;
  actor?: (string | null) | User;
  detail?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  /**
   * Required content section.
   */
  sectionId: string | Section;
  /**
   * Parent page for tree-oriented navigation.
   */
  parentId?: (string | null) | Page;
  /**
   * Write one or two sentences for listings and editorial context.
   */
  summary: string;
  template: 'landing' | 'standard' | 'listing' | 'pillar' | 'service' | 'article' | 'job';
  status?: ('draft' | 'published' | 'archived') | null;
  blocks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections".
 */
export interface Section {
  id: string;
  name: string;
  summary: string;
  slug: string;
  allowedTemplates: ('landing' | 'standard' | 'listing' | 'pillar' | 'service' | 'article' | 'job')[];
  pageIds?: (string | Page)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets".
 */
export interface Asset {
  id: string;
  alt?: string | null;
  decorative?: boolean | null;
  caption?: string | null;
  credit?: string | null;
  tags?: string[] | null;
  deletedAt?: string | null;
  deleteAfter?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    heroAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    heroWebp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    cardAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    cardWebp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnailAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnailWebp?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  from: string;
  to: string;
  status?: number | null;
  /**
   * Updated by the edge log ingestion adapter.
   */
  hitCount?: number | null;
  lastHitAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: string;
  email: string;
  name?: string | null;
  telephone?: string | null;
  company?: string | null;
  message: string;
  topic: 'general' | 'project' | 'partnership' | 'active-incident';
  sourcePage: string;
  consentedAt: string;
  consentBasis: 'visitor-confirmed' | 'staff-recorded' | 'unknown';
  idempotencyKey: string;
  stage: 'new' | 'qualified' | 'contacted' | 'proposal' | 'won' | 'lost';
  urgent?: boolean | null;
  notes?: string | null;
  assignee?: (string | null) | User;
  nextAction?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-outbox".
 */
export interface NotificationOutbox {
  id: string;
  inquiry: string | Inquiry;
  kind: 'lead-received' | 'urgent-lead-alert';
  idempotencyKey: string;
  state: 'queued' | 'delivered' | 'failed';
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  availableAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: string;
  name: string;
  email: string;
  coverLetter: string;
  consent: boolean;
  jobId: string;
  resumeKey: string;
  idempotencyKey: string;
  status?: ('new' | 'reviewing' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "change-sets".
 */
export interface ChangeSet {
  id: string;
  name: string;
  actor?: (string | null) | User;
  state?:
    ('open' | 'submitted' | 'changes-requested' | 'approved' | 'rejected' | 'published' | 'discarded' | 'stale') | null;
  revision?: number | null;
  /**
   * Field-level before and after images captured from draft saves.
   */
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  quality?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  preview?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reviewComments?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  submittedAt?: string | null;
  reviewedAt?: string | null;
  staleAt?: string | null;
  summary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publish-snapshots".
 */
export interface PublishSnapshot {
  id: string;
  contentHash: string;
  changeSet: string | ChangeSet;
  reviewRevision: number;
  changeHash: string;
  manifest:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  themeVersion: string;
  engineVersion: string;
  contractVersion: string;
  approvedBy: string | User;
  baselineSnapshot?: (string | null) | PublishSnapshot;
  baselineSequence: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publish-outbox".
 */
export interface PublishOutbox {
  id: string;
  idempotencyKey: string;
  sequence: number;
  snapshot: string | PublishSnapshot;
  changeSet: string | ChangeSet;
  reviewRevision: number;
  changeHash: string;
  includedChangeKeys:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'pending' | 'processing' | 'failed' | 'completed';
  attempts: number;
  nextAttemptAt?: string | null;
  claimedAt?: string | null;
  leaseToken?: string | null;
  leaseExpiresAt?: string | null;
  completedAt?: string | null;
  completionEvidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errorCode?: string | null;
  correlationID: string;
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preview-render-jobs".
 */
export interface PreviewRenderJob {
  id: string;
  changeSet: string | ChangeSet;
  reviewRevision: number;
  changeHash: string;
  includedChangeKeys:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  baselineSnapshot?: (string | null) | PublishSnapshot;
  baselineSequence: number;
  liveSnapshot?: (string | null) | PublishSnapshot;
  liveSequence: number;
  liveManifest:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  proposedManifest:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  liveManifestHash: string;
  proposedManifestHash: string;
  versionPins:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'pending' | 'processing' | 'failed' | 'completed';
  attempts: number;
  nextAttemptAt?: string | null;
  leaseToken?: string | null;
  leaseExpiresAt?: string | null;
  completedAt?: string | null;
  artifactDigest?: string | null;
  errorCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "published-releases".
 */
export interface PublishedRelease {
  id: string;
  outbox: string | PublishOutbox;
  sequence: number;
  snapshot: string | PublishSnapshot;
  activatedAt: string;
  healthEvidence:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  artifact:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'invitations';
        value: string | Invitation;
      } | null)
    | ({
        relationTo: 'auth-sessions';
        value: string | AuthSession;
      } | null)
    | ({
        relationTo: 'auth-transactions';
        value: string | AuthTransaction;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: string | AuditEvent;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'sections';
        value: string | Section;
      } | null)
    | ({
        relationTo: 'assets';
        value: string | Asset;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: string | Inquiry;
      } | null)
    | ({
        relationTo: 'notification-outbox';
        value: string | NotificationOutbox;
      } | null)
    | ({
        relationTo: 'applications';
        value: string | Application;
      } | null)
    | ({
        relationTo: 'change-sets';
        value: string | ChangeSet;
      } | null)
    | ({
        relationTo: 'publish-snapshots';
        value: string | PublishSnapshot;
      } | null)
    | ({
        relationTo: 'publish-outbox';
        value: string | PublishOutbox;
      } | null)
    | ({
        relationTo: 'preview-render-jobs';
        value: string | PreviewRenderJob;
      } | null)
    | ({
        relationTo: 'published-releases';
        value: string | PublishedRelease;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  roles?: T;
  disabled?: T;
  invitedAt?: T;
  provider?: T;
  providerIssuer?: T;
  providerSubject?: T;
  emergencyTotpSecret?: T;
  emergencyRecoveryHashes?: T;
  emergencyLastCounter?: T;
  emergencyFailedAt?: T;
  emergencyFailedCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations_select".
 */
export interface InvitationsSelect<T extends boolean = true> {
  email?: T;
  provider?: T;
  providerIssuer?: T;
  providerSubject?: T;
  requiredSubject?: T;
  tokenHash?: T;
  roles?: T;
  expiresAt?: T;
  acceptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-sessions_select".
 */
export interface AuthSessionsSelect<T extends boolean = true> {
  tokenHash?: T;
  user?: T;
  authenticatedAt?: T;
  lastSeenAt?: T;
  expiresAt?: T;
  revokedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-transactions_select".
 */
export interface AuthTransactionsSelect<T extends boolean = true> {
  stateHash?: T;
  nonce?: T;
  verifier?: T;
  provider?: T;
  invitation?: T;
  expiresAt?: T;
  consumedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  event?: T;
  user?: T;
  actor?: T;
  detail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sectionId?: T;
  parentId?: T;
  summary?: T;
  template?: T;
  status?: T;
  blocks?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections_select".
 */
export interface SectionsSelect<T extends boolean = true> {
  name?: T;
  summary?: T;
  slug?: T;
  allowedTemplates?: T;
  pageIds?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets_select".
 */
export interface AssetsSelect<T extends boolean = true> {
  alt?: T;
  decorative?: T;
  caption?: T;
  credit?: T;
  tags?: T;
  deletedAt?: T;
  deleteAfter?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        heroAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        heroWebp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        cardAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        cardWebp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnailAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnailWebp?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  status?: T;
  hitCount?: T;
  lastHitAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  telephone?: T;
  company?: T;
  message?: T;
  topic?: T;
  sourcePage?: T;
  consentedAt?: T;
  consentBasis?: T;
  idempotencyKey?: T;
  stage?: T;
  urgent?: T;
  notes?: T;
  assignee?: T;
  nextAction?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-outbox_select".
 */
export interface NotificationOutboxSelect<T extends boolean = true> {
  inquiry?: T;
  kind?: T;
  idempotencyKey?: T;
  state?: T;
  payload?: T;
  availableAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  coverLetter?: T;
  consent?: T;
  jobId?: T;
  resumeKey?: T;
  idempotencyKey?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "change-sets_select".
 */
export interface ChangeSetsSelect<T extends boolean = true> {
  name?: T;
  actor?: T;
  state?: T;
  revision?: T;
  changes?: T;
  quality?: T;
  preview?: T;
  reviewComments?: T;
  submittedAt?: T;
  reviewedAt?: T;
  staleAt?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publish-snapshots_select".
 */
export interface PublishSnapshotsSelect<T extends boolean = true> {
  contentHash?: T;
  changeSet?: T;
  reviewRevision?: T;
  changeHash?: T;
  manifest?: T;
  themeVersion?: T;
  engineVersion?: T;
  contractVersion?: T;
  approvedBy?: T;
  baselineSnapshot?: T;
  baselineSequence?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publish-outbox_select".
 */
export interface PublishOutboxSelect<T extends boolean = true> {
  idempotencyKey?: T;
  sequence?: T;
  snapshot?: T;
  changeSet?: T;
  reviewRevision?: T;
  changeHash?: T;
  includedChangeKeys?: T;
  status?: T;
  attempts?: T;
  nextAttemptAt?: T;
  claimedAt?: T;
  leaseToken?: T;
  leaseExpiresAt?: T;
  completedAt?: T;
  completionEvidence?: T;
  errorCode?: T;
  correlationID?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preview-render-jobs_select".
 */
export interface PreviewRenderJobsSelect<T extends boolean = true> {
  changeSet?: T;
  reviewRevision?: T;
  changeHash?: T;
  includedChangeKeys?: T;
  baselineSnapshot?: T;
  baselineSequence?: T;
  liveSnapshot?: T;
  liveSequence?: T;
  liveManifest?: T;
  proposedManifest?: T;
  liveManifestHash?: T;
  proposedManifestHash?: T;
  versionPins?: T;
  status?: T;
  attempts?: T;
  nextAttemptAt?: T;
  leaseToken?: T;
  leaseExpiresAt?: T;
  completedAt?: T;
  artifactDigest?: T;
  errorCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "published-releases_select".
 */
export interface PublishedReleasesSelect<T extends boolean = true> {
  outbox?: T;
  sequence?: T;
  snapshot?: T;
  activatedAt?: T;
  healthEvidence?: T;
  artifact?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}