import { getPayload } from 'payload'
import config from '../../../payload.config'
import { freshStaff, hasRole } from '../../../src/access'
import { enqueueConfiguredAIJob } from '../../../src/configured-ai-jobs'
import { serverSessionStrategy } from '../../../src/identity'
import { integrationProviders, type IntegrationProvider } from '../../../src/integrations'
export const dynamic = 'force-dynamic'
const maxBodyBytes = 101_000
const privateJSON = (body: unknown, status = 200) => Response.json(body, { status, headers: { 'Cache-Control': 'no-store' } })
const isProvider = (value: unknown): value is IntegrationProvider => typeof value === 'string' && integrationProviders.includes(value as IntegrationProvider)
const sameOrigin = (request: Request) => { const configured = process.env.PAYLOAD_PUBLIC_SERVER_URL; return Boolean(configured && request.headers.get('origin') === new URL(configured).origin) }
async function owner(request: Request) { const payload = await getPayload({ config }); const authenticated = await serverSessionStrategy.authenticate({ headers: request.headers, payload }); const user = authenticated.user as { id?: string; roles?: string[] } | null; return { payload, user: user && user.id && hasRole(user as never, ['owner']) ? user as { id: string; roles?: string[] } : null } }
async function boundedJSON(request: Request): Promise<Record<string, unknown> | undefined> { const reader = request.body?.getReader(); if (!reader) return undefined; const chunks: Uint8Array[] = []; let size = 0; while (true) { const next = await reader.read(); if (next.done) break; size += next.value.byteLength; if (size > maxBodyBytes) return undefined; chunks.push(next.value) }; const bytes = new Uint8Array(size); let offset = 0; for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength }; try { const parsed: unknown = JSON.parse(new TextDecoder().decode(bytes)); return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed as Record<string, unknown> : undefined } catch { return undefined } }
function jobInput(body: Record<string, unknown>) { const keys = ['provider', 'fallbackProvider', 'input', 'maxOutputTokens', 'idempotencyKey']; if (Object.keys(body).some((key) => !keys.includes(key)) || !isProvider(body.provider) || (body.fallbackProvider !== null && body.fallbackProvider !== undefined && !isProvider(body.fallbackProvider)) || typeof body.input !== 'string' || !body.input.trim() || body.input.length > 100_000 || typeof body.maxOutputTokens !== 'number' || !Number.isSafeInteger(body.maxOutputTokens) || body.maxOutputTokens < 1 || body.maxOutputTokens > 8192 || typeof body.idempotencyKey !== 'string' || !/^[A-Za-z0-9_-]{16,128}$/.test(body.idempotencyKey)) return undefined; return { provider: body.provider, fallbackProvider: body.fallbackProvider ?? null, input: body.input, maxOutputTokens: body.maxOutputTokens, idempotencyKey: body.idempotencyKey } }
export async function GET(request: Request) { const access = await owner(request); if (!access.user) return privateJSON({ error: 'Owner access required.' }, 403); const rows = await access.payload.find({ collection: 'configured-ai-jobs', where: { actor: { equals: access.user.id } }, limit: 100, sort: '-createdAt', depth: 0, overrideAccess: true }); return privateJSON({ jobs: rows.docs.map((row: any) => ({ id: row.id, provider: row.provider, fallbackProvider: row.fallbackProvider ?? null, maxOutputTokens: row.maxOutputTokens, configurationSnapshot: row.configurationSnapshot, state: row.state, resultDigest: row.resultDigest ?? null, costStatus: row.costStatus ?? null, failureCode: row.failureCode ?? null, createdAt: row.createdAt })) }) }
export async function POST(request: Request) { if (!sameOrigin(request)) return privateJSON({ error: 'CSRF origin check failed.' }, 403); try { const access = await owner(request); if (!access.user || !(await freshStaff(['owner'])({ req: { payload: access.payload, user: access.user, headers: request.headers } as never }))) return privateJSON({ error: 'Fresh Owner authentication is required.' }, 403); const body = await boundedJSON(request); const input = body && jobInput(body); if (!input) return privateJSON({ error: 'Invalid job.' }, 400); const result = await enqueueConfiguredAIJob(access.payload, access.user.id, input); return privateJSON({ job: { id: result.job.id, state: result.job.state, created: result.created } }, result.created ? 201 : 200) } catch (error) { return privateJSON({ error: error instanceof Error && error.message === 'IDEMPOTENCY_KEY_REUSED' ? 'Idempotency key conflicts.' : 'Job unavailable.' }, error instanceof Error && error.message === 'IDEMPOTENCY_KEY_REUSED' ? 409 : 400) } }
