import { getPayload } from 'payload'
import config from '../../../payload.config'
import { freshStaff, hasRole } from '../../../src/access'
import { integrationProviders } from '../../../src/integrations'
import { enqueueConfiguredAIJob } from '../../../src/configured-ai-jobs'
import { serverSessionStrategy } from '../../../src/identity'
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}})
const provider=(v:unknown)=>typeof v==='string'&&integrationProviders.includes(v as never)
async function owner(request:Request){const payload=await getPayload({config});const auth=await serverSessionStrategy.authenticate({headers:request.headers,payload});const user=auth.user as {id?:string,roles?:string[]}|null;if(!hasRole(user as never,['owner'])||!user?.id)return;return{payload,user}}
export async function GET(request:Request){const access=await owner(request);if(!access)return json({error:'Owner access required.'},403);const rows=await access.payload.find({collection:'configured-ai-jobs',where:{actor:{equals:access.user.id}},limit:100,sort:'-createdAt',depth:0,overrideAccess:true});return json({jobs:rows.docs.map((row:any)=>({id:row.id,provider:row.provider,fallbackProvider:row.fallbackProvider??null,maxOutputTokens:row.maxOutputTokens,configurationSnapshot:row.configurationSnapshot,state:row.state,resultDigest:row.resultDigest??null,costStatus:row.costStatus??null,failureCode:row.failureCode??null,createdAt:row.createdAt}))})}
export async function POST(request:Request){try{const base=process.env.PAYLOAD_PUBLIC_SERVER_URL;if(!base||request.headers.get('origin')!==new URL(base).origin)return json({error:'CSRF origin check failed.'},403);const access=await owner(request);if(!access||!(await freshStaff(['owner'])({req:{payload:access.payload,user:access.user,headers:request.headers}as never})))return json({error:'Fresh Owner authentication is required.'},403);const body=await request.json() as Record<string,unknown>;const keys=['provider','fallbackProvider','input','maxOutputTokens','idempotencyKey'];if(Object.keys(body).some(key=>!keys.includes(key))||!provider(body.provider)||(body.fallbackProvider!==null&&body.fallbackProvider!==undefined&&!provider(body.fallbackProvider))||typeof body.input!=='string'||body.input.length<1||body.input.length>100000||!Number.isSafeInteger(body.maxOutputTokens)||body.maxOutputTokens<1||body.maxOutputTokens>8192||typeof body.idempotencyKey!=='string'||!/^[A-Za-z0-9_-]{16,128}$/.test(body.idempotencyKey))return json({error:'Invalid job.'},400);const result=await enqueueConfiguredAIJob(access.payload,access.user.id,{provider:body.provider,fallbackProvider:body.fallbackProvider??null,input:body.input,maxOutputTokens:body.maxOutputTokens,idempotencyKey:body.idempotencyKey});return json({job:{id:result.job.id,state:result.job.state,created:result.created}},result.created?201:200)}catch(error){return json({error:error instanceof Error&&error.message==='IDEMPOTENCY_KEY_REUSED'?'Idempotency key conflicts.':'Job unavailable.'},error instanceof Error&&error.message==='IDEMPOTENCY_KEY_REUSED'?409:400)}}
