'use client'
import { useCallback, useEffect, useRef, useState } from 'react'
import styles from './users-workspace.module.css'
const roleOptions = ['owner', 'approver', 'editor', 'sales', 'hiring'] as const
type Role = typeof roleOptions[number]
type User = { id: string; name: string; email: string; roles: Role[]; provider: string | null; disabled: boolean; lastSignIn: string | null }
type Invitation = { id: string; email: string; provider: string; roles: Role[]; expiresAt: string }
type Data = { users: User[]; invitations: Invitation[]; providers: { google: boolean; microsoft: boolean }; truncated: boolean }
const date = (value: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Never'
const title = (value: string) => value.charAt(0).toUpperCase() + value.slice(1)
export function UsersWorkspace() {
  const [data, setData] = useState<Data | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [editing, setEditing] = useState<User | null>(null), [inviteURL, setInviteURL] = useState('')
  const inviteDialog = useRef<HTMLDialogElement>(null), editDialog = useRef<HTMLDialogElement>(null)
  const load = useCallback(async () => { setError(''); try { const response = await fetch('/api/users/workspace', { cache: 'no-store' }); const value = await response.json(); if (!response.ok) throw new Error(value.error); setData(value) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Users could not be loaded.') } }, [])
  useEffect(() => { void load() }, [load])
  const post = async (body: unknown) => { setBusy(true); setError(''); try { const response = await fetch('/api/users/workspace', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const value = await response.json(); if (!response.ok) throw new Error(value.error); await load(); return value } catch (cause) { setError(cause instanceof Error ? cause.message : 'The request failed.'); return null } finally { setBusy(false) } }
  const submitInvite = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const result = await post({ action: 'invite', email: form.get('email'), provider: form.get('provider'), roles: form.getAll('roles') }); if (result) setInviteURL(result.inviteURL) }
  const submitEdit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editing) return; const form = new FormData(event.currentTarget); const disabled = form.get('disabled') === 'on'; if (disabled && !editing.disabled && !window.confirm(`Disable access for ${editing.name}? Their active sessions will end.`)) return; const result = await post({ action: 'update', id: editing.id, name: form.get('name'), roles: form.getAll('roles'), disabled }); if (result) { editDialog.current?.close(); setEditing(null) } }
  const openEdit = (user: User) => { setEditing(user); requestAnimationFrame(() => editDialog.current?.showModal()) }
  return <main className={styles.main} data-users-workspace aria-busy={!data && !error}>
    <section className={styles.card} data-users-card><header><div><h1>People with access</h1><p>Invite only. People sign in with a configured provider and the account must match the invited email.</p></div><button data-users-primary type="button" onClick={() => { setInviteURL(''); inviteDialog.current?.showModal() }}>+ Invite person</button></header>
      {error && <div className={styles.error} role="alert">{error} <button type="button" onClick={() => void load()}>Try again</button></div>}
      {data && <div className={styles.tableWrap}><table><thead><tr><th>Person</th><th>Roles</th><th>Sign-in</th><th>Last sign-in</th><th><span className={styles.sr}>Actions</span></th></tr></thead><tbody>{data.users.map(user => <tr key={user.id} data-user-row><td><strong>{user.name}</strong><small>{user.email}</small>{user.disabled && <span className={styles.badge}>Disabled</span>}</td><td>{user.roles.map(role => <span className={styles.role} key={role}>{title(role)}</span>)}</td><td>{user.provider ? title(user.provider) : 'Not configured'}</td><td>{date(user.lastSignIn)}</td><td><button type="button" onClick={() => openEdit(user)} aria-label={`Edit ${user.name}`}>Edit</button></td></tr>)}</tbody></table></div>}
      {data?.invitations.length ? <section className={styles.pending}><h2>Pending invitations</h2>{data.invitations.map(invite => <div key={invite.id}><span><strong>{invite.email}</strong><small>{invite.roles.map(title).join(', ')} · {title(invite.provider)}</small></span><time dateTime={invite.expiresAt}>Expires {date(invite.expiresAt)}</time></div>)}</section> : null}
    </section>
    <section className={styles.glossary} aria-labelledby="role-guide"><h2 id="role-guide">Roles</h2><dl><div><dt>Owner</dt><dd>Full administration, access and publishing control.</dd></div><div><dt>Approver</dt><dd>Reviews and approves editorial changes.</dd></div><div><dt>Editor</dt><dd>Creates and updates site content and media.</dd></div><div><dt>Sales</dt><dd>Works with enquiries and lead records.</dd></div><div><dt>Hiring</dt><dd>Reviews job applications and candidate records.</dd></div></dl></section>
    <dialog ref={inviteDialog} className={styles.dialog} onClose={() => setInviteURL('')} aria-labelledby="invite-title"><form method="dialog" className={styles.close}><button aria-label="Close invitation">×</button></form><h2 id="invite-title">Invite a person</h2>{error && <p role="alert" className={styles.error}>{error}</p>}{inviteURL ? <div className={styles.inviteResult}><p>Share this one-time link securely. It expires in 24 hours.</p><input aria-label="Invitation link" readOnly value={inviteURL} /><button type="button" onClick={() => void navigator.clipboard.writeText(inviteURL)}>Copy link</button></div> : <form onSubmit={submitInvite}><label>Email<input name="email" type="email" required autoFocus /></label><label>Sign-in provider<select name="provider" required defaultValue=""><option value="" disabled>Choose provider</option>{data?.providers.google && <option value="google">Google</option>}{data?.providers.microsoft && <option value="microsoft">Microsoft</option>}</select></label><fieldset><legend>Roles</legend>{roleOptions.map(role => <label key={role}><input type="checkbox" name="roles" value={role} required={false} /> {title(role)}</label>)}</fieldset>{data && !data.providers.google && !data.providers.microsoft && <p role="status">Configure Google or Microsoft sign-in before inviting users.</p>}<button data-users-primary disabled={busy || (!data?.providers.google && !data?.providers.microsoft)}>Create invitation</button></form>}</dialog>
    <dialog ref={editDialog} className={styles.dialog} onClose={() => setEditing(null)} aria-labelledby="edit-title"><form method="dialog" className={styles.close}><button aria-label="Close user editor">×</button></form>{editing && <form onSubmit={submitEdit}><h2 id="edit-title">Edit user</h2>{error && <p role="alert" className={styles.error}>{error}</p>}<p>{editing.email}</p><label>Name<input name="name" required maxLength={160} defaultValue={editing.name} autoFocus /></label><fieldset><legend>Roles</legend>{roleOptions.map(role => <label key={role}><input type="checkbox" name="roles" value={role} defaultChecked={editing.roles.includes(role)} /> {title(role)}</label>)}</fieldset><label className={styles.disable}><input type="checkbox" name="disabled" defaultChecked={editing.disabled} /> Disable access</label><button data-users-primary disabled={busy}>Save user</button></form>}</dialog>
  </main>
}
