import { randomUUID } from 'node:crypto'
import { mkdtempSync,rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterAll,beforeAll,describe,expect,it } from 'vitest'
import { neutralFixture } from '@site-engine/contract/fixtures'
import { getPayload } from 'payload'
import { buildCandidate,canonicalHash } from '../src/publishing'
import { cookieName,hashOpaqueToken,newOpaqueToken,SESSION_COOKIE } from '../src/identity'
const directory=mkdtempSync(join(tmpdir(),'site-engine-change-log-'));process.env.DATABASE_URI=`file:${join(directory,'cms.sqlite')}`;process.env.PAYLOAD_SECRET='synthetic-change-log-secret-that-is-long-enough';process.env.PAYLOAD_PUBLIC_SERVER_URL='http://cms.test'
const {default:config}=await import('../payload.config.js');const service=await import('../src/change-log.js');let payload:any,owner:any
beforeAll(async()=>{payload=await getPayload({config});owner=await payload.create({collection:'users',data:{email:'owner@example.test',name:'Change Owner',roles:['owner']},overrideAccess:true})});afterAll(async()=>{await payload.destroy();rmSync(directory,{recursive:true,force:true})})
async function release(sequence:number,manifest:any,name:string,beforeManifest:any=manifest,changes:any[]=[{collection:'pages',id:manifest.pages[0].id,before:beforeManifest.pages[0]!,after:manifest.pages[0]!,beforeHash:canonicalHash(beforeManifest.pages[0]!),afterHash:canonicalHash(manifest.pages[0]!)}]){const set=await payload.create({collection:'change-sets',data:{name,actor:owner.id,state:'published',revision:1,changes},overrideAccess:true,context:{editorialInternal:true}});const snapshot=await payload.create({collection:'publish-snapshots',data:{contentHash:canonicalHash(manifest),changeSet:set.id,reviewRevision:1,changeHash:canonicalHash(set.changes),manifest,themeVersion:'1.0.0',engineVersion:'test',contractVersion:manifest.settings.contractVersion,approvedBy:owner.id,baselineSequence:Math.max(0,sequence-1)},overrideAccess:true,context:{editorialInternal:true}});const outbox=await payload.create({collection:'publish-outbox',data:{idempotencyKey:randomUUID(),sequence,snapshot:snapshot.id,changeSet:set.id,reviewRevision:1,changeHash:canonicalHash(set.changes),includedChangeKeys:[`pages:${manifest.pages[0].id}`],status:'completed',attempts:1,correlationID:randomUUID()},overrideAccess:true,context:{editorialInternal:true}});const published=await payload.create({collection:'published-releases',data:{outbox:outbox.id,sequence,snapshot:snapshot.id,activatedAt:new Date(Date.now()+sequence).toISOString(),healthEvidence:{checks:[]},artifact:{digest:'a'.repeat(64),sourceContentHash:snapshot.contentHash,themeVersion:'1.0.0',engineVersion:'test',contractVersion:manifest.settings.contractVersion,checks:[]}},overrideAccess:true,context:{editorialInternal:true}});const audit=await payload.create({collection:'audit-events',data:{event:'editorial.change_set_approved',actor:owner.id,detail:{changeSet:set.id,snapshot:snapshot.id}},overrideAccess:true});return{set,published,audit}}
describe('reviewed Change log rollback',()=>{it('projects safe reviewed diffs and enables rollback only for the latest immutable release',async()=>{const prior=structuredClone(neutralFixture);const current=structuredClone(prior);current.pages[0]!.summary='Current release summary';const first=await release(1,prior,'First release');const second=await release(2,current,'Current release',prior);const events=await payload.find({collection:'audit-events',sort:'createdAt',depth:1,overrideAccess:true});const rows=await service.projectChangeLog(payload,events.docs);expect(rows.find((row:any)=>row.id===String(first.audit.id))!.rollback).toMatchObject({sequence:1,enabled:false});expect(rows.find((row:any)=>row.id===String(second.audit.id))).toMatchObject({title:'Current release approved for publishing',status:'Complete',diff:expect.objectContaining({label:'Reviewed changes'}),rollback:expect.objectContaining({sequence:2,enabled:true})});expect(JSON.stringify(rows)).not.toContain('token')
const token=newOpaqueToken(),now=new Date().toISOString();await payload.create({collection:'auth-sessions',data:{tokenHash:hashOpaqueToken(token),user:owner.id,authenticatedAt:now,lastSeenAt:now,expiresAt:new Date(Date.now()+60_000).toISOString()},overrideAccess:true});const set=await service.prepareReviewedRollback(payload,owner,new Headers({cookie:`${cookieName(SESSION_COOKIE)}=${token}`}),String(second.published.id));expect(set).toMatchObject({name:'Rollback release #2',state:'open'});const stored=await payload.findByID({collection:'change-sets',id:set.id,overrideAccess:true});const changes=stored.changes as any[];const candidate=buildCandidate(current,changes,changes.map(change=>`${change.collection}:${change.id}`),{themeVersion:'1.0.0',engineVersion:'test',contractVersion:current.settings.contractVersion});expect(candidate.pages[0]!.summary).toBe(prior.pages[0]!.summary);expect(current.pages[0]!.summary).toBe('Current release summary')})

it('keeps automatic rollback unavailable when a release added a page that snapshot reconciliation cannot remove',async()=>{const previous=structuredClone(neutralFixture),added=structuredClone(previous),page={...structuredClone(added.pages[0]!),id:randomUUID(),slug:'added-page',title:'Added page'};added.pages.push(page);added.settings.sections[0]!.pageIds.push(page.id);const item=await release(3,added,'Release with an added page',previous,[{collection:'pages',id:page.id,before:null,after:page,beforeHash:null,afterHash:canonicalHash(page)}]);const rows=await service.projectChangeLog(payload,(await payload.find({collection:'audit-events',where:{id:{equals:item.audit.id}},depth:1,overrideAccess:true})).docs);expect(rows[0]!.rollback).toMatchObject({enabled:false});expect(rows[0]!.rollback!.note).toContain('manual reviewed change');const token=newOpaqueToken(),now=new Date().toISOString();await payload.create({collection:'auth-sessions',data:{tokenHash:hashOpaqueToken(token),user:owner.id,authenticatedAt:now,lastSeenAt:now,expiresAt:new Date(Date.now()+60_000).toISOString()},overrideAccess:true});await expect(service.prepareReviewedRollback(payload,owner,new Headers({cookie:`${cookieName(SESSION_COOKIE)}=${token}`}),String(item.published.id))).rejects.toThrow('manual reviewed change')})
it('rejects preparing an older release or using a stale Owner session',async()=>{const releases=await payload.find({collection:'published-releases',sort:'sequence',overrideAccess:true});const oldToken=newOpaqueToken(),old=new Date(Date.now()-16*60_000).toISOString();await payload.create({collection:'auth-sessions',data:{tokenHash:hashOpaqueToken(oldToken),user:owner.id,authenticatedAt:old,lastSeenAt:new Date().toISOString(),expiresAt:new Date(Date.now()+60_000).toISOString()},overrideAccess:true});await expect(service.prepareReviewedRollback(payload,owner,new Headers({cookie:`${cookieName(SESSION_COOKIE)}=${oldToken}`}),String(releases.docs[0].id))).rejects.toThrow('Fresh Owner')})})
