import { randomUUID } from 'node:crypto'
import { mkdtempSync,rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterAll,beforeAll,describe,expect,it } from 'vitest'
import { neutralFixture } from '@site-engine/contract/fixtures'
import { getPayload } from 'payload'
import { buildCandidate,canonicalHash } from '../src/publishing'
import { cookieName,hashOpaqueToken,newOpaqueToken,SESSION_COOKIE } from '../src/identity'
const directory=mkdtempSync(join(tmpdir(),'site-engine-change-log-'));process.env.DATABASE_URI=`file:${join(directory,'cms.sqlite')}`;process.env.PAYLOAD_SECRET='synthetic-change-log-secret-that-is-long-enough';process.env.PAYLOAD_PUBLIC_SERVER_URL='http://cms.test'
const {default:config}=await import('../payload.config.js');const service=await import('../src/change-log.js');let payload:any,owner:any
beforeAll(async()=>{payload=await getPayload({config});owner=await payload.create({collection:'users',data:{email:'owner@example.test',name:'Change Owner',roles:['owner']},overrideAccess:true})});afterAll(async()=>{await payload.destroy();rmSync(directory,{recursive:true,force:true})})
async function seedDrafts(manifest:any){for(const section of manifest.settings.sections){const found=await payload.find({collection:'sections',where:{id:{equals:section.id}},limit:1,overrideAccess:true});if(!found.docs.length)await payload.create({collection:'sections',data:{...section,pageIds:[],landingPageId:undefined},overrideAccess:true,context:{editorialInternal:true}})}for(const page of manifest.pages){const found=await payload.find({collection:'pages',where:{id:{equals:page.id}},limit:1,overrideAccess:true});if(found.docs.length)await payload.update({collection:'pages',id:page.id,data:{...page,status:'draft'},draft:true,overrideAccess:true,context:{editorialInternal:true}});else await payload.create({collection:'pages',data:{...page,status:'draft'},draft:true,overrideAccess:true,context:{editorialInternal:true}})}}
async function release(sequence:number,manifest:any,name:string,beforeManifest:any=manifest,changes:any[]=[{collection:'pages',id:manifest.pages[0].id,before:beforeManifest.pages[0]!,after:manifest.pages[0]!,beforeHash:canonicalHash(beforeManifest.pages[0]!),afterHash:canonicalHash(manifest.pages[0]!)}]){const set=await payload.create({collection:'change-sets',data:{name,actor:owner.id,state:'published',revision:1,changes},overrideAccess:true,context:{editorialInternal:true}});const snapshot=await payload.create({collection:'publish-snapshots',data:{contentHash:canonicalHash(manifest),changeSet:set.id,reviewRevision:1,changeHash:canonicalHash(set.changes),manifest,themeVersion:'1.0.0',engineVersion:'test',contractVersion:manifest.settings.contractVersion,approvedBy:owner.id,baselineSequence:Math.max(0,sequence-1)},overrideAccess:true,context:{editorialInternal:true}});const outbox=await payload.create({collection:'publish-outbox',data:{idempotencyKey:randomUUID(),sequence,snapshot:snapshot.id,changeSet:set.id,reviewRevision:1,changeHash:canonicalHash(set.changes),includedChangeKeys:changes.map(change=>`${change.collection}:${change.id}`),status:'completed',attempts:1,correlationID:randomUUID()},overrideAccess:true,context:{editorialInternal:true}});const published=await payload.create({collection:'published-releases',data:{outbox:outbox.id,sequence,snapshot:snapshot.id,activatedAt:new Date(Date.now()+sequence).toISOString(),healthEvidence:{checks:[]},artifact:{digest:'a'.repeat(64),sourceContentHash:snapshot.contentHash,themeVersion:'1.0.0',engineVersion:'test',contractVersion:manifest.settings.contractVersion,checks:[]}},overrideAccess:true,context:{editorialInternal:true}});const audit=await payload.create({collection:'audit-events',data:{event:'editorial.change_set_approved',actor:owner.id,detail:{changeSet:set.id,snapshot:snapshot.id}},overrideAccess:true});return{set,published,audit}}
describe('reviewed Change log rollback',()=>{it('projects safe reviewed diffs and enables rollback only for the latest immutable release',async()=>{const prior=structuredClone(neutralFixture);const current=structuredClone(prior);current.pages[0]!.summary='Current release summary';await seedDrafts(current);const first=await release(1,prior,'First release');const second=await release(2,current,'Current release',prior);const events=await payload.find({collection:'audit-events',sort:'createdAt',depth:1,overrideAccess:true});const rows=await service.projectChangeLog(payload,events.docs);expect(rows.find((row:any)=>row.id===String(first.audit.id))!.rollback).toMatchObject({sequence:1,enabled:false});expect(rows.find((row:any)=>row.id===String(second.audit.id))).toMatchObject({title:'Current release approved for publishing',status:'Complete',diff:expect.objectContaining({label:'Reviewed changes'}),rollback:expect.objectContaining({sequence:2,enabled:true})});expect(JSON.stringify(rows)).not.toContain('token');expect(rows.find((row:any)=>row.id===String(second.audit.id))!.diff!.entries).toContainEqual(expect.objectContaining({field:'Summary',before:prior.pages[0]!.summary,after:'Current release summary'}))
const token=newOpaqueToken(),now=new Date().toISOString();await payload.create({collection:'auth-sessions',data:{tokenHash:hashOpaqueToken(token),user:owner.id,authenticatedAt:now,lastSeenAt:now,expiresAt:new Date(Date.now()+60_000).toISOString()},overrideAccess:true});const set=await service.prepareReviewedRollback(payload,owner,new Headers({cookie:`${cookieName(SESSION_COOKIE)}=${token}`}),String(second.published.id));expect(set).toMatchObject({name:'Rollback release #2',state:'open'});const stored=await payload.findByID({collection:'change-sets',id:set.id,overrideAccess:true});const changes=stored.changes as any[];const candidate=buildCandidate(current,changes,changes.map(change=>`${change.collection}:${change.id}`),{themeVersion:'1.0.0',engineVersion:'test',contractVersion:current.settings.contractVersion});expect(candidate.pages[0]!.summary).toBe(prior.pages[0]!.summary);expect(current.pages[0]!.summary).toBe('Current release summary')})

it('rejects preparing an older release or using a stale Owner session',async()=>{const releases=await payload.find({collection:'published-releases',sort:'sequence',overrideAccess:true});const oldToken=newOpaqueToken(),old=new Date(Date.now()-16*60_000).toISOString();await payload.create({collection:'auth-sessions',data:{tokenHash:hashOpaqueToken(oldToken),user:owner.id,authenticatedAt:old,lastSeenAt:new Date().toISOString(),expiresAt:new Date(Date.now()+60_000).toISOString()},overrideAccess:true});await expect(service.prepareReviewedRollback(payload,owner,new Headers({cookie:`${cookieName(SESSION_COOKIE)}=${oldToken}`}),String(releases.docs[0].id))).rejects.toThrow('Fresh Owner')})})


describe('change-log source, category and page filters', () => {
  it('keeps displayed source categories disjoint and includes category aliases', async () => {
    const { changeLogFilters } = await import('../src/change-log-query')
    for (const event of ['mcp.filter-proof', 'ai.filter-proof', 'identity.filter-proof', 'inquiry.filter-proof', 'block_gallery.filter-proof', 'theme.filter-proof']) {
      await payload.create({ collection: 'audit-events', data: { event, actor: owner.id, detail: {} }, overrideAccess: true })
    }
    await payload.create({ collection: 'audit-events', data: { event: 'system.filter-proof', detail: {} }, overrideAccess: true })
    const events = async (query: { source?: string; type?: string }) => (await payload.find({ collection: 'audit-events', where: { and: [{ event: { contains: 'filter-proof' } }, ...await changeLogFilters(payload, query)] }, limit: 100, overrideAccess: true })).docs.map((item: any) => item.event)
    expect(await events({ source: 'assistant' })).toEqual(expect.arrayContaining(['mcp.filter-proof', 'ai.filter-proof']))
    expect(await events({ source: 'person' })).not.toEqual(expect.arrayContaining(['mcp.filter-proof']))
    expect(await events({ source: 'person' })).not.toEqual(expect.arrayContaining(['ai.filter-proof']))
    expect(await events({ source: 'system' })).toEqual(['system.filter-proof'])
    expect(await events({ type: 'lead' })).toEqual(['inquiry.filter-proof'])
    expect(await events({ type: 'media' })).toEqual(['block_gallery.filter-proof'])
    expect(await events({ type: 'site' })).toEqual(['theme.filter-proof'])
  })
  it('finds reviewed approvals by the captured page even when the audit event only stores the change set', async () => {
    const { changeLogFilters } = await import('../src/change-log-query')
    const result = await payload.find({ collection: 'audit-events', where: { and: [{ event: { equals: 'editorial.change_set_approved' } }, ...await changeLogFilters(payload, { target: neutralFixture.pages[0]!.id })] }, limit: 100, overrideAccess: true })
    expect(result.docs.length).toBeGreaterThanOrEqual(2)
  })
  it('shows actual bounded content changes while excluding secret fields', async () => {
    const before = structuredClone(neutralFixture.pages[0]!)
    const set = await payload.create({ collection: 'change-sets', data: { name: 'Sensitive diff fixture', actor: owner.id, state: 'open', revision: 1, changes: [{ collection: 'pages', id: before.id, before: { ...before, credential: 'old-secret-value' }, after: { ...before, title: 'Revised readable title', credential: 'new-secret-value' } }] }, overrideAccess: true, context: { editorialInternal: true } })
    const rows = await service.projectChangeLog(payload, [{ id: 'synthetic-event', event: 'editorial.change_captured', createdAt: new Date().toISOString(), actor: owner.id, detail: { changeSet: set.id } }])
    expect(rows[0].diff!.entries).toContainEqual(expect.objectContaining({ field: 'Title', before: before.title, after: 'Revised readable title' }))
    expect(JSON.stringify(rows)).not.toContain('secret-value')
  })
})
