import { afterAll, beforeAll, expect, test } from 'vitest'
import { getPayload } from 'payload'
import { join } from 'node:path'
import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { createHash, randomUUID } from 'node:crypto'
const directory=mkdtempSync(join(tmpdir(),'mail-suggestions-'));process.env.DATABASE_URI=`file:${join(directory,'cms.sqlite')}`;process.env.PAYLOAD_SECRET='mail-suggestions-test-secret-long-enough'
const { default: config }=await import('../payload.config.js'); const { adoptMailConversationSuggestion }=await import('../src/mail-conversation-suggestions.js'); let payload:any
const hash=(value:string)=>createHash('sha256').update(value.toLowerCase()).digest('hex')
beforeAll(async()=>{payload=await getPayload({config})});afterAll(async()=>{await payload?.destroy();rmSync(directory,{recursive:true,force:true})})
test('explicit adoption is record-scoped, concurrent-safe, and never imports unmatched content',async()=>{const owner=await payload.create({collection:'users',data:{email:'owner@example.test',name:'Owner',roles:['owner']},overrideAccess:true});const mailbox=await payload.create({collection:'mailbox-configurations',data:{name:'Mailbox',provider:'google',host:'mail.example.test',port:587,security:'starttls',username:'u',primaryAddress:'staff@example.test',aliases:[],verifiedAliases:[],health:'connected',encryptedCredential:'x',credentialRevision:'v1'},overrideAccess:true,context:{mailboxInternal:true}});await payload.create({collection:'mailbox-area-mappings',data:{area:'leads',mailbox:mailbox.id,senderAddress:'staff@example.test'},overrideAccess:true,context:{mailboxInternal:true}});const lead=await payload.create({collection:'inquiries',data:{email:'visitor@example.test',message:'lead',topic:'general',sourcePage:'/',consentedAt:new Date().toISOString(),consentBasis:'staff-recorded',idempotencyKey:randomUUID(),stage:'new'},overrideAccess:true});const other=await payload.create({collection:'inquiries',data:{email:'other@example.test',message:'other',topic:'general',sourcePage:'/',consentedAt:new Date().toISOString(),consentBasis:'staff-recorded',idempotencyKey:randomUUID(),stage:'new'},overrideAccess:true});const suggestion=await payload.create({collection:'mail-conversation-suggestions',data:{mailbox:mailbox.id,provider:'google',providerConversationID:'unmatched-thread',addressHash:hash(lead.email),target:'lead'},overrideAccess:true});await expect(adoptMailConversationSuggestion(payload,{suggestionID:suggestion.id,target:'lead',targetID:other.id,actor:owner.id})).rejects.toThrow('suggestion_not_usable');const adopted=await Promise.all([adoptMailConversationSuggestion(payload,{suggestionID:suggestion.id,target:'lead',targetID:lead.id,actor:owner.id}),adoptMailConversationSuggestion(payload,{suggestionID:suggestion.id,target:'lead',targetID:lead.id,actor:owner.id})]);expect(adopted[0].id).toBe(adopted[1].id);expect(await payload.find({collection:'mail-threads',where:{providerConversationID:{equals:'unmatched-thread'}},limit:10,overrideAccess:true})).toMatchObject({totalDocs:1});expect(await payload.find({collection:'mail-thread-messages',where:{thread:{equals:adopted[0].id}},limit:10,overrideAccess:true})).toMatchObject({totalDocs:0})})
