import { randomUUID } from 'node:crypto'
import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { neutralFixture } from '@site-engine/contract/fixtures'
import { getPayload } from 'payload'
import { canonicalHash } from '../src/publishing'
import { cookieName, hashOpaqueToken, newOpaqueToken, SESSION_COOKIE } from '../src/identity'

const directory=mkdtempSync(join(tmpdir(),'site-engine-reviewed-rollback-'));process.env.DATABASE_URI=`file:${join(directory,'cms.sqlite')}`;process.env.PAYLOAD_SECRET='reviewed-rollback-secret-that-is-long-enough';process.env.PAYLOAD_PUBLIC_SERVER_URL='http://cms.test'
const {default:config}=await import('../payload.config.js');const rollback=await import('../src/change-log.js');let payload:any,owner:any
beforeAll(async()=>{payload=await getPayload({config});owner=await payload.create({collection:'users',data:{email:'rollback-owner@example.test',roles:['owner']},overrideAccess:true})});afterAll(async()=>{await payload.destroy();rmSync(directory,{recursive:true,force:true})})
async function auth(){const token=newOpaqueToken(),now=new Date().toISOString();await payload.create({collection:'auth-sessions',data:{tokenHash:hashOpaqueToken(token),user:owner.id,authenticatedAt:now,lastSeenAt:now,expiresAt:new Date(Date.now()+60_000).toISOString()},overrideAccess:true});return new Headers({cookie:`${cookieName(SESSION_COOKIE)}=${token}`})}
async function release(sequence:number,manifest:any,changes:any[]){const set=await payload.create({collection:'change-sets',data:{name:`Release ${sequence}`,actor:owner.id,state:'published',revision:1,changes},overrideAccess:true,context:{editorialInternal:true}});const snap=await payload.create({collection:'publish-snapshots',data:{contentHash:canonicalHash(manifest),changeSet:set.id,reviewRevision:1,changeHash:canonicalHash(changes),manifest,themeVersion:'test',engineVersion:'test',contractVersion:manifest.settings.contractVersion,approvedBy:owner.id,baselineSequence:sequence-1},overrideAccess:true,context:{editorialInternal:true}});const out=await payload.create({collection:'publish-outbox',data:{idempotencyKey:randomUUID(),sequence,snapshot:snap.id,changeSet:set.id,reviewRevision:1,changeHash:canonicalHash(changes),includedChangeKeys:changes.map(c=>`${c.collection}:${c.id}`),status:'completed',attempts:1,correlationID:randomUUID()},overrideAccess:true,context:{editorialInternal:true}});return payload.create({collection:'published-releases',data:{outbox:out.id,sequence,snapshot:snap.id,activatedAt:new Date().toISOString(),healthEvidence:{checks:[]},artifact:{digest:'a'.repeat(64),sourceContentHash:snap.contentHash,themeVersion:'test',engineVersion:'test',contractVersion:manifest.settings.contractVersion,checks:[]}},overrideAccess:true,context:{editorialInternal:true}})}
describe('reviewed rollback selection',()=>{it('rejects excluded keys and leaves rollback reviewable',async()=>{const before=structuredClone(neutralFixture),after=structuredClone(before);after.pages[0]!.summary='new';const change={collection:'pages',id:after.pages[0]!.id,before:before.pages[0],after:after.pages[0]};await release(1,before,[]);const current=await release(2,after,[change]);await expect(rollback.prepareReviewedRollback(payload,owner,await auth(),String(current.id),{mode:'change',changeKeys:['pages:not-in-release']})).rejects.toThrow('not included')})})
