import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest'
import { getPayload } from 'payload'
import { hashOpaqueToken } from '../src/identity'
const directory=mkdtempSync(join(tmpdir(),'site-engine-users-account-'));process.env.DATABASE_URI=`file:${join(directory,'cms.sqlite')}`;process.env.PAYLOAD_SECRET='synthetic-user-management-secret-that-is-long-enough';process.env.PAYLOAD_PUBLIC_SERVER_URL='http://cms.example.test';process.env.EMERGENCY_TOTP_ENCRYPTION_KEY=Buffer.alloc(32, 11).toString('base64url')
const {default:config}=await import('../payload.config.js');const service=await import('../src/user-management.js');let payload:any;let owner:any
beforeAll(async()=>{payload=await getPayload({config})});beforeEach(async()=>{for(const table of ['audit_events','auth_sessions','invitations','users'])await payload.db.client.execute(`DELETE FROM ${table}`);owner=await payload.create({collection:'users',data:{email:'owner@example.test',name:'Owner',roles:['owner']},overrideAccess:true})});afterAll(async()=>{await payload.destroy();rmSync(directory,{recursive:true,force:true})})
const makeSession=(user:string,token:string,authenticatedAt=new Date().toISOString())=>payload.create({collection:'auth-sessions',data:{tokenHash:hashOpaqueToken(token),user,authenticatedAt,lastSeenAt:authenticatedAt,expiresAt:new Date(Date.now()+60_000).toISOString()},overrideAccess:true})
describe('user invitation and identity administration',()=>{
it('creates a hashed local invitation without persisting the one-time credential in records or audit',async()=>{const result=await service.createUserInvitation(payload,owner,{email:'NEW@EXAMPLE.TEST',roles:['editor','approver']});expect(result.invitation).toMatchObject({email:'new@example.test',roles:['editor','approver']});const token=new URL(result.inviteURL).hash.slice('#invite='.length);const stored=(await payload.find({collection:'invitations',overrideAccess:true})).docs[0]!;expect(stored.tokenHash).not.toBe(token);expect(JSON.stringify(await payload.find({collection:'audit-events',overrideAccess:true}))).not.toContain(token);await expect(service.createUserInvitation(payload,owner,{email:'new@example.test',roles:['editor']})).rejects.toThrow('active invitation')})
it('replaces a retired provider invitation for the same email with a local invite',async()=>{const oldToken='retired-google-invite-token';await payload.create({collection:'invitations',data:{email:'migrate@example.test',provider:'google',providerIssuer:'https://issuer.example.test',providerSubject:'retired-google-subject',tokenHash:hashOpaqueToken(oldToken),roles:['editor'],expiresAt:new Date(Date.now()-60_000).toISOString()},overrideAccess:true});const replacement=await service.createUserInvitation(payload,owner,{email:'migrate@example.test',roles:['sales']});expect(replacement.invitation).toMatchObject({email:'migrate@example.test',roles:['sales']});expect((await payload.find({collection:'invitations',where:{email:{equals:'migrate@example.test'}},overrideAccess:true})).docs).toHaveLength(1);const enroll=await import('../app/api/auth/enroll/route.js');const response=await enroll.POST(new Request('http://cms.example.test/api/auth/enroll',{method:'POST',headers:{origin:'http://cms.example.test','content-type':'application/json'},body:JSON.stringify({action:'prepare',token:oldToken})}));expect(response.status).toBe(403)})
it('revokes a local invitation so it cannot be listed as live',async()=>{const created=await service.createUserInvitation(payload,owner,{email:'revoke@example.test',roles:['sales']});await expect(service.revokeUserInvitation(payload,owner,created.invitation.id)).resolves.toEqual({id:created.invitation.id});expect((await service.loadUsersWorkspace(payload)).invitations).toHaveLength(0);expect((await payload.findByID({collection:'invitations',id:created.invitation.id,overrideAccess:true})).acceptedAt).toEqual(expect.any(String))})
it('updates multiple roles, revokes target sessions and records the security event',async()=>{const target=await payload.create({collection:'users',data:{email:'editor@example.test',name:'Editor',roles:['editor']},overrideAccess:true});const session=await makeSession(target.id,'target-token');await service.updateManagedUser(payload,owner,{id:target.id,name:'Editor Person',roles:['editor','approver'],disabled:false});expect(await payload.findByID({collection:'auth-sessions',id:session.id,overrideAccess:true})).toHaveProperty('revokedAt',expect.any(String));expect((await payload.find({collection:'audit-events',where:{event:{equals:'identity.roles_changed'}},overrideAccess:true})).totalDocs).toBe(1)})
it('blocks removing the final active Owner in both service and canonical collection paths',async()=>{await expect(service.updateManagedUser(payload,owner,{id:owner.id,name:'Owner',roles:['editor'],disabled:false})).rejects.toThrow('active Owner');await expect(payload.update({collection:'users',id:owner.id,data:{disabled:true},overrideAccess:true})).rejects.toMatchObject({ data: expect.objectContaining({ errors: expect.arrayContaining([expect.objectContaining({ message: 'At least one active Owner is required.' })]) }) });await expect(payload.delete({collection:'users',id:owner.id,overrideAccess:true})).rejects.toMatchObject({ data: expect.objectContaining({ errors: expect.arrayContaining([expect.objectContaining({ message: 'At least one active Owner is required.' })]) }) });await payload.create({collection:'users',data:{email:'owner2@example.test',name:'Second',roles:['owner']},overrideAccess:true});await expect(payload.update({collection:'users',id:owner.id,data:{disabled:true},overrideAccess:true})).resolves.toMatchObject({disabled:true})})
it('allows an already-disabled former Owner to be edited without counting it as the last active Owner',async()=>{const disabled=await payload.create({collection:'users',data:{email:'disabled-owner@example.test',name:'Disabled Owner',roles:['owner'],disabled:true},overrideAccess:true});await expect(service.updateManagedUser(payload,owner,{id:disabled.id,name:'Former Owner',roles:['editor'],disabled:true})).resolves.toMatchObject({name:'Former Owner',roles:['editor'],disabled:true})})})
describe('self-service sessions',()=>{it('lists only own sessions, marks current, and safely revokes one or all',async()=>{const current=await makeSession(owner.id,'current-token');const other=await makeSession(owner.id,'other-token');const foreign=await payload.create({collection:'users',data:{email:'other@example.test',name:'Other',roles:['editor']},overrideAccess:true});const foreignSession=await makeSession(foreign.id,'foreign-token');const listed=await service.loadAccountSessions(payload,owner.id,'current-token');expect(listed).toHaveLength(2);expect(listed.find((item:any)=>item.id===current.id)?.current).toBe(true);expect(JSON.stringify(listed)).not.toContain('tokenHash');await expect(service.revokeAccountSessions(payload,owner,{sessionID:foreignSession.id})).rejects.toThrow('not found');await service.revokeAccountSessions(payload,owner,{sessionID:other.id});expect(await payload.findByID({collection:'auth-sessions',id:other.id,overrideAccess:true})).toHaveProperty('revokedAt',expect.any(String));await service.revokeAccountSessions(payload,owner,{all:true});expect(await payload.findByID({collection:'auth-sessions',id:current.id,overrideAccess:true})).toHaveProperty('revokedAt',expect.any(String));expect((await payload.find({collection:'audit-events',overrideAccess:true})).docs.map((event:any)=>event.event)).toEqual(expect.arrayContaining(['identity.session_revoked','identity.sessions_revoked']))})})

describe('user and account HTTP boundaries',()=>{
  it('requires Owner access, same-origin CSRF and fresh authentication for identity writes',async()=>{
    const {cookieName,newOpaqueToken,SESSION_COOKIE}=await import('../src/identity.js');const route=await import('../app/api/users/workspace/route.js');const token=newOpaqueToken();await makeSession(owner.id,token)
    const cookie=`${cookieName(SESSION_COOKIE)}=${token}`
    const listed=await route.GET(new Request('http://cms.example.test/api/users/workspace',{headers:{cookie}}));expect(listed.status).toBe(200);expect(JSON.stringify(await listed.json())).not.toContain('tokenHash')
    const input={action:'invite',email:'route-invite@example.test',roles:['editor']}
    expect((await route.POST(new Request('http://cms.example.test/api/users/workspace',{method:'POST',headers:{cookie,origin:'http://wrong.example.test'},body:JSON.stringify(input)}))).status).toBe(403)
    const editor=await payload.create({collection:'users',data:{email:'route-editor@example.test',name:'Editor',roles:['editor']},overrideAccess:true});const editorToken=newOpaqueToken();await makeSession(editor.id,editorToken)
    expect((await route.GET(new Request('http://cms.example.test/api/users/workspace',{headers:{cookie:`${cookieName(SESSION_COOKIE)}=${editorToken}`}}))).status).toBe(403)
    expect((await route.POST(new Request('http://cms.example.test/api/users/workspace',{method:'POST',headers:{cookie:`${cookieName(SESSION_COOKIE)}=${editorToken}`,origin:'http://cms.example.test'},body:JSON.stringify(input)}))).status).toBe(403)
    const created=await route.POST(new Request('http://cms.example.test/api/users/workspace',{method:'POST',headers:{cookie,origin:'http://cms.example.test'},body:JSON.stringify(input)}));expect(created.status).toBe(201)
    const createdBody=await created.json();expect((await route.POST(new Request('http://cms.example.test/api/users/workspace',{method:'POST',headers:{cookie,origin:'http://cms.example.test'},body:JSON.stringify({action:'revoke-invitation',id:createdBody.invitation.id})}))).status).toBe(200)
  })
  it('returns only the signed-in account sessions and clears the cookie on global sign-out',async()=>{
    const {cookieName,newOpaqueToken,SESSION_COOKIE}=await import('../src/identity.js');const route=await import('../app/api/account/sessions/route.js');const token=newOpaqueToken();await makeSession(owner.id,token);await makeSession(owner.id,'another-own-session');const cookie=`${cookieName(SESSION_COOKIE)}=${token}`
    const listed=await route.GET(new Request('http://cms.example.test/api/account/sessions',{headers:{cookie}}));expect(listed.status).toBe(200);const body=await listed.json();expect(body.sessions).toHaveLength(2);expect(body.sessions.filter((session:any)=>session.current)).toHaveLength(1)
    expect((await route.POST(new Request('http://cms.example.test/api/account/sessions',{method:'POST',headers:{cookie,origin:'http://wrong.example.test'},body:JSON.stringify({action:'revoke-all'})}))).status).toBe(403)
    const revoked=await route.POST(new Request('http://cms.example.test/api/account/sessions',{method:'POST',headers:{cookie,origin:'http://cms.example.test'},body:JSON.stringify({action:'revoke-all'})}));expect(revoked.status).toBe(200);expect(await revoked.json()).toMatchObject({revoked:true,signedOut:true});expect(revoked.headers.get('set-cookie')).toContain(`${cookieName(SESSION_COOKIE)}=`)
  })

})
